### ISSUE TITLE
Improve the dive activity page with some more features 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#10]
suggest some changes that can be made in https://akshitagupta15june.github.io/Moksh/story.html and also create a issue if you wanna add some changes

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by harshal2002** [comment]
Hello @akshitagupta15june 
The story.html page requires some changes here in the "4 yoga exercises to do at your desk", the fourth yoga image is not visible and the user will not be able to scroll to see the fourth image as it is not allowing to scroll to the fourth image.

![Screenshot (535)](https://github.com/akshitagupta15june/Moksh/assets/76609079/739930eb-e22f-4901-a8eb-f113f3312ef1)

I tried to look for a solution and got one. Simply by using the overflow-x: scroll property in CSS, we can make the images to become horizontally scrollable.

So I request you to assign me this issue as I am a GSSoC'23 Contributor
Looking to get a reply. Thankyou

**Comment by akshitagupta15june** [comment]
ok I am assigning you @harshal2002
