### ISSUE TITLE
[BUG]  improve READMEs code block's alignment

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#1000]
## Description

**Describe the bug:**
In the README.md, specifically on **Creating a Pull request** section. There is a problem wit the alignment with the code blocks. Which is causing to make unsymmetrical alignment. The code blocks has  a little bit of formatting which is a bullet point that makes the alignment unsymmetrical.

**Expected behavior:**
I want to make it align and remove the unnecessary formatting to align it properly and behave it as it should be.  

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to README.md 
2. Scroll down until to contributing section and below it, a  **Creating a Pull request** section  '....'
4. See the unsymmetrical or uneven alignment.

**Expected result:**
A clear and concise description of what you expected to happen at each step.

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/514a2d50-f3dd-4fad-8b3d-2311ee97fadb)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

Under gssoc23 assign this to me. thank you!!

**Comment by akshitagupta15june** [comment]
go for it
