### ISSUE TITLE
[STYLE CHANGE] Fix the footer on the shlok page

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#1001]
**Description:**
The footer seems to be distorted  due to some overlapping styling.

**Current Styling:**

<img width="1788" alt="Screenshot 2023-07-06 at 9 05 11 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/ec789555-9440-46e6-91f7-735623db84e4">

[Describe the current styling that needs to be changed.]

**Proposed Styling:**
<img width="1790" alt="Screenshot 2023-07-06 at 9 02 33 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/4f11f89b-a3cd-4e80-9bdb-143d75e0a591">

The contributor is expected to replicate the footer on the home page on shlok page.

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by Nayanika-12** [comment]
Please assign this to me @karthiknadar1204. I can do it.

**Comment by gauravsingh1281** [comment]
@akshitagupta15june @karthiknadar1204  please assign this issue to me. I want to work on it.

**Comment by Vidip-Ghosh** [comment]
@akshitagupta15june @karthiknadar1204 please assign this issue to me

**Comment by akshitagupta15june** [comment]
Make sure it is responsive and similar as index footer
