### ISSUE TITLE
[BUG] reduce navbar height

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1007]
https://akshitagupta15june.github.io/Moksh/

**Comment by rayarka26** [comment]
Please assign me this issue

**Comment by Sch476** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You, 
Sayantan Choudhury
GSSOC'23 Contributor

**Comment by RudraPrasadMahapatra** [comment]
can you please assign this issue under GSSOC 2023.i can fix ii.

**Comment by RitiChandak** [comment]
Please assign me this task

**Comment by Developer-Swati** [comment]
Please assign it to me @akshitagupta15june  mam

**Comment by yaten2302** [comment]
Hi @akshitagupta15june, plz assign this issue to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
Assigned!
