### ISSUE TITLE
[FEATURE REQUEST] Add a translation option in life blog

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1009]
https://akshitagupta15june.github.io/Moksh/Blogs/life.html

In translation hindi should be on top, search regarding this feature

the translate button should be just below image

**Comment by RitiChandak** [comment]
i want to work on it

**Comment by RudraPrasadMahapatra** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You,
Rudra Prasad
GSSOC'23 Contributor

**Comment by Developer-Swati** [comment]
I also want to work on it @akshitagupta15june  mam.

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by Viveksati5143** [comment]
I want to fix this issue @akshitagupta15june .
