### ISSUE TITLE
[FEATURE REQUEST] Add a translation option in despression and suicide blog 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1010]
In translation hindi should be on top, search regarding this feature

the translate button should be just below image
https://akshitagupta15june.github.io/Moksh/Blogs/depression.html

**Comment by RudraPrasadMahapatra** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You,
Rudra Prasad
GSSOC'23 Contributor

**Comment by RitiChandak** [comment]
hi i would like to work on it

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by RitiChandak** [comment]
Hello @akshitagupta15june 
Thank you for assigning me this task. I have just opened the website i know its weird to ask but could you please help me with this it is showing like this.
![image](https://github.com/akshitagupta15june/Moksh/assets/96969496/633f229e-21c7-46bd-a74c-bb664edfc158)
