### ISSUE TITLE
[FEATURE REQUEST] Add a translation option in strength blog

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1012]
In translation hindi should be on top, search regarding this feature

the translate button should be just below image

https://akshitagupta15june.github.io/Moksh/Blogs/Strength.html

**Comment by RudraPrasadMahapatra** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You,
Rudra Prasad
GSSOC'23 Contributor

**Comment by ArunMaramraj** [comment]
Can you assign this to me as part of GSSOC? @akshitagupta15june

**Comment by akshitagupta15june** [comment]
assigned!

**Comment by harshita-2003** [comment]
@akshitagupta15june do assign me this as its still not completed from past 3 weeks

**Comment by ArunMaramraj** [comment]
@harshita-2003 it is completed and PR has been merged
