### ISSUE TITLE
[FEATURE REQUEST] Add a translation option in word blog 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1013]
In translation hindi should be on top, search regarding this feature

the translate button should be just below image

https://akshitagupta15june.github.io/Moksh/Blogs/Words.html

**Comment by rayarka26** [comment]
Please assign me this issue

**Comment by RudraPrasadMahapatra** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You,
Rudra Prasad
GSSOC'23 Contributor

**Comment by Developer-Swati** [comment]
Please assign it to me @akshitagupta15june  mam

**Comment by akshitagupta15june** [comment]
@Vidip-Ghosh would u like to work on it?

**Comment by akshitagupta15june** [comment]
ok
