### ISSUE TITLE
[FEATURE REQUEST] Add a back arrow in all the blogs pages

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1014]
currently when you go to any blogs you can't go back to to blog.html and only through clicking on power of knowledge blog so please add a back button colour should be blue and it should take back to blog.html

![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/a61f1128-0f68-4f01-9e57-d725759f1157)

just like above (PS its just an emoji to let you know where the back button is required)

**Comment by rayarka26** [comment]
Please assign me this issue

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by RitiChandak** [comment]
please assign me this task
