### ISSUE TITLE
[BUG] Footer is not exact similar to index in the pomodoro page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1015]
we have a commonfooter.js but in the pomodoro rule some text is not visible also on clicking subscribe its not working same as index

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by Developer-Swati** [comment]
Please assign it to me @akshitagupta15june  mam

**Comment by Web403** [comment]
@akshitagupta15june Assign me this issue cause nobody is doing it right now.

**Comment by akshitagupta15june** [comment]
https://github.com/akshitagupta15june/Moksh/issues/1064 similar issue and some contributor is working, hence closing this
