### ISSUE TITLE
[BUG] Footer is not exact similar to index in the rejuvenate page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1016]
https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html

we have a commonfooter.js but in the pomodoro rule some text is not visible also on clicking subscribe its not working same as index

**Comment by rayarka26** [comment]
Please assign me

**Comment by RudraPrasadMahapatra** [comment]
Hi @akshitagupta15june , I would like to fix this issue. Please assign me this issue.

Thank You,
Rudra Prasad
GSSOC'23 Contributor

**Comment by ArunMaramraj** [comment]
Can you assign me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by Web403** [comment]
Assign me this issue. I can fix it.

**Comment by ritik48** [comment]
Please assign me this issue

**Comment by ArunMaramraj** [comment]
Hi @akshitagupta15june I commented initially on the issue right after it was assigned to someone else. Since he has withdrawn his issue, based on FCFS, can you assign me this?

**Comment by Developer-Swati** [comment]
@akshitagupta15june  please assign it to me

**Comment by RitiChandak** [comment]
Please assign it to me

**Comment by akshitagupta15june** [comment]
Hey this issue is being worked upon here https://github.com/akshitagupta15june/Moksh/issues/1062 hence closing it now
