### ISSUE TITLE
[STYLE CHANGE]  Moving the Sign Up for Newsletter prompt closer to the email subscribe bar

### ISSUE THREAD

**Issue by cation03** [akshitagupta15june/Moksh#1018]
**Description:**

Moving the Sign Up for Newsletter prompt closer to the email subscribe bar.

**Reason for Change:**

This would help enhance usability as it was difficult for me to find the subscribe bar after reading "Sign up for the newsletter".

**Current Styling:**

![image](https://github.com/akshitagupta15june/Moksh/assets/78123938/20281fbb-1f0d-49ea-874d-055a23eebc81)

**Proposed Styling:**

Moving the "Sign Up For Our Newsletter" line and "Get weekly updates..."closer to the email subscribe bar so that it appears coherent.

**Additional context**

Please assign me this issue under GSSoC.

**Comment by akshitagupta15june** [comment]
hey we have a common footer.js and also right now some pages have footer issues so I want that should be improved then we can work on this
