### ISSUE TITLE
[BUG] Fix the moksh logo in navbar of the home page

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1022]
## Description

**Describe the bug:**
The moksh logo in the navbar of home page is broken

**Expected behavior:**
Moksh logo should appear

**Actual behavior:**
As shown in the screenshot

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'index.html'
2. See navbar

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/100852245/710d622a-e47c-4e26-818d-e7a86e3653b2)

**Comment by ankitjt** [comment]
the image is not broken per-se , the format used is works mostly on the latest versions of most browser. However, chrome supports it, try to open it in latest version of chrome.
