### ISSUE TITLE
[BUG] Need to be fixed proper responsive for mobile device user on the iskon event page.....

### ISSUE THREAD

**Issue by Brijesh1963** [akshitagupta15june/Moksh#1037]
Need to be fixed proper responsive for mobile device user on the iskon event page.....
Actual behaviour:

The text will overlayed on another text,as well as the images also.....

Expected Behaviour:

It will need to clean and as well as proper arrangements...
![20230708_181620](https://github.com/akshitagupta15june/Moksh/assets/98037970/727f240a-36c5-4c5a-b241-dedb4bd5543f)

**Comment by ankitjt** [comment]
do a fresh fetch, iskcon page is updated.
