### ISSUE TITLE
[STYLE CHANGE] Improving sidebar of home page

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1041]
**Description:**
The sidebar of the homepage looks so simple

**Reason for Change:**
As the sidebar of blog.html it too can be enhanced.

**Current Styling:**
Simple white colour need to be changed

**Proposed Styling:**

It  can be matched with the home page design i.e. greenish colour or as recommended.

**Screenshots or Design Mockups (optional):**

<img width="959" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/100852245/2e5b6ecf-5385-48e9-8fb3-3db922dff676">

**Priority Level (optional):**

- [ ] Low
- [X] Medium
- [ ] High

**Comment by Viveksati5143** [comment]
@akshitagupta15june Please assign it to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
can u suggest UI like u want to add some greenish I want to see how will it look

**Comment by Viveksati5143** [comment]
> can u suggest UI like u want to add some greenish I want to see how will it look

Sure
