### ISSUE TITLE
[BUG]  Fix typo in README.md

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#1050]
## Description

**Describe the bug:**
In the documentation, I saw a typo which is `brokel` that should be corrected to `broken`. 

**Expected behavior:**
I want to make the documentation free from typos to improve the clarity of its purpose 

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to README.md
2. Browse until you reach the `GSSOC'23 Pointer System` section
3. and check again for heading `Level 1 - Documentation/Minor bug fix`
4. Check the error in the `points 10`. In the 3rd bullet point, you can see the typo

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/a081b26d-5577-43d9-adf3-98b5b6714e89)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

ASSIGN THIS TO ME under GSSOC23

**Comment by abuharish02** [comment]
Assign to me I will fix it.

**Comment by jfmartinz** [comment]
can you pls check? @akshitagupta15june

**Comment by jfmartinz** [comment]
@akshitagupta15june  assign this to me
