### ISSUE TITLE
Improve the rejuvenate page 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1062]
https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html
steps to follow
1) Take reference from iskcon page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html, add the same navbar from iskcon to rejuvenate page 
2)remove the background picture from rejuvenate page
3) add same footer of iskcon page in rejuvenate page
4) Make sure whole page is responsive 
5) Add screenshot in pull request to show responsiveness

**Comment by UdhbhavSinghRana** [comment]
can you assign me this?

**Comment by akshitagupta15june** [comment]
ok! Please follow all guideline, responsiveness is very important

**Comment by ritik48** [comment]
@akshitagupta15june please assign this issue to me

**Comment by UdhbhavSinghRana** [comment]
![Screenshot from 2023-07-12 15-01-08](https://github.com/akshitagupta15june/Moksh/assets/102753277/04a7a3a5-63cc-415e-92df-e6c2b0f18d4d)
![Screenshot from 2023-07-12 15-00-44](https://github.com/akshitagupta15june/Moksh/assets/102753277/23a33ad0-e4e3-44ad-9ec1-65936af1b932)
![Screenshot from 2023-07-12 15-00-22](https://github.com/akshitagupta15june/Moksh/assets/102753277/e55a0c09-25c0-414f-bb7c-76d5fcf82efb)
this is how the site is looking in different sizes the only thing not working right now it the menu button on small screen you just have to add an onclick event on that button that will add a class to side-scroll nav "right-[0px]" but im not able to do it for some reason @akshitagupta15june
