### ISSUE TITLE
Improve the divine activities page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1063]
https://akshitagupta15june.github.io/Moksh/Divine_page/story.html
steps to follow

1)Take reference from iskcon page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html, add the same navbar from iskcon to divine activities page
2)remove the background picture from divine activities page
3) add same footer of iskcon page in divine activities page
4) Make sure whole page is responsive
5) Add screenshot in pull request to show responsiveness

**Comment by rayarka26** [comment]
Please assign me this issue

**Comment by Viveksati5143** [comment]
Please assign this issue to me I dont have worked in any level 2 issue yet

**Comment by SrushtiPatil1** [comment]
Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
ok! Please follow all guideline, responsiveness is very important

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me. I want to work on it

**Comment by akshitagupta15june** [comment]
Any help u need!

**Comment by rayarka26** [comment]
No i will complete it today
