### ISSUE TITLE
[BUG] Navbar &footer of Pomodoro rule page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1064]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html

Steps to follow
1) Add same navbar present in iskcon page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html in the pomodoro page
2) Add same footer from iskcon page in the pomodoro page
3) Make sure whole page is responsive
4)Add screenshot in pull request to show responsiveness

**Comment by ArunMaramraj** [comment]
Can you assign me this @akshitagupta15june

**Comment by Viveksati5143** [comment]
Please assign this issue to me I dont have worked in any level 2 issue yet

**Comment by akshitagupta15june** [comment]
ok! Please follow all guideline, responsiveness is very important
