### ISSUE TITLE
[BUG] Improve the shlok page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1065]
https://akshitagupta15june.github.io/Moksh/shlok_page/motivation.html
steps to follow

1)Take reference from iskcon page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html, add the same navbar from iskcon to shlok page
2)remove the background picture from shlok page
3) add same footer of iskcon page in shlok page
4) Make sure whole page is responsive
5) Add screenshot in pull request to show responsiveness

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me

**Comment by Viveksati5143** [comment]
Please assign this issue to me I dont have worked in any level 2 issue yet

**Comment by akshitagupta15june** [comment]
ok! Please follow all guideline, responsiveness is very important

**Comment by Vidip-Ghosh** [comment]
<img width="1680" alt="Screenshot 2023-07-14 at 12 21 35" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/2d94c35c-20cc-47e2-b160-758ae909d66c">
@akshitagupta15june Is this alright or do I need to add same navbar content as in events page??

**Comment by akshitagupta15june** [comment]
hey can u see this powered by google translate text can be removed
also can u show the page responsiveness and also footer responsiveness
