### ISSUE TITLE
[BUG] Karma image becomes distorted in mobile view

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1066]
https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/3a1d3a32-6adf-4950-b74a-70cf827eeb81)

**Comment by akshitagupta15june** [comment]
go fot it!

**Comment by debdutta04** [comment]
please assign me this issue

**Comment by akshitagupta15june** [comment]
assigned!
