### ISSUE TITLE
[FEATURE REQUEST] Improve the 'power of sloks' page

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1079]
## Description

**Is your feature request related to a problem? Please describe.**
The Power of sloks page can be enhanced

**Describe the solution you'd like**
Adding header, 
footer,
background image,
enhancing the overall page.

**Screenshots or Mockups** (optional)
<img width="958" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/100852245/f2a028cf-399d-45cb-a915-d9cedca39ce2">

**Priority** (optional)
[X] High

**Comment by MeenuyD** [comment]
yes it looks very simple we should make it more attractive I would like to work on this issue can you please assign it to me

**Comment by Viveksati5143** [comment]
Hey @akshitagupta15june ,
now #1065 is merged so please assign this issue to me so i can start working on it!!
