### ISSUE TITLE
UI change in the featured karma page.

### ISSUE THREAD

**Issue by sabeenaviklar** [akshitagupta15june/Moksh#1081]
**Description:**
I will make some UI changes in which it will increase user experience. The style is not well aligned with the Site.

[Provide a clear and concise description of the style change you are requesting.]

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**
The current user experience and
<img width="1268" alt="Screenshot 2023-07-14 at 1 47 35 PM" src="https://github.com/akshitagupta15june/Moksh/assets/122459291/5acb01b6-4ef5-41ae-be1a-25d22331e3b0">
 styling is not good.

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by akshitagupta15june** [comment]
Go for it
