### ISSUE TITLE
[BUG]Navbar Links Error

### ISSUE THREAD

**Issue by RitiChandak** [akshitagupta15june/Moksh#1087]
## Description

**Describe the bug:**
the navbar links directing users to an error page instead of the main page.

**Expected behavior:**

**Actual behavior:**
A clear and concise description of what actually happened.

https://github.com/akshitagupta15june/Moksh/assets/96969496/30dd421a-23da-45b9-8792-9f7eecce34f6
## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by RitiChandak** [comment]
@akshitagupta15june please assign me this issue under gssoc'23

**Comment by akshitagupta15june** [comment]
Go for it!
