### ISSUE TITLE
[BUG] Pomodoro page Bug

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1091]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html
The lower text is merging with footer
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/c3045083-9a99-407c-87da-ea3602ee6de8)

**Comment by ArunMaramraj** [comment]
Hi @akshitagupta15june can you assign this to me as part of GSSOc?

**Comment by akshitagupta15june** [comment]
@Developer-Swati would u like to work on this

**Comment by Developer-Swati** [comment]
Ok I will try.

**Comment by khadar1020** [comment]
can i work on this issue [akshitagupta15june](https://github.com/akshitagupta15june) if any one are not working
