### ISSUE TITLE
[BUG] shlok page navbar is not working fine

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1092]
when you scroll down and click on features in shlok page the dropdown gets distorted
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/749101af-7482-4373-9d33-3437c26fbcc1)

**Comment by akshitagupta15june** [comment]
Take reference from rejuvenate page https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html

**Comment by ArunMaramraj** [comment]
Can you assign this to me?

**Comment by Developer-Swati** [comment]
@akshitagupta15june   I would like to work on it

**Comment by Developer-Swati** [comment]
@akshitagupta15june  I would like to work on it

**Comment by akshitagupta15june** [comment]
assigned!

**Comment by Developer-Swati** [comment]
@akshitagupta15june  but you told me that you would assign me an issue on priority on the behalf of a previous issues. So please assign it to me

**Comment by akshitagupta15june** [comment]
check this https://github.com/akshitagupta15june/Moksh/issues/1091 @Developer-Swati

**Comment by Developer-Swati** [comment]
Ok thanks @akshitagupta15june
