### ISSUE TITLE
[FEATURE REQUEST] Add a Scroll To Top Button

### ISSUE THREAD

**Issue by 5h0ov** [akshitagupta15june/Moksh#1096]
## Description

**Is your feature request related to a problem? Please describe.**
I would like to add a Scroll To Top Button in the website with the following concept:

![scrollbutton](https://github.com/akshitagupta15june/Moksh/assets/83227649/66f1173d-19c2-419b-bd3b-de1a0dec6ed8)

I will change the colour to fit the theme of the webpage!

**Describe the solution you'd like**
- Create a separate javascript and css file and implement the scroll to top button in them

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by sumitkr2000** [comment]
@akshitagupta15june Can I work on this issue?

**Comment by Aditi-P22** [comment]
Please assign me this issue under GSSOC'23

**Comment by sumitkr2000** [comment]
@akshitagupta15june please assign me this issue
