### ISSUE TITLE
add some more questions in bhagwadgita quiz 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#11]
https://akshitagupta15june.github.io/Moksh/quiz.html

u can take help of this iskcon vedabase library https://vedabase.io/

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by Yashika-Agrawal** [comment]
Hey . i m a GSsoc'23 contributor , please assign this issue to me as i have worked on quiz apps before too!.

**Comment by Deepanshu0703** [comment]
Can you assign this is to me too I want to add more questions

**Comment by ishitaa-dhingra** [comment]
Please assign me this issue under GSSOC23 i would also like to add more questions ...

**Comment by ankitjt** [comment]
@Yashika-Agrawal did you submit your PR for this? because I can't find any PRs from you and it's been more 2 weeks since it was assigned, so pl update the status by today, if no response we will assigning the issue to others.

**Comment by Yashika-Agrawal** [comment]
Yea , I will raise the PR today itself for this.

**Comment by Yashika-Agrawal** [comment]
Hey @ankitjt , I have raised the PR for this issue.

**Comment by Sushil919** [comment]
Please assign me this issue under GSSOC'23, I would like to add more questions to the quiz section

**Comment by DhananjayGoyalGL** [comment]
@akshitagupta15june Hey , I am a GSsoc'23 contributor , please assign this to me, I recently went through the quiz and want to add some more questions!!

**Comment by akshitagupta15june** [comment]
hey now no more questions are needed

**Comment by DhananjayGoyalGL** [comment]
> hey now no more questions are needed

Ok..
