### ISSUE TITLE
Fix the footer in shlok page

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#110]
<img width="1790" alt="Screenshot 2023-05-01 at 9 29 29 AM" src="https://user-images.githubusercontent.com/95973644/235404811-d8369b24-4aca-4316-ad7f-1ebf901e39d7.png">

**Comment by akshitagupta15june** [comment]
ok

**Comment by MOHDNEHALKHAN** [comment]
This issue is already fixed by me @akshitagupta15june

**Comment by MOHDNEHALKHAN** [comment]
Check #80 issue

**Comment by karthiknadar1204** [comment]
@MOHDNEHALKHAN you added the footer but is is out of  its position,i have fixed the css ,will submit pr for review after lunch.
