### ISSUE TITLE
[BUG]Features of navbar in shlok page are not correctly displaying

### ISSUE THREAD

**Issue by Developer-Swati** [akshitagupta15june/Moksh#1110]
## Description

**Describe the bug:**

**Expected behavior:**

**Actual behavior:**
A clear and concise description of what actually happened.

**Expected result:**

![IMG_20230717_134024](https://github.com/akshitagupta15june/Moksh/assets/125959657/5e009b1c-74ee-406b-b9ac-a4bc4bd182b0)

**Actual result:**

![IMG_20230717_133235](https://github.com/akshitagupta15june/Moksh/assets/125959657/aa67326d-7b60-4b84-9f7e-6a2a1dba10d9)

**Comment by akshitagupta15june** [comment]
one person is working on this issue https://github.com/akshitagupta15june/Moksh/issues/1092

**Comment by Developer-Swati** [comment]
Ok
