### ISSUE TITLE
[BUG] in ipad mode the nav-bar is overlapping

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#1114]
## Description
in ipad mode the nav-bar home button is overlapping with the moksh name.
**Describe the bug:**
![Screenshot (412)](https://github.com/akshitagupta15june/Moksh/assets/124120102/2898da2c-9e45-42d2-ac7d-5d91b8d720a9)

**Expected behavior:**
we can use media query and set a hamburger menu icon or we can change the margin space also.

please assign me this issue [akshitagupta15june](https://github.com/akshitagupta15june)

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by JiyaGupta-cs** [comment]
This issue is already resolved.
I think you should close this issue.
