### ISSUE TITLE
Bug in Readme File 

### ISSUE THREAD

**Issue by vaibhavx42** [akshitagupta15june/Moksh#112]
- While exploring the readme, I stumbled upon **_`a-spiritual-productivity-tool-for-mental-wellness`_** and **_`features`_**  section in 
table of contents to be broken .
- As other hyperlinks they should work but they're not.
- Can I improve it? Along with this I can add back to top sections since the readme might get bigger in future it'll be a good addition !

**Comment by akshitagupta15june** [comment]
Ok

**Comment by akshitagupta15june** [comment]
are u working on it?

**Comment by vaibhavx42** [comment]
- Yes akshita I'm waiting for response from the github team 

- The back to top thing is not an issue it has been done but the bug of a-spiritual-productivity-tool-for-mental-wellness it was actually right in your readme i revamped the whole readme but still it wasn't working is it possible it can be a markdown render error?

- I'm waiting for the response from them after that I'll submit the PR

**Comment by akshitagupta15june** [comment]
Ok

**Comment by ankitjt** [comment]
@vaibhavx42 is the bug fixed? did you push your PR?
