### ISSUE TITLE
[BUG] the subscribe button in footer of event.html page

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#1134]
## Description
the subscribe button the text in the button is not complete
**Describe the bug:**
the text of subscribe is coming out

**Expected behavior:**
we can change the padding.

## Screenshots
![Screenshot (426)](https://github.com/akshitagupta15june/Moksh/assets/124120102/1e7a3fc8-779a-41f7-a35c-5ca7749d2caa)

**Comment by khadar1020** [comment]
please assign me this issue [akshitagupta15june](https://github.com/akshitagupta15june)

**Comment by khadar1020** [comment]
please assign me this issue @akshitagupta15june

**Comment by Mandeep-009** [comment]
you are right but this is the case of reward.html and not in event.html
