### ISSUE TITLE
[footer UI] : arrangement of footer elements to enhance UI

### ISSUE THREAD

**Issue by Komal73** [akshitagupta15june/Moksh#1140]
## Description

to change arrangement of sign up for newsletter section, moksh summary, and others elements.
to enhance padding and margin 
![Screenshot 2023-07-20 152952](https://github.com/akshitagupta15june/Moksh/assets/115211296/942124b9-9610-4954-8505-54a1a2b75c23)

**Comment by Komal73** [comment]
@akshitagupta15june kindly check and assign this issue under GSSOC23

**Comment by SandeshGC** [comment]
I would like to work on this issue for hacktoberfest. Please assign it to me if it is available.
