### ISSUE TITLE
[BUG] Add CSS file

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1145]
## Description

**Describe the bug:**
The event.css file is not linked with event.html file

**Expected behavior:**
The event.css file should be linked with event.html file

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'iskcon folder'
2. Click on 'events'
3. Scroll down to 'event.html'

## Additional Information

**Device (please complete the following information):**
- OS: [Windows]
- Browser [Chrome]
- Version [11]

**Comment by KetanParmar02** [comment]
hey, @Viveksati5143 i'm interest to resolve this issue can you assign to me??
