### ISSUE TITLE
[BUG] Navbar in the pomodoro page is transparent and overlaps with contents on scrolling

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1156]
Please take a reference from the blog page https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html when scrolling down the navbar background turns white but this is not the case with pomodoro page

**Comment by Aditi-P22** [comment]
I want to work on this project. Please assign me this issue under GSSOC'23.

**Comment by Vidip-Ghosh** [comment]
Please assign this to me

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by JoeNeedham** [comment]
Please assign. I am a new contributor

**Comment by Sch476** [comment]
Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
Assigned

**Comment by sumitkr2000** [comment]
please assign me this issue @akshitagupta15june
