### ISSUE TITLE
[FEATURE REQUEST] Add navbar in meditation page similar as in blog page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1157]
Please take a reference from the blog page https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html and add the same navbar to meditation page https://akshitagupta15june.github.io/Moksh/AR_Meditate/meditation.html

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by RitiChandak** [comment]
please assign me this task

**Comment by ArunMaramraj** [comment]
Can u assign me this @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
