### ISSUE TITLE
[BUG] Navbar in the iskcon page is transparent and overlaps with contents on scrolling

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1158]
Please take a reference from the blog page https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html when scrolling down the navbar background turns white but this is not the case with iskcon page

**Comment by Harshu467** [comment]
Assign me

**Comment by RitiChandak** [comment]
please assign me this task

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by akshitagupta15june** [comment]
Assigned!
