### ISSUE TITLE
[BUG] Navbar in the divine activities page is transparent and overlaps with contents on scrolling

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1159]
Please take a reference from the blog page https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html when scrolling down the navbar background turns white but this is not the case with divine activities page https://akshitagupta15june.github.io/Moksh/Divine_page/story.html

**Comment by Harshu467** [comment]
assign me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by akshitagupta15june** [comment]
Assigned!
