### ISSUE TITLE
[BUG] dropdown of features part in the divine activities page is not similar to all pages

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1160]
https://akshitagupta15june.github.io/Moksh/Divine_page/story.html

for a reference check https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html features dropdown

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by Vidip-Ghosh** [comment]
Please assign this to me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by akshitagupta15june** [comment]
Assigned!
