### ISSUE TITLE
[BUG] Navbar in therejuvenate page is transparent and overlaps with contents on scrolling

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1161]
Please take a reference from the blog page https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html when scrolling down the navbar background turns white but this is not the case with rejuvenate page https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by Harshu467** [comment]
1. assign me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
