### ISSUE TITLE
[BUG] Footer of rejuvenate page is not similar to all pages

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1162]
https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html

for a reference have a look at blog page footer https://akshitagupta15june.github.io/Moksh/Blogs/Blog.html

**Comment by Aditi-P22** [comment]
Please assign me this issue under GSSOC'23

**Comment by RitiChandak** [comment]
Please assign me this task

**Comment by Harshu467** [comment]
assign me

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by akshitagupta15june** [comment]
Assigned!
