### ISSUE TITLE
[FEATURE REQUEST] Start bhagwad gita quiz should be highlighted and in top

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1164]
https://akshitagupta15june.github.io/Moksh/Divine_page/story.html

currently the quiz button is on bottom and also not catchy it should be highlighted in this page and on top

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by Vidip-Ghosh** [comment]
Please assign this to me

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by JoeNeedham** [comment]
> Assigned!

@akshitagupta15june did you want the button on top of "Desk Yoga Made Easy with these 3 Yoga Exercises!"? Where exactly is preferred. Thanks again for assigning!

**Comment by akshitagupta15june** [comment]
I can't see the image

**Comment by JoeNeedham** [comment]
> I can't see the image

Not sure why it didn't upload, but now it's there @akshitagupta15june

**Comment by akshitagupta15june** [comment]
not in top but can u keep it below the 4 Exercises to Boost Your Workday! also please beautify this button, or if you have any ideas to make it more creative

**Comment by akshitagupta15june** [comment]
are u still working on it?

**Comment by khadar1020** [comment]
please assign me this issue @akshitagupta15june

**Comment by JoeNeedham** [comment]
> are u still working on it?

I am going to do a PR today.
