### ISSUE TITLE
[FEATURE REQUEST] Add a background to pomodoro page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1165]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html

try to make it similar background colour as iskcon page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by Harshu467** [comment]
assign me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
