### ISSUE TITLE
[BUG] Add a background in gita generator

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1166]
https://akshitagupta15june.github.io/Moksh/shlok_page/motivation.html

make it similar to iskcon page background https://akshitagupta15june.github.io/Moksh/Iskcon/event.html

**Comment by Viveksati5143** [comment]
I want to work in this issue

**Comment by Harshu467** [comment]
assign me

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
