### ISSUE TITLE
[FEATURE REQUEST] Add a gita playlist section in the rejuvenate page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1167]
https://t.co/OzI2NaIiKy add this gita playlist section in the rejuvenate page, try to style page more catchy and attractive

**Comment by Viveksati5143** [comment]
I want to work in this issue

**Comment by rayarka26** [comment]
Please assign me this  issue

**Comment by Harshu467** [comment]
Assign me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
