### ISSUE TITLE
[BUG] Translate button is floated to left , make it in center

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1168]
https://akshitagupta15june.github.io/Moksh/Blogs/depression.html

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by rayarka26** [comment]
Please assign me

**Comment by Harshu467** [comment]
Assign me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june Please assign this issue to me I want to work on it

**Comment by sumitkr2000** [comment]
please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
