### ISSUE TITLE
Issue in footer

### ISSUE THREAD

**Issue by LovishMalhotra** [akshitagupta15june/Moksh#1186]
**Description:**

sign up newsletter not visible and subscribe button is not fit properly in the Pomodoro break page.

![Screenshot 2023-07-23 210431](https://github.com/akshitagupta15june/Moksh/assets/90837700/682f8c0b-62e3-4125-8735-8b9d8d0f7b21)

I will change the css of footer.
Please assign me this issue.

**Comment by akshitagupta15june** [comment]
Go for it
