### ISSUE TITLE
[BUG] - Error text in readme

### ISSUE THREAD

**Issue by 1Shubham7** [akshitagupta15june/Moksh#1187]
## Description

![image](https://github.com/akshitagupta15june/Moksh/assets/116020663/24a3a897-4697-4692-bcb8-dca1688c2ad2)

Discord should be in one line

## Screenshots
Already added

**Additional context:**

Please assign me this issue under GSSoC'23

**Comment by NextThread** [comment]
hey, i'd like to work on this issue
