### ISSUE TITLE
Restructure the codebase

### ISSUE THREAD

**Issue by aryasoni98** [akshitagupta15june/Moksh#119]

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by karthiknadar1204** [comment]
@aryasoni98 ,How do you suggest to restructure the codebase, could you please elaborate

**Comment by aryasoni98** [comment]
Basically restructure the file base. Like create the name folder.

**Comment by barry-g1076** [comment]
Hey @karthiknadar1204 , I'm new to working on open source project's. Could I work on this issue, I would put all files of same type into one folder eg. all javascript files will be in one folder. that way it would be easier to find different files.

**Comment by karthiknadar1204** [comment]
Ok I think there is already a issue to restructure the folder structure and @akshitagupta15june is working on it, reconfirm it once again
