### ISSUE TITLE
[STYLE CHANGE] Improving Timer in Pomodoro break

### ISSUE THREAD

**Issue by anushkaMohan** [akshitagupta15june/Moksh#1191]
**Description:**

Changing styling of timer on Pomodoro Break page

**Reason for Change:**
The timer in Pomodoro break is pretty simple. It styling can be improved.

**Current Styling:**

The styling of timer is basic right now.

**Proposed Styling:**

I want to change the timer to following style : 
![Screenshot (232)](https://github.com/akshitagupta15june/Moksh/assets/123250698/bb74608b-17c5-4ea7-87d1-1badb0a7caad)
![Screenshot (234)](https://github.com/akshitagupta15june/Moksh/assets/123250698/38c38ce7-cb94-4a23-baef-3f2467793654)
![Screenshot (231)](https://github.com/akshitagupta15june/Moksh/assets/123250698/b523657c-4450-44e5-8701-860f61ef5b47)

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

Within 4 days of opening this issue

**Possible Implementation Approach (optional):**

I will implement the above style using CSS and JavaScript

**Comment by akshitagupta15june** [comment]
yes go for it!
