### ISSUE TITLE
[BUG] the colour of navbar elements should be white in ar meditate page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1195]
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/18242ab3-de7e-45db-a87b-d470259c4081)

fix the colour according to when scrolling down it should not mix up with the navbar colour

**Comment by ArunMaramraj** [comment]
Can you assign me @akshitagupta15june

**Comment by Developer-Swati** [comment]
Please assign it to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!

**Comment by akshitagupta15june** [comment]
are u still working on it?

**Comment by Enhancer18** [comment]
yes i am working on it

**Comment by Enhancer18** [comment]
@akshitagupta15june plz close this issue as the pull request has been merged
