### ISSUE TITLE
[FEATURE REQUEST] Add the background and navbar to the bhagwadgita quiz page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1197]
https://akshitagupta15june.github.io/Moksh/quiz_page/quiz.html

Take reference from iskcon events https://akshitagupta15june.github.io/Moksh/Iskcon/event.html

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me

**Comment by gauravsingh1281** [comment]
Please assign this issue to me I

**Comment by gauravsingh1281** [comment]
Please assign this issue to me
