### ISSUE TITLE
[BUG] navabar elements of pomodoro break page are not visible 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1198]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html

Take reference from iskcon events page https://akshitagupta15june.github.io/Moksh/Iskcon/event.html

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me

**Comment by ArunMaramraj** [comment]
Can you assign me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Assigned!
