### ISSUE TITLE
[BUG] footer of pomodoro page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1199]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html footer is not similar to iskcon page take reference from iskcon page

**Comment by Viveksati5143** [comment]
I want to work kn this issue

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me

**Comment by Viveksati5143** [comment]
I'll work on this issue first

**Comment by akshitagupta15june** [comment]
Assigned!
