### ISSUE TITLE
Improve pomodoro page to more dynamic page like improve the time UI or content

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#12]
https://akshitagupta15june.github.io/Moksh/reward.html

**Comment by karthiknadar1204** [comment]
Can i work on this issue @akshitagupta15june ,please assign it to me

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,please assign this issue to me,i can improve the ui of the page and initiate a pr by this weekend along with other issues.

**Comment by karthiknadar1204** [comment]
@akshitagupta15june Can i work on this issue, please assign it to me.

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,please assign this issue to me
