### ISSUE TITLE
[BUG] Pomodoro.html page footer is distorted and not in place

### ISSUE THREAD

**Issue by ArunMaramraj** [akshitagupta15june/Moksh#1218]
## Description

The pomodoro.html page footer is not in place and is distorted

![image](https://github.com/akshitagupta15june/Moksh/assets/121447227/7aa64d70-0f3e-4017-81f4-d756f6c825b3)

**Comment by akshitagupta15june** [comment]
Please refactor this whole page not only footer but also align every item
