### ISSUE TITLE
[FEATURE REQUEST] add google translator in home page

### ISSUE THREAD

**Issue by S-ishita** [akshitagupta15june/Moksh#1221]
## Description

**Is your feature request related to a problem? Please describe.**
I want to add google translator in home page

**Describe the solution you'd like**
A google translate element will be added in navbar.

## Additional Information

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).
High
**Additional Notes** (optional)
Add any other notes or comments about the feature request here.
PLease assign this issue to me

**Comment by akshitagupta15june** [comment]
it distorts the other elemnts so its not needed currently
