### ISSUE TITLE
[BUG] Back to blog button is distorted in life blog 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1223]
https://akshitagupta15june.github.io/Moksh/Blogs/life.html

**Comment by ArunMaramraj** [comment]
can you assign me this @akshitagupta15june

**Comment by akshitagupta15june** [comment]
u are working on an issue so will assign some other contributor

**Comment by ArunMaramraj** [comment]
ok np

**Comment by debdutta04** [comment]
I would like to work on this issue please assign me

**Comment by akshitagupta15june** [comment]
Assigned
