### ISSUE TITLE
Overlapping section in pomodoro page

### ISSUE THREAD

**Issue by LovishMalhotra** [akshitagupta15june/Moksh#1225]
**Description:**
Issue in Pomodoro page 

The section on the Pomodoro page is overlapping.
![image](https://github.com/akshitagupta15june/Moksh/assets/90837700/b9ffd86f-1d21-4d43-ba69-8088e4014c96)

**Comment by LovishMalhotra** [comment]
@akshitagupta15june  assign me this issue

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by akshitagupta15june** [comment]
are u still working on it?

**Comment by Mayank-Sharma17** [comment]
@akshitagupta15june if he is not working on it, can you assign this issue to me.

**Comment by LovishMalhotra** [comment]
I am working on it 
will push code by today

**Comment by Mayank-Sharma17** [comment]
ok
