### ISSUE TITLE
[BUG] Space between the image and text is too much

### ISSUE THREAD

**Issue by ritikalath30** [akshitagupta15june/Moksh#1226]
## Description

**Describe the bug:**
The space between the image and the text creates a void that is not pleasing. 
I'd like to reduce the space.
I would also like to increase the font size to make it more appealing.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'Power of Knowledge blog'

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/64362328/02acc8d7-293f-4c69-ac83-da1f878437d6)

## Additional Information

**Device (please complete the following information):**
- OS: Windows
- Browser Chrome

**Comment by akshitagupta15june** [comment]
some contributor is working on it.
