### ISSUE TITLE
[STYLE CHANGE] [GSSOC] Adding margin to images and cards

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [akshitagupta15june/Moksh#1228]
**Description:**

[Provide a clear and concise description of the style change you are requesting.]
The UI looks too compact as there are no spaces or gaps between the cards and the page

**Reason for Change:**
Adding suitable spacing and margins and paddings would definately enhance the user experience which in turn aligns with the overall goal of the website.

**Current Styling:**
I have attached the SS of the current styling where there is scope for improvement.

**Proposed Styling:**
I can add proper margins and uniform spacings which would help enhance the user experience and make the UI of the website look more appealing to the user also it would appear more pleasing to the user.

**Screenshots of current ui:**
Current styling

![image](https://github.com/akshitagupta15june/Moksh/assets/97378312/585bf883-e988-4355-9c12-b51bea3c7fa8)

![image](https://github.com/akshitagupta15june/Moksh/assets/97378312/115f8fa8-1744-419f-8a69-d825019a7358)

**Comment by akshitagupta15june** [comment]
Hey its not required currently!.
