### ISSUE TITLE
add a blog section in the website 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#123]
inside blog section add this poem picture 
![image](https://user-images.githubusercontent.com/57909583/236743580-a2126cb4-e0a3-4dbe-847d-666b2d641f87.png)
with a title " A powerful poem on words"

**Comment by karthiknadar1204** [comment]
@akshitagupta15june I would like to work on this issue

**Comment by karthiknadar1204** [comment]
Should the blog section be added to an existing link or should we create a completely new link on the navbar?

**Comment by akshitagupta15june** [comment]
I think blog section should not be present inside the features drop-down it should be visible in index navbar and yes a new blog.html is required for this because this is just a start we can improve it further

**Comment by karthiknadar1204** [comment]
Ohk so when clicking on the blog section link on the navbar, the user will be redirected to a completely different page with the poem image and a heading

**Comment by akshitagupta15june** [comment]
There should be different folders with different topic, so this "words" topic will will have the poem inside it
![image](https://user-images.githubusercontent.com/57909583/236841961-6320c35c-a47c-4aab-8e59-c1dc09dc0400.png)
u can add this icon

**Comment by karthiknadar1204** [comment]
I have started the base work of setting up the page,will share ss of the base in sometime

**Comment by karthiknadar1204** [comment]
@akshitagupta15june I have prepared the folder for blog section and added the navbar footer as well to them, I'll create a card with the name of words first on this page, when the user clicks on this card called words, the user will be redirected to a different page where we will have the above icon and the main poem, does that sound right?

How do you want the icon to be placed on the screen, like a banner on the top or anything else

**Comment by akshitagupta15june** [comment]
just the folder icon,

**Comment by karthiknadar1204** [comment]
@akshitagupta15june will share the mock up of the blog section by late evening
Thank you

**Comment by karthiknadar1204** [comment]
Added blog link to the navbar
<img width="1792" alt="Screenshot 2023-05-14 at 7 01 23 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/42d6ce9f-5354-4fde-a7ea-fffc91fd3d93">


Created a blog section with the image as a card, will change the button styling and background of the card ,Could you suggest something for the styling, cant think of anything off my mind for the card button and the background
<img width="964" alt="Screenshot 2023-05-14 at 7 01 34 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/c6cb9a4a-f151-432c-9dcb-1831695f6be3">



On clicking the read more button on the card,the user will be redirected to this page,will be adding the poem here
<img width="1754" alt="Screenshot 2023-05-14 at 7 01 43 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/628517b8-9cfc-466a-ae00-a6763b09ed96">

**Comment by akshitagupta15june** [comment]
Wonderful!
Awesome work @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@akshitagupta15june do you have the poem on separate pages, adding the entire poem together as a single page look very bad

**Comment by karthiknadar1204** [comment]
@akshitagupta15june submitting a pr for review for the same ,will raise another issue to align the poems in the page.
Thank you

**Comment by shreya26-bit** [comment]
@akshitagupta15june , may I make a UI of Power of knowledge more attractive?...
