### ISSUE TITLE
[BUG] Event.html navbar doesn't work on mobile

### ISSUE THREAD

**Issue by ArunMaramraj** [akshitagupta15june/Moksh#1230]
https://github.com/akshitagupta15june/Moksh/assets/121447227/5423ab08-af3d-42be-89da-e47c86acf99c

**Comment by debdutta04** [comment]
@akshitagupta15june  please assign me this issue under Gssoc'23

**Comment by ArunMaramraj** [comment]
@akshitagupta15june can you check this?

**Comment by akshitagupta15june** [comment]
some contributor is working on it.

**Comment by ArunMaramraj** [comment]
@akshitagupta15june I don't see anyone working on navbar explicitly. Can you once check

**Comment by ArunMaramraj** [comment]
They are working on positioning of the pages

**Comment by akshitagupta15june** [comment]
oh yes they are working on responsiveness

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by ArunMaramraj** [comment]
Thank you @akshitagupta15june
