### ISSUE TITLE
Issue/Suggestion : Improve the UI of blog page 

### ISSUE THREAD

**Issue by harshita-2003** [akshitagupta15june/Moksh#1233]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by harshita-2003** [comment]
@akshitagupta15june do assign me'

**Comment by akshitagupta15june** [comment]
Hey its not required currently!
