### ISSUE TITLE
to make responsive the events card in mobile view (ss attached)

### ISSUE THREAD

**Issue by harshita-2003** [akshitagupta15june/Moksh#1234]
**Description:**

[Provide a clear and concise description of the style change you are requesting.]

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

![Screenshot 2023-07-28 002814](https://github.com/akshitagupta15june/Moksh/assets/119532943/596f4b46-0179-46c6-80e1-8560065d0a1d)

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

@akshitagupta15june  assign me this please

**Comment by akshitagupta15june** [comment]
some contributor is working on it.
