### ISSUE TITLE
[FEATURE REQUEST] - Adding a socials section and badges to that section in the readme

### ISSUE THREAD

**Issue by 1Shubham7** [akshitagupta15june/Moksh#1235]
## Description

**Is your feature request related to a problem? Please describe.**
We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.

## Additional Information

**Screenshots or Mockups** (optional)
Added above

**Priority** (optional)
Medium

**Additional Notes** (optional)
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by akshitagupta15june** [comment]
Hey its not required currently!.
