### ISSUE TITLE
[FEATURE REQUEST] Project Restructuring

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1237]
## Description
Some extra files in the Codebase are not organized!!

**Describe the solution you'd like**
- Adding extra css & js files in their respective folders
- Just leaving index.html, readme, contributors guide & code of conduct outside
- Setting proper links accordingly for proper functioning of website

**Screenshots or Mockups** (optional)
<img width="166" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/100852245/4272c58a-ac6d-403c-886d-ee0614be4d2d">

**Priority** (optional)
High

**Comment by Viveksati5143** [comment]
Please consider this issue under gssoc'23

**Comment by harshitkandpal** [comment]
hi can i work on this

**Comment by Viveksati5143** [comment]
> hi can i work on this

No

**Comment by akshitagupta15june** [comment]
hey its not required currently

**Comment by harshitkandpal** [comment]
ok i think it has been done as i forked it 
no problem
