### ISSUE TITLE
[BUG] WEBSITE NOT RESPONSIVE.

### ISSUE THREAD

**Issue by yashi-15** [akshitagupta15june/Moksh#1238]
## Description

**Some pages on the website does not have proper responsiveness: **
 1.  _Event_, _reward_ and _motivation_ pages are not responsive for all devices.
 2.  Navigation button in pages is not working properly in small devices view.

##Screenshots
![Screenshot (15)](https://github.com/akshitagupta15june/Moksh/assets/132138302/2c29be65-cab6-4c09-b420-3cdd3223f987)
![Screenshot (16)](https://github.com/akshitagupta15june/Moksh/assets/132138302/6fc5f9a2-69e2-4a34-9429-b172c2f91998)
![Screenshot (17)](https://github.com/akshitagupta15june/Moksh/assets/132138302/176d7d30-0d9a-479d-b4b9-29a86ccdf1dc)

 ** I would like to contribute and resolve this issue. Assign it to me under GSSOC'23 so that I can work on it. **

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by akshitagupta15june** [comment]
Please see to this issue also provide screenshots when evrything is completed and also it may not distort other element so make sure all are up to mark
