### ISSUE TITLE
Adding Pointer cursor for the language button in the home page.

### ISSUE THREAD

**Issue by mnik7044** [akshitagupta15june/Moksh#124]
In the home page when hovering the language column the cursor does not change to pointer/hand cursor, which may confuse some users who expect clickable elements to have a hand cursor. This issue is present on all pages of the website.

**Comment by mnik7044** [comment]
Hey @akshitagupta15june please assign this issue to me I want to work on it.

**Comment by akshitagupta15june** [comment]
Ok
