### ISSUE TITLE
[BUG] Overlapping Sections on pomodoro Page 

### ISSUE THREAD

**Issue by SHAIK-MUNEERUDDIN** [akshitagupta15june/Moksh#1240]
## Description

**Describe the bug:**
In our project, we have encountered an issue where two sections on a specific page are overlapping, resulting in a visually inconsistent layout. This needs to be addressed to ensure a seamless user experience.

**Expected behavior:**
The sections on the page should be displayed without any overlap, maintaining the intended design and layout.

**Actual behavior:**
Due to the issue, the two sections are overlapping, causing visual clutter and potential confusion for users.

## Reproduction Steps

**Steps to reproduce the behavior:**

Navigate to the Pomodoro personal break page.
Observe the overlapping section:s pomodoro text and about.

## Screenshots

![Screenshot (167)](https://github.com/akshitagupta15june/Moksh/assets/120248240/93aed908-de9b-42cb-b8dc-8d090b808dba)

## Additional Information

**Device (please complete the following information):**
- OS: [Windows]
- Browser [Firefox]

**Additional context:**

I would like to take ownership of resolving this issue and ensure that the page layout is visually consistent as per the design requirements. I am a GSSoC'23 contributor.

**Comment by akshitagupta15june** [comment]
a contributor is working on it
