### ISSUE TITLE
[BUG] index.html in Importance of Sloks is distorted completely

### ISSUE THREAD

**Issue by ArunMaramraj** [akshitagupta15june/Moksh#1251]
This issue is not assigned to anyone. I see others working on responsiveness of websites. Since this page is distorted completely, can you assign me this @akshitagupta15june 

![Screenshot 2023-07-30 191534](https://github.com/akshitagupta15june/Moksh/assets/121447227/2a881f4e-d668-4472-8c8a-273e4b4c2370)
![Screenshot 2023-07-30 191549](https://github.com/akshitagupta15june/Moksh/assets/121447227/c5ae2c7d-4e8a-42cd-b8b1-ab6b9c8358b0)

**Comment by debdutta04** [comment]
@akshitagupta15june mam please assign this issue to me  as i am working on it

**Comment by ArunMaramraj** [comment]
@debdutta04 this wasn't assigned assigned to anyone and I raised this 5 days ago.
