### ISSUE TITLE
add more shloks to shlok generator

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#126]
take reference from https://vedabase.io/en/library/bg/2/ https://vedabase.io/en/library/bg/3/ and follow proper format

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I can work on it please assign it to me

**Comment by justAkshitAgrawal** [comment]
Created a PR: https://github.com/akshitagupta15june/Moksh/pull/128

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I know some of the most beautiful verses of Bhagwad Gita which I can add to resolve this issue
