### ISSUE TITLE
Make card more attractive

### ISSUE THREAD

**Issue by Ahtaxam** [akshitagupta15june/Moksh#127]
In my point of view card in feature section should me little bit below and top padding and also rounder little bit, then it will look more beautiful what you think.

**Note**: i would like to work on this issue

![Screenshot from 2023-05-12 21-15-28](https://github.com/akshitagupta15june/Moksh/assets/64573767/aa649169-8809-4272-bf4a-60711e764c92)

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by Ahtaxam** [comment]
Now What you think. align card center on page. also change card button style.

![Screenshot from 2023-05-13 15-46-42](https://github.com/akshitagupta15june/Moksh/assets/64573767/fe5efa64-2d4d-4749-a7cb-b6c6dd3e5431)

change card button style. after hover text is white.

![Screenshot from 2023-05-13 15-47-07](https://github.com/akshitagupta15june/Moksh/assets/64573767/fe1c4b59-3bea-4d94-b69c-25d2bce06512)

**Comment by akshitagupta15june** [comment]
yes looks cool

**Comment by Ahtaxam** [comment]
opened PR
