### ISSUE TITLE
Add more question in bhagwadgita quiz 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#129]
https://akshitagupta15june.github.io/Moksh/story.html

quiz page https://akshitagupta15june.github.io/Moksh/quiz.html

**Comment by ashish-khankari** [comment]
Jai Shree Krishna Could You Please Assign me this task

**Comment by akshitagupta15june** [comment]
Hare Krishna 🙏
Sure

**Comment by ashish-khankari** [comment]
You can merge the PR
