### ISSUE TITLE
[FEATURE REQUEST] Improve the boxes and make it adjustable to texts in the gita storyline

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#1312]
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/5acd3376-160d-4367-8280-8f27a741b8f3)
https://akshitagupta15june.github.io/Moksh/Gita-Storyline/storyline.html

**Comment by Aditi-P22** [comment]
Please assign this issue to me

**Comment by akshitagupta15june** [comment]
Ok
