### ISSUE TITLE
[BUG] discord text allign issue

### ISSUE THREAD

**Issue by manzil-infinity180** [akshitagupta15june/Moksh#1317]
## Description

**Describe the bug:**

**Expected behavior:**

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**
<img width="1507" alt="Screenshot 2023-09-01 at 7 48 36 PM" src="https://github.com/akshitagupta15june/Moksh/assets/119070053/1a9f0c50-38f4-48a4-b408-b49732a48c69">

**Comment by manzil-infinity180** [comment]
asign to me

**Comment by manzil-infinity180** [comment]
https://github.com/akshitagupta15june/Moksh/pull/1318

**Comment by karthiknadar1204** [comment]
I want to contribute to this issue, please assign it to me
