### ISSUE TITLE
Navbar is not fixed in the home page

### ISSUE THREAD

**Issue by mnik7044** [akshitagupta15june/Moksh#132]
## Description
The navbar on the home page is not fixed, unlike the other pages of the website. This causes inconvenience to users as they have to scroll up to access the navigation menu.

## Expected behavior
The navbar should be fixed on the top of the screen on all pages of the website, including the home page.

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I would like to work on this issue please assign it to me.

**Comment by akshitagupta15june** [comment]
Ok
