### ISSUE TITLE
[BUG] Navbar and content overlapping

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#1333]
## Description

**Describe the bug:**
Navbar and the content are overlapping on the Pomodoro Spiritual Break page.

**Expected behavior:**
There should be some margin given to the content so there is space between the content and the navbar.

## Screenshots

<img width="960" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/8d286755-7791-4f8b-bf18-3017a8145fd9">

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows]
- Browser [e.g., Chrome]

**Comment by sagarbee** [comment]
It's Already solved!

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.
