### ISSUE TITLE
[FEATURE REQUEST] Home page texts are too large for small devices

### ISSUE THREAD

**Issue by ritik48** [akshitagupta15june/Moksh#1337]
## Description

**Is your feature request related to a problem? Please describe.**
Text on the home page is too large for small devices, and it doesn't look good

**Describe the solution you'd like**
I would like to make text size and images responsive when we switch to small screen devices

## Additional Information

**Screenshots or Mockups** (optional)
* Before
![moksh before](https://github.com/akshitagupta15june/Moksh/assets/84488726/227139b6-5352-4c24-bfd6-93e9277bbe83)

* After
![moksh after](https://github.com/akshitagupta15june/Moksh/assets/84488726/5cce1ecd-abfc-443f-9f18-8e1f27276ff8)

**Comment by akshitagupta15june** [comment]
Go for it!
