### ISSUE TITLE
[STYLE CHANGE] White outline on hover for the 'Read' button for the Power of Knowledge Blogs section.

### ISSUE THREAD

**Issue by kapooraryan** [akshitagupta15june/Moksh#1344]
**Description:**

I want to change the Read button on the blog cards for the Power of Knowledge blogs such that a white border outline appears upon hovering.

**Reason for Change:**
It is an additional feature improving the look of the website, in particular the 'Power of Knowledge Blogs' section.

**Current Styling:**
The current styling does not have any border outline appear upon hovering, only the scale of the whole blog card being changed.

**Proposed Styling:**
Adding a white border outline upon hovering over each blog card.

**Screenshots or Design Mockups (optional):**
Before:
![Before](https://github.com/akshitagupta15june/Moksh/assets/69362333/5461e397-992e-4c8b-9ba5-43a3f3ef9204)
After:
![After](https://github.com/akshitagupta15june/Moksh/assets/69362333/910e13ae-1086-4785-b1c1-de033881dd23)

**Additional Information (optional):**
Changes made to the Blog.html and newBlogStyle.css

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Possible Implementation Approach (optional):**
Modifying the newBlogStyle.css file and adding a class to the read buttons to make the changes.

Note: I have made the changes, I hope you accept my PR.

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by kapooraryan** [comment]
I have made the PR for the same, please have a look and let me know.
