### ISSUE TITLE
[BUG] On Smaller Screen Features not visible

### ISSUE THREAD

**Issue by ritik48** [akshitagupta15june/Moksh#1348]
## Description

**Describe the bug:**
On small screen devices, the features section of the home page is not visible. It's due to some uneven position value applied to the element.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. View the site on smaller screen
2. Scroll down to 'Features'

## Screenshots
![moksh features problem](https://github.com/akshitagupta15june/Moksh/assets/84488726/c70d6d2b-f261-4cc4-81f1-6ae5697b6bcd)

## Additional Information

**Device (please complete the following information):**
- OS: [Windows]
- Browser [Chrome]

**Comment by akshitagupta15june** [comment]
go for it
