### ISSUE TITLE
[STYLE CHANGE] 

### ISSUE THREAD

**Issue by kapooraryan** [akshitagupta15june/Moksh#1349]
**Description:**

The Navbar should cover the Moksh logo and title in the 'Rejuvenate' section of the website.

**Reason for Change:**

Visual appeal and it does not look like the logo is sticking out below the Navbar anymore.

**Current Styling:**

Currently the Moksh logo and title sticks out below the Navbar in the 'Rejuvenate' section.

**Proposed Styling:**

The Navbar should cover the Moksh logo and title without extending the Navbar.

**Screenshots or Design Mockups (optional):**

Before:
![Before_Rejuvenate](https://github.com/akshitagupta15june/Moksh/assets/69362333/edb0c0f1-b276-48c8-a644-a31e6251ef22)

After:
![After_Rejuvenate](https://github.com/akshitagupta15june/Moksh/assets/69362333/8db216aa-f8d9-41d7-a6ce-f4505ec1b2ea)

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Possible Implementation Approach (optional):**

Adding a top margin to the left section of the Navbar so that the Moksh logo and title are slightly pushed up and stay within the Navbar. This can be achieved by making changes to the rejuvenate.css file.

Please assign this issue to me under Hacktober fest. I will create the PR for the same at the earliest, Thanks.

**Comment by Devchawla2608** [comment]
@kapooraryan please assign this issue to me under hacktober fest.
