### ISSUE TITLE
Add dark theme to website

### ISSUE THREAD

**Issue by akhil888binoy** [akshitagupta15june/Moksh#136]

**Comment by nileshkr17** [comment]
Hi @akshitagupta15june , I am Nilesh, I would like to work on this issue. I will be making a PR as soon as I am done with resolving the issue. 
Please assign it to me.
Thank you.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! "

**Comment by Anushka20365** [comment]
Hello @akshitagupta15june ma'am ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by silwite** [comment]
Hello @akshitagupta15june ,I'm Manasi can you assign this to me under GSSOC'23.
Teach Stack- MERN stack
