### ISSUE TITLE
[FEATURE REQUEST] Navbar in Moksh -> meditation.html

### ISSUE THREAD

**Issue by Vidip-Ghosh** [akshitagupta15june/Moksh#1361]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
<img width="1680" alt="Screenshot 2023-10-05 at 19 23 52" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/00170f1c-a018-4319-a25e-c26dbfe4da75">
Currently, there is no Navbar in Medidation page. It needs to be added. 

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
Go for it
