### ISSUE TITLE
[BUG] Pull request template has stopped functioning

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#1363]
## Description

**Describe the bug:**
Pull request template has stopped functioning

**Expected behavior:**
A proper template for everyone making a pull request

**Actual behavior:**
No template

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'Moksh'
2. Click on 'Pull requests'
3. Scroll down to 'any pull request'

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/100852245/bbdf03b4-525b-4866-9779-2a77421c80c8)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

I would like to work on this issue

**Comment by Viveksati5143** [comment]
@akshitagupta15june can I start working on this issue?

**Comment by akshitagupta15june** [comment]
yes
