### ISSUE TITLE
Improving Meditation page

### ISSUE THREAD

**Issue by ankitjt** [akshitagupta15june/Moksh#138]
Meditation page looks very down scaled when opened on smaller screens.

![image](https://github.com/akshitagupta15june/Moksh/assets/48979824/bc4dead5-4d56-419f-8c8b-41599cee68af)

**Expected behaviour:**
Making the page responsive for all screen sizes.

**Comment by ankitjt** [comment]
@akshitagupta15june  Would like to work on this, If you can assign the issue.

**Comment by akshitagupta15june** [comment]
Ok
