### ISSUE TITLE
[BUG] Gita-Storyline link redirecting to wrong page

### ISSUE THREAD

**Issue by thanmaisai** [akshitagupta15june/Moksh#1397]
## Description

**Describe the bug:**
When clicked on Gita-Storyline 
the link gets redirected to 
https://akshitagupta15june.github.io/Gita-Storyline/storyline.html
insted of 
https://akshitagupta15june.github.io/Moksh/Gita-Storyline/storyline.html#

**Expected behavior:**
Proper navigation through pages.

**Actual behavior:**
Any number of times when clicked on Storyline should redirect to same link.

## Reproduction Steps

**Steps to reproduce the behavior:**
1. got top navigation bar 
2. Click on Gita-Storyline twice it will redirect to an unknown page.
**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
need to fill the URL linked in the navigation bar

## Screenshots
<img width="1440" alt="Screenshot 2023-10-24 at 11 33 45 PM" src="https://github.com/akshitagupta15june/Moksh/assets/91474486/6627f92a-19f1-4003-9897-2e1ca699d2a5">
<img width="1439" alt="Screenshot 2023-10-24 at 11 33 18 PM" src="https://github.com/akshitagupta15june/Moksh/assets/91474486/8ad34e31-30e8-4ed4-b1e2-d61aaea1c028">

## Additional Information

**Device (please complete the following information):**
- OS: [macOS]
- Browser [ Firefox]

**Additional context:**

**Comment by thanmaisai** [comment]
@akshitagupta15june Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023

**Comment by rahulkhandait-sde** [comment]
@akshitagupta15june Please assign me the 'Fix Bug: Clicking on "Gita Storyline" Option Shows 404 Error on the Same Page' issue under NSEC WOC. I'm looking forward to working on it!

**Comment by akshitagupta15june** [comment]
ok
