### ISSUE TITLE
improve the main page navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#140]

**Comment by karthiknadar1204** [comment]
@akshitagupta15june I would like to work on this issue

**Comment by akshitagupta15june** [comment]
Ok

**Comment by akshitagupta15june** [comment]
Navbar has been distorted

**Comment by karthiknadar1204** [comment]
yes,will fix it by tomorrow

**Comment by karthiknadar1204** [comment]
The blog section is not visible on the navbar as well,will fix it by tomorrow evening sure thing

**Comment by karthiknadar1204** [comment]
Fixed the navbar,submitting pr for review
