### ISSUE TITLE
Optimizing Web Performance and Code Clarity: Localizing External Resources and Adding Comments for Enhanced Efficiency and Readability

### ISSUE THREAD

**Issue by NithurjanA** [akshitagupta15june/Moksh#1425]
- Consider localizing external resources like Tailwind CSS and Google Fonts within the HTML code instead of direct external links to improve loading times and reduce dependency on external servers, thereby enhancing project robustness
- Adding comments to explain different sections or functions of the code

**Comment by akshitagupta15june** [comment]
hey its not needed currently
