### ISSUE TITLE
Add Open Graph Protocols and twitter tags to the website for efficient social media sharing

### ISSUE THREAD

**Issue by rakesh-vajrapu** [akshitagupta15june/Moksh#1429]
## Description
I want to add Open Graph Protocols to the website for efficient social media sharing. Please assign this issue to me @akshitagupta15june 

**Describe the solution you'd like**
I want to add Open Graph Protocols to the website for efficient social media sharing. Please assign this issue to me @akshitagupta15june

**Priority** (optional)
High

**Comment by akshitagupta15june** [comment]
not required currently
