### ISSUE TITLE
Adding Parallax to the Home page

### ISSUE THREAD

**Issue by raghav1482** [akshitagupta15june/Moksh#1430]
Adding Parallax feature on scroll on home page will enhance the beauty of the website.

**Kindly assign me this issue under #SWOC24 @akshitagupta15june**

**Comment by raghav1482** [comment]
Ma'am Kindly add SWOC24 Label on the issue.

**Comment by akshitagupta15june** [comment]
can u provide a reference like how parallax will improve it

**Comment by raghav1482** [comment]
> can u provide a reference like how parallax will improve it

it will make the background of home page slide relatively with the content to give appealing look
