### ISSUE TITLE
[FEATURE REQUEST] Adding Dark Mode 

### ISSUE THREAD

**Issue by Ab369** [akshitagupta15june/Moksh#1431]
## Description

**There is no DARK MODE available on the site.**
Dark mode will enhance the overall UI experience of the site. 

**Addition of DARK MODE toggle button**
 Add a dark mode toggle button on the navbar. On clicking the toggle enable/disable Dark mode.

**Potential Implementation**
1. Create a toggle Button
2. Switch between Dark/Light mode using Toggle function
3. Toggle function will invert colors and change colors based on dark mode UI.

**Additional Notes**
I would like to work on this Feature. Please assign it to me.

**Comment by akshitagupta15june** [comment]
hey its not needed curently!
