### ISSUE TITLE
[FEATURE REQUEST]  Needs to Modify the Chat Bubble 

### ISSUE THREAD

**Issue by RYGENN** [akshitagupta15june/Moksh#1432]
## Description

**In Features drop down menu ,there is gita storylline section where arjuna and krishna chat bubble is overriding the characters .**

## Additional Information

**Context**

**Potential Implementation** (optional)
you can make a perfect chat bubble instead of  a block section.

**Screenshots or Mockups** (optional)

![Screenshot 2024-01-03 211605](https://github.com/akshitagupta15june/Moksh/assets/91363907/96a61fbb-00f0-4200-817d-3513c166c658)

**Priority** (optional)
high

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
Go for it @RYGENN

**Comment by RYGENN** [comment]
> Go for it @RYGENN
