### ISSUE TITLE
[STYLE CHANGE] Issue in Feature section

### ISSUE THREAD

**Issue by KhushiRawat29** [akshitagupta15june/Moksh#1434]
**Destination**
1) Navigate to landing page
2) Scroll Down to "Features " section
3) Click on "Connect" button for the blog named "Connect with Iskcon Events"
4) scroll down a little

**Description:**
You can notice that the padding between the two sections is not proper. The padding works out for mobile or tablet view but doesn't look good for laptop view.

**Reason for Change:**

The requested style change will enhance  user experience and readability.

**Current Styling:**

max height for the first and second section and margins.

**Proposed Styling:**

Increase the max-height for both, for more spacing and applying margin top and margin bottom for better appearance.

**Screenshots or Design Mockups (optional):**

![2024-01-06 (4)](https://github.com/akshitagupta15june/Moksh/assets/117963603/7d868b90-cac4-4ed8-98df-0d7bf6b7e413)

**Additional Information (optional):**

Changes are made in event.html inline css

**Priority Level (optional):**

- [x] Medium

**Timeline (optional):**

I can implement it today

**Comment by KhushiRawat29** [comment]
okay

**Comment by KhushiRawat29** [comment]
@akshitagupta15june please assign this issue to me.

**Comment by KhushiRawat29** [comment]
This is how it will look . @akshitagupta15june 

![2024-01-06 (5)](https://github.com/akshitagupta15june/Moksh/assets/117963603/da6dfaaa-d051-45bc-9b1c-338ef0a58b32)

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by KhushiRawat29** [comment]
Okay
