### ISSUE TITLE
[BUG] Iskcon events page not responsive.

### ISSUE THREAD

**Issue by yashi-15** [akshitagupta15june/Moksh#1454]
I want to introduce responsiveness for this screen size in Iskcon events page. Please assign this issue to me under SWOC .

![Screenshot (210)](https://github.com/akshitagupta15june/Moksh/assets/132138302/ca196940-dac8-402e-a610-84402dd56d40)

**Comment by gitgoap** [comment]
@yashi-15  Can you provide the link of the page which is not response.?

**Comment by gitgoap** [comment]
@yashi-15 
Can you describe the issue a bit more?
When mobile view mode is switched on then it looks like it is responsive.
**Screenshots attached**

![Screenshot 2024-01-16 114650](https://github.com/akshitagupta15june/Moksh/assets/117789470/b2137a01-0562-405a-a0ee-2b9f53ddace4)

**Comment by yashi-15** [comment]
> @yashi-15 Can you describe the issue a bit more? When mobile view mode is switched on then it looks like it is responsive. **Screenshots attached**
> 
> ![Screenshot 2024-01-16 114650](https://private-user-images.githubusercontent.com/117789470/296949734-b2137a01-0562-405a-a0ee-2b9f53ddace4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTI1NjEsIm5iZiI6MTcwNTQxMjI2MSwicGF0aCI6Ii8xMTc3ODk0NzAvMjk2OTQ5NzM0LWIyMTM3YTAxLTA1NjItNDA1YS1hMGVlLTJiOWY1M2RkYWNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxMzM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGRiN2M1ZjdjNTQ5Njc4YmU5ZDQxMzcyNjJkNjJiMWZhZDJhZDJkYThiN2FjZTA1NmE3ZDRhNzE0YzQyMmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-hD5Iz--s6UADhvd0i1Hd-VHYFvhQ-KjhrT5G22H6d0)

For mobile size only, it is responsive...but for other screen sizes it's not responsive (like for the one showed in the screenshot in my previous comment)

- For example, if I switch the Dimensions to "Surface Pro 7" the orientation of the cards is not responsive:

![Screenshot 2024-01-16 191256](https://github.com/akshitagupta15june/Moksh/assets/132138302/21cb3b3b-9eec-4e17-b760-74e2a7a879b2)

- Also, when it is switched to "Surface Duo" the orientation of the cards is not proper i.e. aligned towards left but not at the center.

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by Sohan2213** [comment]
@akshitagupta15june I am interested to work on this issue!
