### ISSUE TITLE
Add this below content inside the "words" folder in blog section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#148]
content https://docs.google.com/document/d/1VpC3gr3IlCOxYo7c0O7jMYbC847RDTEqxPR2yQ0WUmU/edit?usp=sharing

add it inside words folder of blog section https://akshitagupta15june.github.io/Moksh/Blog.html

**Comment by ankitjt** [comment]
hey @akshitagupta15june would like to work on the blog page. 
Can you please assign the issue, if not assigned yet to anyone.

Thanks.

**Comment by akshitagupta15june** [comment]
ok

**Comment by manasi-jain** [comment]
Hi  @akshitagupta15june, I'm interested in working on this issue. Can I contribute to its resolution?

**Comment by EmptyNode** [comment]
hey @akshitagupta15june please assign this issue to me. i am eagerly waiting to work on this issue as a GSSOC 2023 contributor

**Comment by ankush9302** [comment]
is issue resolve ? @akshitagupta15june

**Comment by ankitjt** [comment]
Yea the issues is resolved.
