### ISSUE TITLE
Add Exit Button for Bhagavad Gita Quiz Termination During Gameplay

### ISSUE THREAD

**Issue by rahulkhandait-sde** [akshitagupta15june/Moksh#1493]
## Description

**Is your feature request related to a problem? Please describe.**
During the gameplay of the Bhagavad Gita quiz, there is currently no clear and easy way for users to exit the quiz and return to the main menu or previous screen. This can be frustrating for users who want to end the quiz session for any reason, such as needing to leave the page or wanting to start over. 

**Describe the solution you'd like**
Adding an exit button would provide a simple and intuitive way for users to terminate the quiz and navigate to other parts of the application.

## Additional Information

**Context**
Currently, once users start the quiz, there is no way to exit the quiz without completing it. Adding an exit button would enhance the user experience by providing a clear and easy way to end the quiz session if needed.

**Potential Implementation** (optional)

https://github.com/akshitagupta15june/Moksh/assets/90828823/83b9ed09-eca1-41a0-b87a-ecbe2baf0fd4

**Screenshots or Mockups** (optional)
![msedge_Q59LLBdeKd](https://github.com/akshitagupta15june/Moksh/assets/90828823/9d09be87-15ac-4044-9e77-b44a16895b3c)

**Priority** (optional)
Medium

**Before Change**
![msedge_lbAUVl78dD](https://github.com/akshitagupta15june/Moksh/assets/90828823/9f547247-1c04-4508-913b-7bfe32f1e699)

**After Change**
![msedge_Q59LLBdeKd](https://github.com/akshitagupta15june/Moksh/assets/90828823/dbeefe98-320a-4874-a7d4-ea459116c04c)

**Comment by akshitagupta15june** [comment]
go for it!
