### ISSUE TITLE
Improve Newsletter Box Email Text Color Visibility

### ISSUE THREAD

**Issue by rahulkhandait-sde** [akshitagupta15june/Moksh#1498]
**Description:**

The current color scheme used for the email text in the newsletter box 

**Reason for Change:**

The current text color in the newsletter box is not providing sufficient contrast against the background, leading to poor visibility and readability issues. Improving the text color will enhance user experience by ensuring that important information is easily visible and accessible to users.

**Current Styling:**

![Before-Edit](https://github.com/akshitagupta15june/Moksh/assets/90828823/597abe6c-cb37-4724-a834-e9f21ccb3c0f)

**Proposed Styling:**

![After-Edit](https://github.com/akshitagupta15june/Moksh/assets/90828823/a7f5040c-8fcc-4cae-966a-e3c1cb819740)

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Comment by akshitagupta15june** [comment]
That's a placeholder Ig s

**Comment by rahulkhandait-sde** [comment]
@akshitagupta15june ma'am, that's not a placeholder; you can check it on the website. Here is a screenshot for your reference 

![msedge_kyo8tl9pm0](https://github.com/akshitagupta15june/Moksh/assets/90828823/d3c4c626-a6dc-42b6-9ab8-4ee10075b245)
