### ISSUE TITLE
Improve navbar hover animation

### ISSUE THREAD

**Issue by mnik7044** [akshitagupta15june/Moksh#150]

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I want to work on this issue please assign it tp me

**Comment by akshitagupta15june** [comment]
congrats @mnik7044 you are one of the top contributor of moksh so dm me discord so that i can send you some awesome github stickers

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23
