### ISSUE TITLE
Difficulty toggling between menus due to language translation box

### ISSUE THREAD

**Issue by rahulkhandait-sde** [akshitagupta15june/Moksh#1500]
**Description:**

When navigating the website, users find it challenging to toggle between menus due to the language translation box obstructing the menu options. This impedes user experience and navigation efficiency.

**Reason for Change:**

The language translation box is positioned in a way that overlaps with the menu options, making it difficult for users to access the menus easily. This can lead to frustration and a poor user experience.

**Current Styling:**

![msedge_PncBwDKDno](https://github.com/akshitagupta15june/Moksh/assets/90828823/522f2cf6-351d-4834-ba84-6a8c44c112ed)

**Video**

https://github.com/akshitagupta15june/Moksh/assets/90828823/75a407a0-dfbd-4d3e-9c21-63d042e1c7d0

**Proposed Styling:**

https://github.com/akshitagupta15june/Moksh/assets/90828823/f9c7152b-da7d-48cd-98f6-0efbb9ceb2d8

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Comment by akshitagupta15june** [comment]
Done
