### ISSUE TITLE
Adding respective icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [akshitagupta15june/Moksh#1516]
## Description

COULD YOU PLZ ASSIGN THIS ISSUE TO ME UNDER GSSOC'24

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

**Describe alternatives you've considered**

One alternative could be redesigning the navbar layout or color scheme. However, adding icons is a more direct and effective solution to address the visual appeal and usability concerns of the navbar

## Additional Information

![Screenshot 2024-05-11 080754](https://github.com/akshitagupta15june/Moksh/assets/115486960/b42b07e8-c83a-4394-bcab-7ca31c71115b)

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

COULD YOU PLZ ASSIGN THIS ISSUE TO ME UNDER GSSOC'24

**Comment by priti200** [comment]
I would lilke to contribute upon this issue as I've made some good interacting navbars in my personal projects. 
I'll try to make this navbar as user friendly as it can be and come up with new navbar. So, could you please assign me for this issure? Waiting for your response.

Thankyou!!!!

**Comment by akshitagupta15june** [comment]
hey its not required currently
