### ISSUE TITLE
Update Quiz Rules

### ISSUE THREAD

**Issue by avanimathur** [akshitagupta15june/Moksh#1519]
Rule 4 says 'You can't exit from the quiz while you're playing.'
However, a 'Quit Quiz' button is present once we start answering. This rule needs to be modified in order to deliver an appropriate meaning.

![image](https://github.com/akshitagupta15june/Moksh/assets/151984867/6292fb95-6ba2-4766-ae5f-c9586c72929a)

![image](https://github.com/akshitagupta15june/Moksh/assets/151984867/bc28c40a-9723-4ec7-81bf-e2cb18096725)

This contribution is GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me
Thanks.

**Comment by akshitagupta15june** [comment]
hey its not required!
