### ISSUE TITLE
 Irregular spacing in descriptive content of Pomodoro Spiritual Break, Read a Shlok, Rejuvenate.

### ISSUE THREAD

**Issue by VanshikaAg12** [akshitagupta15june/Moksh#1522]
![jss](https://github.com/akshitagupta15june/Moksh/assets/156996206/e50879b8-a341-4ba0-ab77-8a3d6746e9c9)

There are irregular spacings in descriptive content of Pomodoro Spiritual Break, Read a Shlok, and Rejuvenate, as i have marked in the photo. Kindly assign me the task of fixing that under GSSoC'24.

**Comment by kritikasharma4** [comment]
I too want to work on this issue ,please assign it to me
Thankyou

**Comment by akshitagupta15june** [comment]
Go for it!!
