### ISSUE TITLE
Issue/Suggestion: Change search label to city in upcoming event or filter by state feature

### ISSUE THREAD

**Issue by dhanushsurendra** [akshitagupta15june/Moksh#1523]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:** 
![Screenshot 2024-05-12 114447](https://github.com/akshitagupta15june/Moksh/assets/50047808/05ebccca-3992-4bd0-b6de-c756f0fe424c)

**Expected:** The upcoming events section has state as a search label which is supposed to be city. It can be misleading to the users

**Actual:** Change the label to city

**Additional Details:**
Please assign this issue to me under gssoc'24. I'll fix it @akshitagupta15june

**Comment by akshitagupta15june** [comment]
someone is working on this issue!
