### ISSUE TITLE
[BUG] Mobile Interface Issue: Overlapping 'New Quote' Button in Shlokas Tab

### ISSUE THREAD

**Issue by suryapratapsingh26** [akshitagupta15june/Moksh#1524]
## Description

**Describe the bug:**
In the Shlokas tab on mobile, clicking 'Read' generates a random shloka, but the 'New Quote' button overlaps with the background, obscuring the verse's source. This impedes user understanding and navigation.

**Expected behavior:**
The "New Quote" button should be positioned appropriately on the mobile interface, ensuring it does not overlap with the background and obscuring the source of the generated shlokas. This allows users to easily identify the verse's origin when browsing through the Shlokas tab.

**Actual behavior:**
A clear and concise description of what actually happened.
After clicking "Read" in the Shlokas tab on mobile, a random shloka is generated, but the "New Quote" button overlaps with the background, making it difficult for users to discern the verse's source due to the obstruction caused by the overlapping button.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'Read a Shlok'
2. Click on 'Read'
3. Scroll down to 'New Qupte'

**Expected result:**
Initiating Action: Clicking on the "Read" button in the Shlokas tab on the mobile interface.
Expected Result: A random shloka should be generated.
Button Visibility: The "New Quote" button should be clearly visible and appropriately positioned, ensuring it does not overlap with the background or obscure the source of the generated shlokas.
Ease of Identification: Users should be able to easily identify the source of the generated shloka without any obstruction caused by overlapping interface elements.

**Actual result:**
Action Taken: Clicked on the "Read" button in the Shlokas tab on the mobile interface.
Actual Result: A random shloka was generated.
Button Visibility: The "New Quote" button overlapped with the background, obstructing the view of the verse's source.
Identification Difficulty: Users faced difficulty in identifying the source of the generated shloka due to the overlapping button, which obscured relevant information.
## Screenshots

![MOKSH ERROR](https://github.com/akshitagupta15june/Moksh/assets/146753809/804456c0-0ba0-46a8-88d2-f90cda774da1)

## Additional Information

**Device (please complete the following information):**
- 1QNEO6
- Browser [Chrome, Safari, Firefox]
- Version [Android 12]

**Additional context:**

**Comment by suryapratapsingh26** [comment]
I want to work on this issue Under GSSOC'24. Assign me this issue

**Comment by akshitagupta15june** [comment]
Go for it!!
