### ISSUE TITLE
[DOC] : Correcting CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by anglerfishlyy** [akshitagupta15june/Moksh#1529]
## Description

**Describe the bug:**
Its a grammatical erroneous document.

**Expected behavior:**
A clear and concise description of the rules that contributors should follow while working with open-source projects.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to CODE of the project.
2. Click on CODE_OF_CONDUCT.md .
3. Scroll down and read .
4. See  grammatical errors.

## Screenshots

![Screenshot (54)](https://github.com/akshitagupta15june/Moksh/assets/163823908/395c3127-38fb-4275-a79e-6a493edd8a6b)

**Additional context:**

The correct code of conduct sets the tone for respectful and inclusive interactions within an open source project, fostering a welcoming and collaborative community.

Lets  together make MOKSH outstanding !!

**Comment by anglerfishlyy** [comment]
Would you like me to solve it or not bot?

**Comment by anglerfishlyy** [comment]
Hey @akshitagupta15june , I would like to solve the issue that i created.
Can you assign it to me.

**Comment by akshitagupta15june** [comment]
hey no changes are required in this file currently.
