### ISSUE TITLE
Fix navbar on the Ar vr page

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#153]
Not getting redirected to the page on clicking on the links on the features dropdown and logo is not correct as well

**Comment by karthiknadar1204** [comment]
@akshitagupta15june please assign this issue to me,i would like to work on this

**Comment by akshitagupta15june** [comment]
ok

**Comment by ShivamAhir** [comment]
@akshitagupta15june please assign this issue to me ,if it is still open.

**Comment by ShivamAhir** [comment]
> Not getting redirected to the page on clicking on the links on the features dropdown and logo is not correct as well

The redirection to the page on clicking is working fine. However, there is an issue with the top-left logo, as it keeps changing and is not fixed in position.
