### ISSUE TITLE
[FEATURE REQUEST] : GREETING ON ARRIVAL

### ISSUE THREAD

**Issue by aditikhare16** [akshitagupta15june/Moksh#1532]
## Description

**Is your feature request related to a problem? Please describe.**
Yes, it can work as a sweet and warm greeting to the user.

**Describe the solution you'd like**
When the user opens this page, a prompt can come up "Hey, hope you are having a good day! How are you feeling today?" Followed by emojis with "bad...fine...good...very good".
Based on the selection of the user, a message or some suggestion would come up.
eg, if the user chooses "very good" the message would come up "yaay! keep up with that energy!"

**Describe alternatives you've considered**
None.

## Additional Information
It can act as a warm welcome which is essential for a website for mental health purposes.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
![image](https://github.com/akshitagupta15june/Moksh/assets/114524718/b39032d7-b2b0-4ef1-bc48-145274e2442b)
![image](https://github.com/akshitagupta15june/Moksh/assets/114524718/c462a647-be36-4258-9f5f-b5e4075b4978)
![image](https://github.com/akshitagupta15june/Moksh/assets/114524718/15fb0391-362d-4928-99e2-3776416d4607)

**Priority** (optional)
High

Please assign me this feature under GSSOC'24.

**Comment by akshitagupta15june** [comment]
hey its not required.

**Comment by aditikhare16** [comment]
But I was assigned this issue with the labels and I worked on this also. This is unfair.

**Comment by aditikhare16** [comment]
Also, this feature is good if you once give it a chance. I literally coded it all since I was assigned this.
