### ISSUE TITLE
[Feature]  : Add search Results 

### ISSUE THREAD

**Issue by sivaprasath2004** [akshitagupta15june/Moksh#1533]
## Description

**Is your feature request related to a problem? Please describe.**
- Add `search` results and shortlist by the `upcoming events`..

**Describe the solution you'd like**
- If the user can be search the upcoming events is can be showed next week this country to specify the results..

### Expected like this

[Screencast from 2024-05-12 08-10-53.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/efcadc0b-8489-40f7-b35b-94ed18c7b182)

**Comment by kapilG0** [comment]
Hello @akshitagupta15june can you please assign this issue to me

**Comment by Sagargupta028** [comment]
Hello Please assign this issue to me

**Comment by akshitagupta15june** [comment]
Go for it!!
