### ISSUE TITLE
[FEATURE REQUEST] Responsive should be added after click on read shlok 

### ISSUE THREAD

**Issue by kapilG0** [akshitagupta15june/Moksh#1535]
## Description

**Is your feature request related to a problem? Please describe.**
Responsive should be added after click on read shlok content not displaying properly in mobile 

**Describe the solution you'd like**
I will try to use css html for solving that

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
![Screenshot_2024_0514_192646](https://github.com/akshitagupta15june/Moksh/assets/59639410/34c8a84f-3da2-487f-bfb7-f8150f633e68)

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
Go for it!!
