### ISSUE TITLE
[BUG] after goes to index.html YouTube video should be responsive it is not showing properly in mobile

### ISSUE THREAD

**Issue by kapilG0** [akshitagupta15june/Moksh#1536]
## Description

**Describe the bug:**
Video is not showing properly in mobile view 

**Expected behavior:**
It should be showing properly on every device 
![Screenshot_20240514_194109](https://github.com/akshitagupta15june/Moksh/assets/59639410/89cae857-6a5c-42a3-b669-230d8fa7f12e)

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by kapilG0** [comment]
Hello @akshitagupta15june please assign this issue to me under gssoc 24

**Comment by kapilG0** [comment]
@akshitagupta15june Please closed this issue I am sorry but after running in my local and in inspect after selecting multiple device video is coming properly. I am sorry .
For different dimension i checked
![image](https://github.com/akshitagupta15june/Moksh/assets/59639410/797962c3-7c7d-4a27-8399-bfe3c85b168e)
![image](https://github.com/akshitagupta15june/Moksh/assets/59639410/a828e0e8-dc99-479a-94ff-62ed199d47a1)

**Comment by Janvibaghel** [comment]
his @akshitagupta15june  I'm interested in this issue, please assign it to me under GSSoc '24 .

**Comment by kapilG0** [comment]
> Go for it!!
@akshitagupta15june Please closed this issue I am sorry but after running in my local and in inspect after selecting multiple device video is coming properly. I am sorry .
For different dimension i checked
![image](https://github.com/akshitagupta15june/Moksh/assets/59639410/797962c3-7c7d-4a27-8399-bfe3c85b168e)
![image](https://github.com/akshitagupta15june/Moksh/assets/59639410/a828e0e8-dc99-479a-94ff-62ed199d47a1)

**Comment by kapilG0** [comment]
Hello @akshitagupta15june I am closing this issue I am sorry but after running in my local and in inspect after selecting multiple device video is coming properly. I am sorry .
For different dimension i checked please check above screen shot thank you
