### ISSUE TITLE
Add download all question button in PDF on the quize game and to show how many questions true marked by participant

### ISSUE THREAD

**Issue by AnkitMourya12** [akshitagupta15june/Moksh#1537]
Add a "Download All Questions" button to the quiz game's PDF to allow users to download the entire set of questions. Include a summary section in the PDF to display the total number of correctly answered questions by the participant.
And i also enhance the Quize Game page.

**Comment by AnkitMourya12** [comment]
I would like to work on this issue. @akshitagupta15june kindly assign this issue to me under GSSoc, lablel.

**Comment by akshitagupta15june** [comment]
Go for it!!
