### ISSUE TITLE
[STYLE CHANGE] 

### ISSUE THREAD

**Issue by rashichouhan-18** [akshitagupta15june/Moksh#1538]
Description:

Redesign the navigation bar to improve attractiveness and usability.

Reason for Change:

The current navigation bar lacks attractiveness and doesn't provide any functional elements, making it less engaging for users. A visually appealing and functional navigation bar can enhance user experience and make navigation easier.

Current Styling:

The current navigation bar consists only of a logo and lacks any other elements.

Proposed Styling:

Add functional elements such as menu items or links alongside the logo to improve usability. Incorporate visual elements like icons or styling effects to make the navigation bar more attractive and engaging.

**Comment by akshitagupta15june** [comment]
hey its not required currently.
