### ISSUE TITLE
Incorrect Label Case for 'Your email' Tag at Bottom of Page

### ISSUE THREAD

**Issue by soumojeet-mondal** [akshitagupta15june/Moksh#1540]
**Issue and Steps to Reproduce:**
   1) Scroll to the bottom of the Home Page on the website.
   2) Locate the form field with the label "Your email".
   3) Observe that the label is displayed in lowercase as "Your email".

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/157923320/8eb37b99-3eb7-4735-97a8-1246149d5624)

**Expected:**
The label for the form field at the bottom of the page should be displayed in the title case as "Your Email" to maintain consistency with other labels and improve readability.

**Actual:**
On the website, at the bottom of the page, there is a form field with the label "Your email". However, the label should be displayed in the title case as "Your Email" for consistency and clarity.

**Additional Details:**
 -  The issue affects the label for the email input field at the bottom of all pages on the website.
 -   Displaying the label in the title case ("Your Email") will improve consistency and align with standard conventions for labeling form fields.
 -   No functional impact is associated with this issue, but correcting it will enhance the visual presentation and user experience of the website.

**Comment by anshdeep0504** [comment]
Hi!! I am Anshdeep singh, contributor in GSSoC'24. I would like to address this issue and make the respective changes.

**Comment by akshitagupta15june** [comment]
hey its not required!
