### ISSUE TITLE
[FEATURE REQUEST] : Alerting Invalid mail address

### ISSUE THREAD

**Issue by sivaprasath2004** [akshitagupta15june/Moksh#1543]
## Description

**Is your feature request related to a problem? Please describe.**
- In the `/AR_Meditate/meditation.html` page i will check the  input doesn't given and click the `subscribe` button that is no warning alert..

**Describe the solution you'd like**
- If the user click the result that is alerting the user `Enter the mail address` that is not showing.
- please assign i will ready to add the new feature and implement..

### Error

[Screencast from 2024-05-15 18-15-45.webm](https://github.com/akshitagupta15june/Moksh/assets/121082414/0e500a45-5e31-47ba-8be9-3f956a575949)

**Comment by akshitagupta15june** [comment]
Go for it!!
