### ISSUE TITLE
[FEATURE REQUEST] Implement Dark and Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [akshitagupta15june/Moksh#1544]
## Description

**Is your feature request related to a problem? Please describe.**
Many users prefer to have control over the appearance of their applications, including the ability to switch between dark and light modes for better readability and reduced eye strain. Currently, the application lacks this feature, limiting user customization options.

**Describe the solution you'd like**
Integrate a dark and light mode toggle within the application's interface, allowing users to switch between modes seamlessly. When enabled, the dark mode should adjust the color scheme to darker tones, enhancing readability in low-light environments.

**Describe alternatives you've considered**
An alternative solution could involve implementing a theme selector with predefined themes, including dark and light modes. However, a toggle switch provides a more intuitive and straightforward user experience.

## Additional Information

**Context**
The addition of a dark and light mode toggle aligns with current design trends and user expectations for customizable application interfaces. Offering this feature enhances user satisfaction and usability.

**Potential Implementation** (optional)
The toggle switch can be placed in the application's settings menu or as a prominent button within the interface for easy access. Utilizing CSS variables and media queries can facilitate smooth transitions between dark and light modes.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Medium

**Additional Notes** (optional)
Considering the increasing demand for customizable user experiences, implementing a dark and light mode toggle can differentiate the application and attract more users.

**Comment by akshitagupta15june** [comment]
not required in website currently.
