### ISSUE TITLE
[BUG] Tweet button under Gita shlok generator does not paste correct text on Twitter

### ISSUE THREAD

**Issue by Shobhit-Nagpal** [akshitagupta15june/Moksh#1545]
## Description

**Describe the bug:**
The tweet button in the Gita Shlok generator does not paste the shlok onto the tweet when redirected to Twitter.

**Expected behavior:**
The expected behavior is that when redirected to twitter and the tweet shows up, it should already have the shlok copied onto the tweet.

**Actual behavior:**
Current behavior is that instead of copying the shlok, it copies "" on to the tweet

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to Gita Shlok Generator
2. Click on Tweet button
3. See the tweet text after being redirected to Twitter

**Expected result:**
At step 3, I expected to see the shlok ready to be tweeted

**Actual result:**
It just showed "" on the tweet

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/74096450/a1c6e928-8963-4fd3-9d55-4e676903ef46)

## Additional Information

**Device (please complete the following information):**
- OS: Linux
- Browser Chrome
- Version 123.0.6312.122 (Official Build) (64-bit)

**Additional context:**

Kindly assign this issue under my name with the relevant gssoc and level labels :)

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by Shobhit-Nagpal** [comment]
thanks! on it
