### ISSUE TITLE
enhancing the background of READ A SHLOK PAGE 

### ISSUE THREAD

**Issue by sahithinandikula** [akshitagupta15june/Moksh#1546]
**Description:**

The Read a Shlok page is not visually appealing it can be enhanced for better user interaction

**Reason for Change:**

The color of the buttons is not appealing, the hover effects are simple.
the text color can be changed so that it looks better and makes the user easier to read

**Current Styling:**
![image](https://github.com/akshitagupta15june/Moksh/assets/138794574/48046a75-6bd7-4aa3-9ef4-8150ba94cfec)

**Proposed Styling:**

->The color can be changed to a palette that suits the theme of spirituality.
->text styling can be changed
->Hover effects can be added

**Additional Information (optional):**

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [X ] High

**Timeline (optional):**

Can add the specified styling by the next evening

**Comment by akshitagupta15june** [comment]
go for it!
