### ISSUE TITLE
Stopping the continuous horizontal scroll on hover over MOKSH CONTRIBUTORS part

### ISSUE THREAD

**Issue by anwesha2002** [akshitagupta15june/Moksh#1547]
## Description

**Is your feature request related to a problem? Please describe.**
While hovering on moksh contributors if someone wants to see a contributor in detail its not possible for them as it is running continuously and becoming difficult even read their name.

**Describe the solution you'd like**
 so I want to enhance the feature by making them hold or stop while hovering or moving cursor over them.

**Describe alternatives you've considered**
I want to make a css class to make them hold while hovering a cursor on them. It will make it easy for users to read them better

## Additional Information

**Context**
@ankitjt I am a GSSOC'24 contributor please assign this to me

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

https://github.com/akshitagupta15june/Moksh/assets/116761608/567724df-370a-468f-b007-c0e67668ffce

**Priority** (optional)
Priority medium

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
its a feature by vaunt so currently no changes required.
