### ISSUE TITLE
Dropdown of search bar going behind the book tickets

### ISSUE THREAD

**Issue by anwesha2002** [akshitagupta15june/Moksh#1549]
## Description

**Describe the bug:**
The dropdown while entering any input in the search bar of upcoming event section, it is going behind the tickets . Which is making it difficult to read the places where the event is happening

**Expected behavior:**
The dropdown should be visible and clear on the tickets so that user can see all the event places clearly

**Actual behavior:**
 it is going behind the tickets making it difficult for users to read them clearly

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to "https://akshitagupta15june.github.io/Moksh/index.html" this link
2. Hover the mouse over 'features' on the navbar
3. on the dropdown click on "iskcon events". Scroll down to the upcoming events search bar . Enter any letter (ex : B)
4. See error "https://akshitagupta15june.github.io/Moksh/Iskcon/event.html"

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![Screenshot 2024-05-16 145818](https://github.com/akshitagupta15june/Moksh/assets/116761608/f18d15c2-32fa-4516-9346-1c03ae2db954)

## Additional Information

**Device (please complete the following information):**
- OS: Windows
- Browser : Chrome
- Version latest

**Additional context:**

@ankitjt I am a GSSOC'24 contributor please assign this to me

**Comment by akshitagupta15june** [comment]
go for it!
