### ISSUE TITLE
 feature enhancement : Saving Blogs in  a section to show them later under the power of knowledge blog section

### ISSUE THREAD

**Issue by anwesha2002** [akshitagupta15june/Moksh#1550]
## Description

**Is your feature request related to a problem? Please describe.**
While clicking on  the save icon of the blogs it is not saving the blog and even the icon color is not changing after saving it

**Describe the solution you'd like**
I would like to save the blog on clicking the save icons, in a different section where users can go to see all the blogs they saved and can read them there as well

**Describe alternatives you've considered**

## Additional Information

**Context**
For making this unders the POWER OF KNOWLEDGE BLOGS section i want to make another button or link named "save blogs" where users can go and see those and read as well
**Potential Implementation** (optional)
I can save the blogs in an array in localstorage and serve them form there

**Screenshots or Mockups** (optional)
![Screenshot 2024-05-16 150613](https://github.com/akshitagupta15june/Moksh/assets/116761608/a256a3c8-d3db-43fd-ad2a-4f440dd4b295)

**Priority** (optional)
high

**Additional Notes** (optional)
@ankitjt I am a GSSOC'24 contributor please assign this to me

**Comment by akshitagupta15june** [comment]
hey print feature does same work here, so no changes required currently.
