### ISSUE TITLE
[BUG] Menu is not working properly in responsive mode

### ISSUE THREAD

**Issue by Bittukr7479** [akshitagupta15june/Moksh#1552]
When the website is in responsive mode, the navigation bar doesn't work correctly. After clicking the menu icon, the menu items don't appear. However, after scrolling up, the menu items become visible, as shown in the video.

https://github.com/akshitagupta15june/Moksh/assets/123286618/26160e78-580d-4fac-bc57-6b1c4760b6c0

**Comment by akshitagupta15june** [comment]
go for it!
