### ISSUE TITLE
[STYLE CHANGE] Correcting the gaps and centering the Read in the button

### ISSUE THREAD

**Issue by Unalia09** [akshitagupta15june/Moksh#1553]
![image](https://github.com/akshitagupta15june/Moksh/assets/147930477/aa5a30c0-174c-4bb0-a096-8aa8a4fa5d41)

There is too huge of a gap between depression and suicide which makes it look uncomfortable also the "read" isn't centered.
I would like to change that and also change the other "read" which haven't been centered well.

Priority Level (optional):

- [X] Low
- [ ] Medium
- [ ] High

**Comment by Unalia09** [comment]
I would like to be assigned this under gssoc24

**Comment by akshitagupta15june** [comment]
go for it!
