### ISSUE TITLE
Issue/Suggestion Mouse wheel indicator at the header is also be seeing in the mobile view .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [akshitagupta15june/Moksh#1555]
**Issue and Steps to Reproduce:**

1. Go to the website
2. Open it in mobile
3. You can see mouse indication is also coming in mobile but we dont use mouse except this we can use any other symbol like arrow for mobile users. 
4. 
**Screenshots:**
![Screenshot 2024-05-17 141819](https://github.com/akshitagupta15june/Moksh/assets/118350936/8ec15ce8-f9a0-461c-869e-0e1f659f91fd)

**Expected:**
Some other indicator like arrow or scroll will be shown .

**Actual:**
Mouse indicator can be seen .

**Comment by akshitagupta15june** [comment]
go for it!
