### ISSUE TITLE
[STYLE CHANGE]  The text in the header section wants to be shifted towards right .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [akshitagupta15june/Moksh#1556]
**Description:**

Their is a very less gap between the image and the text and the right most part of the header is looking very empty .

**Reason for Change:**

It may increase the UI of the website .

**Current Styling:**

Their is very less gap between the image and the text of the header section .
**Proposed Styling:**

A proper gap will be given between the image and the text .

**Screenshots or Design Mockups (optional):**

Design overview -;  
![Screenshot 2024-05-17 142515](https://github.com/akshitagupta15june/Moksh/assets/118350936/43668e86-30c2-412a-b665-966dc1a74c4a)

**Additional Information (optional):**

**Priority Level (optional):**

- [ ] Low
- [  x ] Medium
- [ ] High

**Timeline (optional):**

less than 1hr .

**Possible Implementation Approach (optional):**

By giving more margin or gap .

**Comment by akshitagupta15june** [comment]
hey! some contributor is already working on this issue
