### ISSUE TITLE
Simplification in Logo of Moksh and Blog button colour change

### ISSUE THREAD

**Issue by 3simransharma** [akshitagupta15june/Moksh#1559]
**Description:**

-Simplification of Moksh logo and change of blog button colour.

**Reason for Change:**

I'm a professional graphic designer, and I saw the current logo, I felt that it should be more simple, so I have simplified the logo and have created that logo in different ways to use in different situations(saved in Images/LOGO directory in svg format).

**Current Styling:**

![image](https://github.com/akshitagupta15june/Moksh/assets/95140559/ada1f8d8-c4d3-4a29-b6e7-ffaac89bf8b0)
![image](https://github.com/akshitagupta15june/Moksh/assets/95140559/e7a9a8e9-5caf-449b-b27b-7cb481cb7303)

![image](https://github.com/akshitagupta15june/Moksh/assets/95140559/f10fea66-bf31-4be0-a047-4a79258114ba)

**Proposed Styling:**

the logo will look like this on website: 

![msedge_UEjubLCM67](https://github.com/akshitagupta15june/Moksh/assets/95140559/b34bfe35-085f-498c-9c6d-96705c9f9543)

![msedge_1sszLX3RFc](https://github.com/akshitagupta15june/Moksh/assets/95140559/8fbd62f0-c7fb-4584-a5ae-23d9843f0c5c)

currently I have changed logo in home page only just to show you, if you like this logo, then I'll implement this logo in all over the website.

Also, I have also changed the colour of a button in the blogs page.

![image](https://github.com/akshitagupta15june/Moksh/assets/95140559/2792d07d-b0fb-4b5f-9a5b-247f2f1fc78e)

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Comment by 3simransharma** [comment]
If you don't mind, please assign me this issue under gssoc'24

**Comment by akshitagupta15june** [comment]
hey some contributor is already working on this
