### ISSUE TITLE
Add blog section link to the navbar on all the pages

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#156]
All the pages have links to other pages except for the link to the newly created blog section

**Comment by karthiknadar1204** [comment]
@akshitagupta15june can i work on this issue,please assign this issue to me

**Comment by manasi-jain** [comment]
Hi  @karthiknadar1204, I'm interested in working on this issue. Can I contribute to its resolution?

**Comment by karthiknadar1204** [comment]
Honestly I am waiting for it to be assigned to me

**Comment by akshitagupta15june** [comment]
@karthiknadar1204 assigning u
