### ISSUE TITLE
[FEATURE REQUEST] IMPORTANT FEATURES FOR  INSTRUMENTAL MUSIC SECTION 

### ISSUE THREAD

**Issue by Championshi** [akshitagupta15june/Moksh#1563]
**IMPORTANT****
This section of features includes Adding a Music Section for the instrumental music  
****WHY THIS SECTION****
To Heal the Mind of individual through instrumental music  even there is article published that to improve mental peace and stability through instrumental music(like:- flute, vilone, kalbharivi e.t.c )   and many other music are beneficial according to the sympton of the person

**Is your feature request related to a problem? Please describe.**
yes it is related  to the problem of mental peace and stability   whic can be enhanced through instrumental music recommendation to the user 

**Describe the solution you'd like**
i would like to add  instrumental music section like the section of some features included earlier   in  this section of  instumental music there would be different instumental music section with their benefits mention in it as this data is published online for different ancient instumental music through this music section like bhagwat gita audio user can hear this music to heal his/her mind 

## Additional Information

**Context**
this section can we implemented same as the other section but the content of this section should be different 

**Potential Implementation** (optional)
this section can we implemented same as the other section but the content of this section should be different   like in this section 
 different types instrumental music option is available with their benefits  

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
high

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by akshitagupta15june** [comment]
its not required currently
