### ISSUE TITLE
[FEATURE REQUEST] Change the styling of the Power of knowledge Blogs page to match the Theme of the website

### ISSUE THREAD

**Issue by r7projects-shayan** [akshitagupta15june/Moksh#1565]
## Description

**Is your feature request related to a problem? Please describe.**

The color scheme of the Power of knowledge Blogs page doesn't match the main color schemes of the website. The buttons are having unnecessary gray gradient effect, while the color theme is different. 

**Describe the solution you'd like**
Match the color schemes of the Knowledge of Blogs page with the Moksh's main theme color

## Additional Information

**Context**

![Screenshot 2024-05-18 134017](https://github.com/akshitagupta15june/Moksh/assets/167475552/a3cffa24-426b-4721-b545-84952f52a2c0)
![Screenshot 2024-05-18 134708](https://github.com/akshitagupta15june/Moksh/assets/167475552/0d786a02-6b97-42b3-a881-a0d97f433984)

![Screenshot 2024-05-18 134446](https://github.com/akshitagupta15june/Moksh/assets/167475552/b2bfd6cd-ad7d-45ab-a6f6-80d8b5d0bf5b)

**Priority** (optional)
High

**Program**

Gssoc 24

**Comment by r7projects-shayan** [comment]
@akshitagupta15june Kindly assign this issue to me, I will fix it in a small amount of time and make the website look magical

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by r7projects-shayan** [comment]
Thanks @akshitagupta15june

**Comment by r7projects-shayan** [comment]
I will create another pull request without merge conflicts @akshitagupta15june

**Comment by r7projects-shayan** [comment]
@akshitagupta15june I have raised the new Pull request #1595 and it has no conflicts now.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by r7projects-shayan** [comment]
@Mahimatestgithub it's already done, please checkout for another issue

**Comment by r7projects-shayan** [comment]
@akshitagupta15june kindly merge the pr, I have resolved all the conflicts
