### ISSUE TITLE
[BUG] Navbar is getting hidden while Translating the page in Power of Knowledge Blogs page

### ISSUE THREAD

**Issue by r7projects-shayan** [akshitagupta15june/Moksh#1566]
## Description

**Describe the bug:**
Navbar is getting hidden while Translating the page in Power of Knowledge Blogs page whenever we are trying to translate the blog. This is happening because of Google Translate getting on top of Navbar and hiding it

**Expected behavior:**
Navbar should be visible even while translation is ongoing.

**Actual behavior:**
Navbar getting hidden.

## Reproduction Steps

**Steps to reproduce the behavior:**

 Fix the google translate bar appearing on top of navbar

**Expected result:**
Google translate bar appearing on somewhere in the side other than on  top of navbar

**Actual result:**
Google translate bar appearing on top of navbar

## Screenshots

![Screenshot 2024-05-18 134131](https://github.com/akshitagupta15june/Moksh/assets/167475552/507d1035-66c6-4df7-bb35-f5a785fe3500)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]

Windows
- Browser [e.g., Chrome, Safari, Firefox]

Chrome and Edge
- Version [e.g., 22]

**Additional context:**

**Priority**

High

**Program**

Gssoc 24

**Comment by r7projects-shayan** [comment]
@akshitagupta15june I love the concept of Moksh but this bug is standing as an obstacle between Moksh and the Bhakts. Kindly assign this issue to me so I can remove it as soon as possible.

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by r7projects-shayan** [comment]
Alright

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
