### ISSUE TITLE
Design About Us Page

### ISSUE THREAD

**Issue by Hemashree21** [akshitagupta15june/Moksh#1567]
I can add an about us page highlighting the features and mission of the website. 

@akshitagupta15june please assign this issue to me

**Comment by ichitrang** [comment]
I hope this message finds you well. My name is [Your Name], and I am a passionate developer with experience in web development and design. I am writing to express my interest in contributing to the "Shopnex" project, particularly by creating a comprehensive "About Us" page for the Shopnex website. To proceed, I kindly request access to the repository to begin working on this enhancement. I am open to feedback and keen on maintaining the project's coding standards and conventions.

**Comment by akshitagupta15june** [comment]
hey its already present in website.
