### ISSUE TITLE
Not show TimeLine of Quize Page.This Functionality have In your code But it not shows.

### ISSUE THREAD

**Issue by AnkitMourya12** [akshitagupta15june/Moksh#1568]
## Description

Describe the bug:-
In quize page when start the quize then it not shows timeline. Let understand by screenshot-
<img width="668" alt="quize5_timeOf" src="https://github.com/akshitagupta15june/Moksh/assets/121748364/d20364ed-5c10-4871-8d66-456c47b2130d">

example of other website ss:-
<img width="924" alt="quize4_time" src="https://github.com/akshitagupta15june/Moksh/assets/121748364/125aa533-2bb5-4c30-b51d-5277a3983b5a">

 In your given code have this functionality but just fix the code then after it work same as other website.

**Comment by AnkitMourya12** [comment]
@akshitagupta15june can you assign this task to fix the bug. and kindly assign the under gssoc24 and labels

**Comment by akshitagupta15june** [comment]
Go for it!
