### ISSUE TITLE
[FEATURE REQUEST] Responsiveness should be added on  ISKCON Events page

### ISSUE THREAD

**Issue by Noopur-Thombare** [akshitagupta15june/Moksh#1569]
Description
Is your feature request related to a problem? Please describe.
Responsiveness should be added on Events page cards are overlapping with footer and it should be mobile compatible 

Describe the solution you'd like
I will try to use CSS HTML for solving this problem

Additional Information
also I can add hover effect on Srila Prabhupada image and I can also solve the overlapping cards problem on hovering 

Screenshots
![Screenshot 2024-05-18 202827](https://github.com/akshitagupta15june/Moksh/assets/144435206/83bb99ac-8913-4126-b24f-f470ebb785a6)

![Screenshot 2024-05-18 202857](https://github.com/akshitagupta15june/Moksh/assets/144435206/4606837c-e428-4a2e-a057-66b0a835ebf5)

![Screenshot 2024-05-18 202942](https://github.com/akshitagupta15june/Moksh/assets/144435206/abb2668d-f856-4074-b81b-f5e81edcc1fc)

**Comment by Noopur-Thombare** [comment]
@akshitagupta15june please assign this task to me and kindly assign the under gssoc24 and labels

**Comment by akshitagupta15june** [comment]
Go for it!
