### ISSUE TITLE
Streamlining components 

### ISSUE THREAD

**Issue by ankitjt** [akshitagupta15june/Moksh#158]
The project has some components that are used on all pages like navbar and footer. For making any change in any of these components we would have to apply the change on each page and any it would be hard to keep track what changes are made as multiple people are working on different/same pages.

Instead of updating pages individually, we can inject them on each page with a script (e.g. commonComponents.js) which can be added on each page. So what ever changes are to be made can be made in the commonComponents.js which will reflect all across.

Suggestion to create two files-
1. commonComponents.js
2. commonStyles.css 

Components that can be added in the commonComponents.js -
1. Navbar
2. Footer

Likewise any common styles ( background-color, link and button styles etc.) and styles for navbar & footer can also be added in commonStyles.css.

We can use [Montserrat](https://fonts.google.com/specimen/Montserrat?query=montserrat) font family. It has a load time of 39ms.

This is just an opinion, please share your feedback and suggestions.

**Comment by akshitagupta15june** [comment]
I would like to invite @karthiknadar1204 @swapnilgarg7 @mnik7044 @harmeetsingh11 to discuss on this issue and bring a solution

**Comment by karthiknadar1204** [comment]
Thank you @akshitagupta15june 
@ankitjt I think this might involve migrating the project to react, does that sound right, like under components we will be having components like navbar and footer and since all the pages have a uniform styling for both navbar and footer,we can make it all work with just one style sheet and do not have to use the elements of the navbar and footer repeatedly on all the pages.

@ankitjt is this what you meant ?

**Comment by ankitjt** [comment]
No, what I am proposing can be achieved with vanilla JS too.  

So to break it down with regards to code, it'll go something like this-

Say we have an element in our html -
`<div class='container customNavbar'></div>`

In commonScript.js

```
const customNavbar = document.querySelector( ".customNavbar" );

// We can run a self executing function which runs as soon as the page loads.
(() => {

// This way we only have to update any markup here only making scaling (if needed ) or changes easy.
let navbarContent = `Here add all the markup for navbar`

customNavbar.innerHTML = navbarContent

} )()
```

Yes, for styling we can use a single sheet for common components as well as for common elements (link, button), though I reckon it'll be less for elements as Bootstrap would take care of most of the styling part from the get go.

It'll be more uniform and easier to make any styling changes for future.

**Comment by akshitagupta15june** [comment]
also I want to keep this project for beginners so i won't be shifting this project to reactjs

**Comment by ankitjt** [comment]
@akshitagupta15june I am not suggesting moving to reactjs either.

**Comment by karthiknadar1204** [comment]
@ankitjt Sounds good!

**Comment by karthiknadar1204** [comment]
@ankitjt Sounds good!

**Comment by ankitjt** [comment]
Thanks, so how do we proceed ahead?

**Comment by akshitagupta15june** [comment]
you can start by taking a meditation page which u improved

**Comment by harmeetsingh11** [comment]
Thanks @akshitagupta15june for mentioning.
Another possible solution is that we can use `jQuery `to achieve this. Here's explanation-

- Create `navbar.html`, `footer.html` and `styles.css` (contains all the styling related to navbar and footer).
- Lets say we want to use created navbar and footer in `index.html` page.
- In `index.html`, firstly we add jQuery from CDN in the `Head` section.
- The `body` section is as follows-
```
<body>
    <!-- Navbar starts -->
    <div id="navbar"></div>
    <!-- navbar ends -->

    <!-- main content -->

    <!-- footer start -->
    <div id="footer"></div>
    <!-- footer end -->

    <!-- script to load navbar.html file -->
    <script>
      $(function () {
        $('#navbar').load('navbar.html');
      });
    </script>

    <!-- script to load footer.html file -->
    <script>
      $(function () {
        $('#footer').load('footer.html');
      });
    </script>
  </body>

```
