### ISSUE TITLE
no navbar and whitish window in augmented reality meditation

### ISSUE THREAD

**Issue by Devansh1508** [akshitagupta15june/Moksh#1586]
## Issue
- In the augmented reality meditation section there is no navbar.
- There is a whitish border near the window which becomes a box when size of window is more than 768px.
- menu button of story page does not works.

## issue 1
<img width="833" alt="moksh 1" src="https://github.com/akshitagupta15june/Moksh/assets/160311808/6341bce3-a4b0-4ded-9e23-f46d88e58966">

## issue 2
<img width="578" alt="moksh 2" src="https://github.com/akshitagupta15june/Moksh/assets/160311808/9316b45b-f64e-41be-be6c-f02e379b2d82">

## issue 3
<img width="485" alt="moksh 3" src="https://github.com/akshitagupta15june/Moksh/assets/160311808/c85a95a5-accb-48b4-bc16-62e06ec32a1c">

## proposed solution

- for issue 1
In the current project code, a container has been designated for the navigation bar. However, it appears that no links, text, or logo have been integrated into it. Consequently, the navigation bar is non-functional. 

- for issue 2 and issue 3
The issue can be resolved by making some adjustments in CSS, html and javascript.

## Expected Outcome
Implementing the proposed solution will result in a more a user-friendly page section. It will become easy for a user to move from one section of the website to the other.

## Additional Details

- I will ensure that the proposed solution is compatible with different screen sizes and devices.
- This enhancement may require adjustments to the existing CSS and HTML code.

Kindly assign this issue to me under GSSoC 24.

**Comment by akshitagupta15june** [comment]
Go for it
