### ISSUE TITLE
Improve the rejuvenate section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#16]
how can we make this section more attractive? https://akshitagupta15june.github.io/Moksh/rejuvenate.html

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,i would like to work on this issue,please assign it to me

**Comment by karthiknadar1204** [comment]
I can add some real engaging effects that can enhance the user experience for this issue

**Comment by akshitagupta15june** [comment]
ok

**Comment by karthiknadar1204** [comment]
Starting work on this issue from tomorrow
Thank you

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,i have adjusted the lower part of the rejuvenate page,working on the links,will submit pr for review by 10:30

**Comment by karthiknadar1204** [comment]
@akshitagupta15june i have added a few styles but cant think of anyhing good for the video links so havent changed anything with the links,tried implementing a slider but it wasnt looking appealing.
please review my pr
Thank you
ps:will attach the ss of the changes applied
