### ISSUE TITLE
[FEATURE REQUEST]  Add a contact us page

### ISSUE THREAD

**Issue by Bhavishya2601** [akshitagupta15june/Moksh#1611]
I want to add a contact us page which is a necessary for every website,
something like this 

![Screenshot 2024-05-22 133655](https://github.com/akshitagupta15june/Moksh/assets/147748752/c01917d2-03f7-40cc-9342-08a35efbec4b)

Hope you would assign this task to me

**Comment by Ansh101112** [comment]
@itsmohit097 sir please assign me this issue
