### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by rahulkhandait-sde** [akshitagupta15june/Moksh#1613]
**Issue:** The Twitter widget on the Moksh website is not displaying correctly.

**Expected:**
![msedge_4KuXEogrTb](https://github.com/akshitagupta15june/Moksh/assets/90828823/135a069d-0a2e-4397-b1a5-c06ea862fec5)

**Actual:**
![msedge_kO9db7Uw6f](https://github.com/akshitagupta15june/Moksh/assets/90828823/db540b5a-d44a-4bde-99ba-9df3fb418be9)

**Comment by rahulkhandait-sde** [comment]
@akshitagupta15june ma'am please assign me this issue under GSSOC'24 and also label it

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by rahulkhandait-sde** [comment]
@akshitagupta15june Ma'am please add label 1 under GSSOC'24
