### ISSUE TITLE
Fix the Footer of Blogs page

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [akshitagupta15june/Moksh#162]
The footer is covering Half of the page and overlaps with the content.
<img width="946" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/70560812/fe84fd60-375c-4470-8632-db2643b3b595">

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! "

**Comment by ankitxcoding** [comment]
yes why not but there are no response from the admin on this, if we made changes on this and request a pr then there is possibility that admin will not merge the pr.

**Comment by akshitagupta15june** [comment]
its completed
