### ISSUE TITLE
QR Code for AR Meditation ID Validation Bug:

### ISSUE THREAD

**Issue by techy4shri** [akshitagupta15june/Moksh#1632]
## Description 

**Describe the bug:**
The QR Code which is supposed to be facilitate AR Meditation doesn't work, instead, it shows ID validation error- both in android and windows devices.

**Expected behavior:**
The QR is supposed to overlay calming and focus-inducing visuals onto your physical environment. This could either be a result of incorrect data encoding or QR code reader error. The later is highly unlikely considering I tried the QR with 3 devices and all of them showed the ERROR page.

**Actual behavior:** the link does not return any valid request or open up the AR webpage it is supposed to.

**Expected result:**
The link should direct the user to an AR meditation webpage and ask for required permission before displaying the calming visuals and media; for example: serene landscapes, geometric patterns that change and flow or a clear focal point for your attention, helping you stay present in the moment. 

**Actual result:**
The webpage which opens, shows _**Error: Invalid Entry ID**_

## Screenshots
![Moksh QR Error](https://github.com/akshitagupta15june/Moksh/assets/141991095/235fa533-feca-4bff-8545-c2edf4a219b2)
![Moksh QR Error ](https://github.com/akshitagupta15june/Moksh/assets/141991095/7b5f2b14-8c8a-49f3-a003-431511b1896a)
<img width="960" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/141991095/d8d18d4e-f849-422b-b927-467ac30c5ac8">

## Additional Information 

**Device:**
- OS: Android 11, Android 13, Windows 11
- Browser: Chrome
- Version:  Google Chrome 125.0.6422.113, Google Chrome 125.0.6422.72 , Google Chrome 125.0.6422.112 (Official Build) (64-bit),

Kindly assign me this issue @akshitagupta15june Ma'am  under GSSoC'24 so that I can work on it.

**Comment by akshitagupta15june** [comment]
it requires a paid version, i will look into it
