### ISSUE TITLE
non responsive

### ISSUE THREAD

**Issue by Prashant-2505** [akshitagupta15june/Moksh#164]
website's navbar and other section is non - responsive according to device 

![Screenshot (37)](https://github.com/akshitagupta15june/Moksh/assets/102030344/6429bf9e-bb76-4b47-aaac-63bca1d353ad)

i can fix that issue 

assign this issue to me   (contributor in Gssoc ' 23)

**Comment by Prashant-2505** [comment]
![Screenshot (45)](https://github.com/akshitagupta15june/Moksh/assets/102030344/c6f948f2-a217-4569-b1a6-de40bd06af09)

**Comment by ankitjt** [comment]
do a new fetch, the homepage is responsive now.
