### ISSUE TITLE
Improve the UI cards 

### ISSUE THREAD

**Issue by 007aneesh** [akshitagupta15june/Moksh#165]
Adding the animation and UI of the featured cards because these are not eye catching ![Screenshot_2023-05-20-00-14-25-116-edit_com.android.chrome.jpg](https://github.com/akshitagupta15june/Moksh/assets/90706436/01d45bb9-bb87-44fe-8131-7d66e0d643ea)

**Comment by akshitagupta15june** [comment]
ok @007aneesh
