### ISSUE TITLE
[FEATURE REQUEST] Adding icons to navbar

### ISSUE THREAD

**Issue by harinisayani** [akshitagupta15june/Moksh#1650]
## Description

**Is your feature request related to a problem? Please describe.**
I observed this webpage is not having icons to the anchor tags.

**Describe the solution you'd like**
I want to add icons to navbar to make look attractive.

## Additional Information

**Additional Notes** (optional)
I am SSOC'24 contributor.
Please assign me this issue.

**Comment by gaurimadan** [comment]
Hi, I am a contributor in SSOC'24. I would like to work on this issue. Kindly assign me this.

**Comment by akshitagupta15june** [comment]
not currently needed
