### ISSUE TITLE
[FEATURE REQUEST] Adding more social media icons

### ISSUE THREAD

**Issue by harikasayani** [akshitagupta15june/Moksh#1651]
## Description

**Is your feature request related to a problem? Please describe.**
I want add more social media icons

## Additional Information

**Additional Notes** (optional)
I am SSOC'24 Contributor.
Please assign me this task.
I want to work on this issue.

**Comment by jayanththalla** [comment]
please assign me @pa

**Comment by gaurimadan** [comment]
HI, I am a contributor in SSoC, I would like to contribute to this issue, kindly assign me .

**Comment by piyushsahujtp** [comment]
I want to change twitter with X and adding more social media accounts like facebook and instagram.

**Comment by akshitagupta15june** [comment]
currently not needed
