### ISSUE TITLE
[BUG]  Add Button for move contributors card

### ISSUE THREAD

**Issue by dhruv8433** [akshitagupta15june/Moksh#1652]
## Description
@akshitagupta15june 

**Describe the bug:**
we can add left and right button in this contributions list

**Expected behavior:**
- we can add left and right button too

**Actual behavior:**
A clear and concise description of what actually happened.
- currently they move autometically

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'home page'

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/114583978/fcb149dc-0aa6-4e15-b393-c85e0c0a97c5)

**Additional context:**

**Comment by akshitagupta15june** [comment]
not currently needed
