### ISSUE TITLE
[BUG]  Add slug for better user experience

### ISSUE THREAD

**Issue by dhruv8433** [akshitagupta15june/Moksh#1653]
## Description
@akshitagupta15june 

**Describe the bug:**
- we can update url format and add slugs for better user experience

**Expected behavior:**
- require slugs

**Actual behavior:**
A clear and concise description of what actually happened.
- there is no slug in url

## Reproduction Steps

**Steps to reproduce the behavior:**
- we can add slug

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/114583978/9d7b0503-7ecd-4ca2-a53f-5f52533472fc)

**Comment by akshitagupta15june** [comment]
its not currently needed in website
