### ISSUE TITLE
[FEATURE REQUEST]  Want to add dark/light toggle button

### ISSUE THREAD

**Issue by Aditijainnn** [akshitagupta15june/Moksh#1654]
By adding this light/dark mode option the website look more good

**Comment by Mallik0** [comment]
Adding a toggle button to switch between light and dark theme is indeed a great UI, and it greatly helps the user experience therefore kindly assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
not needed in this website
