### ISSUE TITLE
Sections overlapping navigation bar issue

### ISSUE THREAD

**Issue by yuvraj-singh009** [akshitagupta15june/Moksh#1659]
![Screenshot 2024-06-01 233113](https://github.com/akshitagupta15june/Moksh/assets/149161662/961ff6ad-9148-40e2-aa8d-7dfdc9a57c7c)
![Screenshot 2024-06-01 233100](https://github.com/akshitagupta15june/Moksh/assets/149161662/4baed6af-b92d-414f-a4f8-8578484d6fe5)
![Screenshot 2024-06-01 233048](https://github.com/akshitagupta15june/Moksh/assets/149161662/2f6389cf-9905-4daa-8747-46790141c77b)

In the website we have seen some issues regarding navigation bar visibility. the navigation bar hides under various section of website. you can see the issue in the screenshot i have attached
I can fix the issue if assigned to me. within 1-2days

**Comment by gdhyani** [comment]
I can start working on this, as a part of gsoc.
