### ISSUE TITLE
Make navbar responsive

### ISSUE THREAD

**Issue by 007aneesh** [akshitagupta15june/Moksh#166]
Navbar is not responsive at all so make it responsive
 ![Screenshot_2023-05-20-00-16-40-093_com.android.chrome.jpg](https://github.com/akshitagupta15june/Moksh/assets/90706436/4326c08c-7030-49af-a13d-257c7647d28c)

**Comment by mad-alpha** [comment]
Can you please assign this issue to me ? @007aneesh

**Comment by raghavawasthi24** [comment]
I can make make navbar full responsive for all devices. Can you please assign this issue to me?

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by 007aneesh** [comment]
@akshitagupta15june I want to know if someone else is working on the navbar or not because I want to work on it so assign it to me!

**Comment by ankitjt** [comment]
Have you checked the navbar on the blog page? 

Please provide on what page the navbar is not responsive, share relevant screenshots.

**Comment by 007aneesh** [comment]
@ankitjt check the screenshot attached to this issue!

**Comment by akshitagupta15june** [comment]
I have assigned to someone else
