### ISSUE TITLE
[BUG] [CSS] Navbar is conflicting the overlapping with cards

### ISSUE THREAD

**Issue by nik-rawat** [akshitagupta15june/Moksh#1663]
## Description

**Describe the bug:**
The navbar of the landing page is having a bug regarding its position.

**Expected behavior:**
The navbar should be on top of the z-index the whole page should go under the navbar layer.

**Actual behavior:**
The navbar of the landing page is overlapping with the cards in features.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'index.html'
2. Scroll down to 'FEATURES' section
3. Scroll through the cards
4. See the bug at navbar

**Expected result:**
The position of navbar should be at its correct z-index.

**Actual result:**
While scrolling through the cards in 'FEATURES' section the navbar should not go under the card details.

## Screenshots

![ssoc moksh](https://github.com/akshitagupta15june/Moksh/assets/121238130/e5be13c5-0652-4f96-8029-ced5f1ca4a29)

I want to resolve this issue. Please assign this issue under SSOC for me to resolve.
Record:
I agree to follow this project's Code of Conduct
I'm a SSOC'24 contributor
I want to work on this issue.

**Comment by nik-rawat** [comment]
I want to resolve this issue. Please assign this issue under SSOC for me to resolve.

**Comment by Diwakar-Mishra** [comment]
Sir, I am a GSSOC'24 contributor and I want to resolve the above issue with the help of CSS Positioning, z-idnex and other CSS properties So, can you please assign this task to me .

**Comment by Mallik0** [comment]
Hi there!
I feel there is something wrong with the z index and will need to check the position as well, so kkindly assign this bug to me, I'm a ssoc'24 contributor

**Comment by akshitagupta15june** [comment]
someone is working on it!
