### ISSUE TITLE
[BUG] Menu icon not functional in argumented reality page in small screen.

### ISSUE THREAD

**Issue by dushyant2901** [akshitagupta15june/Moksh#1667]
Description
Describe the bug:
When you go to argumented reality page and try to open menu/navbar in small screen device by clicking on menu icon it's not responding.

Expected behavior:
On small screen devices Menu icon should respond to the user's click to open the menu so that user can navigate to options available in it.

Actual behavior:
No response to the click event on the menu icon in small screen device.

Reproduction Steps

Go to 'Argumented reality page'
Click on 'menu icon'.

**Comment by dushyant2901** [comment]
Kindly assign this issue to me.
#ssoc

**Comment by akshitagupta15june** [comment]
Go for it!
