### ISSUE TITLE
[BUG] Buttons(Share, Save and Print) in karma page not working

### ISSUE THREAD

**Issue by nik-rawat** [akshitagupta15june/Moksh#1670]
## Description
The  share, save, and print buttons are not responsive in the karma.html page

**Describe the bug:**
The buttons in karma page are not doing anything.

**Expected behaviour:**
share button should copy the page URL, save button should download it, and print button will open print pop up.

**Actual behaviour:**
These buttons are not responsive.

## Reproduction Steps

**Steps to reproduce the behaviour:**

1. Go to 'navigation bar'.
2. Click on 'POWER OF KNOWLEDGE BLOGS'.
3. Click on 'READ MORE'.
4. Try to click on share, save and print buttons.
5. See the error.

**Expected result:**
These buttons should convey their functions.

**Actual result:**
There is no function call for these buttons.
## Screenshots

![moksh-karma](https://github.com/akshitagupta15june/Moksh/assets/121238130/a9e0abbe-040d-4c5d-9592-2953e3899708)

**Comment by nik-rawat** [comment]
Kindly assign this issue to me.
#SSOC

**Comment by akshitagupta15june** [comment]
Go for it!
