### ISSUE TITLE
[STYLE CHANGE] Fixing Css of Blog Page in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [akshitagupta15june/Moksh#1673]
**Description:**

![image](https://github.com/akshitagupta15june/Moksh/assets/142989448/3f43cc32-0fce-4e93-97e0-e3bff3d0b389)

i can change this mobile view of blog page decreasing the unnecessary gap

**Reason for Change:**

it will make website look beautiful in mobile view and increases user experience 

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

![image](https://github.com/akshitagupta15june/Moksh/assets/142989448/2e5b9988-6c08-4e6f-9e94-d4c311f4d866)

**Priority Level (optional):**

- [x] Medium

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by dhairyagothi** [comment]
> Go for it!

Please assign with label gssoc
