### ISSUE TITLE
[BUG] Footer links not visible in argumented reality page

### ISSUE THREAD

**Issue by dushyant2901** [akshitagupta15june/Moksh#1675]
## Description

**Describe the bug:**
Footer links in argumented reality page are not visible. As the text color of the footer links is similar to the background it leads to readability issue.

**Expected behavior:**
Footer links should be visible to the user so that one can navigate to different options available in links.

**Actual behavior:**
Readability issue as the text color of the links is similar to the background.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'index.html'
2. Click on 'click on argumented reality meditation option from navbar'
3. Scroll down to 'footer section'

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![Screenshot_2024-06-05-15-50-33-97_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/akshitagupta15june/Moksh/assets/74450982/3240667b-4474-477d-a5d0-c62960efbddd)

**Comment by dushyant2901** [comment]
Kindly assign me this issue.
#ssoc

**Comment by akshitagupta15june** [comment]
Go for it!
