### ISSUE TITLE
[STYLE CHANGE] Overlapping of upcoming iskcon event search menu with navbar and no hover effect 

### ISSUE THREAD

**Issue by supratimbanik** [akshitagupta15june/Moksh#1677]
**Description:**
Hello! I am an SSOC'24 contributor. 
I want to resolve the styling issues of the upcoming events search bar in the isckon events page.

https://github.com/akshitagupta15june/Moksh/assets/118803109/2faf59ab-69c1-48aa-a2e3-c41320644e3a

![image](https://github.com/akshitagupta15june/Moksh/assets/118803109/62830854-9cae-424b-89d9-9c1fade10b62)

**Reason for Change:**
Search menu of the search bar overlaps with the navbar on scrolling. Also the search menu has no hover animation. On clicking the search menu option the search field value is not changed. This hampers the UI experience.

**Current Styling:**
Currently the search elements are only added after text is added to the search field.
There is no hover animation for the search menu.
Also the z-index is also not properly handled.

**Proposed Styling:**
I will add some event listeners for hover and click actions.
I will also properly set the z-index of the search menu.

**Screenshots or Design Mockups**

![image](https://github.com/akshitagupta15june/Moksh/assets/118803109/8bd6c682-7878-4c8c-952f-6c3e37fa9667)

https://github.com/akshitagupta15june/Moksh/assets/118803109/112e4a99-8392-49a7-8469-bb105498f68b

**Comment by akshitagupta15june** [comment]
Go for it!
