### ISSUE TITLE
[BUG] : Inconsistent Navbar Design across pages

### ISSUE THREAD

**Issue by Vibhu315** [akshitagupta15june/Moksh#1678]
NavBar of home page has 'Mental Health Problems' Button but when we click on 'Power of Knowledge Blogs' the Navbar doesnot contain 'Mental Health Problems' Button

![Screenshot 2024-06-06 000458](https://github.com/akshitagupta15june/Moksh/assets/93249125/42ffeffa-3def-455d-9508-63c90e59161a)

![Screenshot (201)](https://github.com/akshitagupta15june/Moksh/assets/93249125/15b112e4-f183-49bf-9034-b31b84bf0cc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

hey @akshitagupta15june  , I can fix this issue , please assign me this issue

**Comment by akshitagupta15june** [comment]
someone is working on it
