### ISSUE TITLE
changes in footer section

### ISSUE THREAD

**Issue by sandeep0009** [akshitagupta15june/Moksh#168]
i want to make some ui changes in footer please asign me this task and will do it as soon as possible

**Comment by Aditi323** [comment]
I would like to work on this issue as a GSSOC contributor.

**Comment by ankitjt** [comment]
Please share what's the issue in the footer section

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! "

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I have gone through the code and think I can make necessary changes to solve this issue.

**Comment by tusharma08** [comment]
Hey 👋 I am Tushar, I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I have gone through the code and think I can make necessary changes to solve this issue.

**Comment by sandeep0009** [comment]
> Please share what's the issue in the footer section


<img width="940" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/63727946/45dad628-140d-46f6-8e84-4ddd7c5e19d3">
the error which i found are hovering over the title it is not cursor pointer and also we can optimise the space and can make the copyright and all of footer section under center and align them colum vise which will give much better look .this are the changes what im talking about

**Comment by Pragati-3003** [comment]
Hey @akshitagupta15june 
I would like to work on this issue.
Please assign this issue to me under GSSOC'23.
Thanks.

**Comment by akshitagupta15june** [comment]
its not needed
