### ISSUE TITLE
Blog section is completely non responsive

### ISSUE THREAD

**Issue by raghavawasthi24** [akshitagupta15june/Moksh#171]
![Screenshot (98)](https://github.com/akshitagupta15june/Moksh/assets/113261155/a1a48352-f386-4da0-8764-a08dc034ead1)

I can fix this issue and wish that you assign this missue to me.

**Comment by Anushka20365** [comment]
Hello @akshitagupta15june ma'am ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.
Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by akshitagupta15june** [comment]
ok @raghavawasthi24 assigning u

**Comment by raghavawasthi24** [comment]
Thanks for the opportunity. I will try my best to make it correct.

**Comment by riyaVerma1726** [comment]
hello @akshitagupta15june . kindly assign me this issue. I have previously don work on making responsive websites
