### ISSUE TITLE
[FEATURE REQUEST] : Adding a testimonials section.

### ISSUE THREAD

**Issue by nagalakshmi08** [akshitagupta15june/Moksh#1713]
## Description

**Is your feature request related to a problem? Please describe.**
Many users always wanted to know about any website before using it.

**Describe the solution you'd like**
I would like to develop a testimonials section for this website which contains user reviews which shows about how good the website is.
**Describe alternatives you've considered**
There may be other alternatives like searching in google and all , but testimonials are effective way of knowing about a website,

## Additional Information

**Context**
![Screenshot 2024-06-07 203400](https://github.com/akshitagupta15june/Moksh/assets/121669832/a84411e0-e5ac-4bd1-941c-93053df58339)

This is one of my previous work on testimonials section of a website. 

**Priority**
High

**Additional Notes** (optional)
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

**Comment by akshitagupta15june** [comment]
not required in this website
