### ISSUE TITLE
[BUG] Issue in opening bhagwad Geeta quiz page and adding some more  quiz 

### ISSUE THREAD

**Issue by dhairyagothi** [akshitagupta15june/Moksh#1715]
## Description

**Describe the bug:**
Fixing bhagwad Geeta quiz page not opening and adding some more quiz

**Expected behavior:**
Problem in opening bhagwad Geeta quiz page stucked on the page and not opening 

**Actual behavior:**
Page should open properly 

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
Smooth opening of bhagwad Geeta quiz page 

**Actual result:**
Bhagwad Geeta quiz page not opening 

## Additional Information

**Device (please complete the following information):**
- OS: windows
- Browser chrome
- Version [e.g., 22]

**Additional context:**

Please assign me this under gssoc @akshitagupta15june

**Comment by dhairyagothi** [comment]
Please assign to me under gssoc @akshitagupta15june

**Comment by akshitagupta15june** [comment]
someone is working on it
