### ISSUE TITLE
Issue/Suggestion


### ISSUE THREAD

**Issue by dhairyagothi** [akshitagupta15june/Moksh#1716]
Decreasing font size and doing other changes to make this page look beautiful 

**Issue and Steps to Reproduce:**
Font size not looking good in mobile view 

**Screenshots:**
![Screenshot_20240611_200438.jpg](https://github.com/akshitagupta15june/Moksh/assets/142989448/e1d9cc20-b2fc-474f-b244-22e56248098d)

**Expected:**

Font size should decrease in mobile view so that it look good

**Actual:**
Font size is not looking good

**Additional Details:**
Please assign this issue to me under gssoc @akshitagupta15june

**Comment by dhairyagothi** [comment]
@akshitagupta15june please assign to me under gssoc

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by dhairyagothi** [comment]
Please merge the PR @akshitagupta15june
