### ISSUE TITLE
[STYLE CHANGE] : REVAMP THE FOOTER SECTION UNWANTED SPACE OF HOME PAGE AND THEME NOT WORK ON THE NAVBAR FEATURE SECTION 

### ISSUE THREAD

**Issue by AbhinaySngh** [akshitagupta15june/Moksh#1717]
![Screenshot 2024-06-11 225028](https://github.com/akshitagupta15june/Moksh/assets/162811933/6971d117-03ff-4404-99d4-ee880ac2cfc8)

**Comment by AbhinaySngh** [comment]
@akshitagupta15june Please assign me this issue under GSSOC'24 lebel.

**Comment by akshitagupta15june** [comment]
someone is working on it
