### ISSUE TITLE
[FEATURE REQUEST] : Add Login and SignUp Pages along with validation.

### ISSUE THREAD

**Issue by Vibhu315** [akshitagupta15june/Moksh#1719]
## Description
Hi @akshitagupta15june Mam,
We can add login and signup page along with validation for User Registration in the website.

## Screenshots

Various example of login and sign up pages.

![image](https://github.com/akshitagupta15june/Moksh/assets/93249125/52912f25-6666-4054-86e9-bde92a4dae31)
![image](https://github.com/akshitagupta15june/Moksh/assets/93249125/c261af1c-71bd-4d86-b296-8e01685ed4a1)
![image](https://github.com/akshitagupta15june/Moksh/assets/93249125/bdd3c705-7475-4239-a7d4-7ae42d199e61)

**Comment by Vibhu315** [comment]
Hey @akshitagupta15june ,
I can add this feature .please assign me this under GSSOC'24.

**Comment by akshitagupta15june** [comment]
not required in this website
