### ISSUE TITLE
[FEATURE REQUEST] Add a Dark Mode/Light Mode Theme Which Persist 

### ISSUE THREAD

**Issue by MastanSayyad** [akshitagupta15june/Moksh#1720]
Hey @akshitagupta15june  

I would like to add a Theme mode button which will be stored in browsers local storage so that it can persist across page refreshes

could you pls assign me this issue under gssoc?

**Comment by MastanSayyad** [comment]
@akshitagupta15june please take a look at this issue

**Comment by akshitagupta15june** [comment]
not required for this website
