### ISSUE TITLE
Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [akshitagupta15june/Moksh#1722]
## Description

**Is your feature request related to a problem? Please describe.**

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

**Describe the solution you'd like**

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

**Describe alternatives you've considered**

An alternative could be using a third-party service like Google Analytics for more detailed visitor statistics, but it does not provide a simple, on-page visitor count.

## Additional Information

**Context**
This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

**Potential Implementation**
One way to implement this feature could be by using a simple JavaScript snippet that updates the visitor count. This count could be retrieved and displayed in the footer.

**Additional Notes** 
**I request you to assign this issue to me under the gssoc label.**

**Comment by rohitinu6** [comment]
**@akshitagupta15june please assign this issue to me**

**Comment by akshitagupta15june** [comment]
not required in this website
