### ISSUE TITLE
I want tot change Moksh Logo on the header 

### ISSUE THREAD

**Issue by sheetal-81** [akshitagupta15june/Moksh#1723]
**Description:**

I wish to change the moksh logo which is on the header 

**Reason for Change:**

current one is also good , But i want to enhance the logo which looks more realistic to meditation as well as related to website 

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

iThe image which i wish to add i upload in this section 
![moksh](https://github.com/akshitagupta15june/Moksh/assets/134307985/6a8dfbca-e841-43e8-9488-6fdaa4c2e7c2)

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

only  1 day to implement this 

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by akshitagupta15june** [comment]
currently not required
