### ISSUE TITLE
Issue/Suggestion: Improving contributing.md file

### ISSUE THREAD

**Issue by kanishk-2** [akshitagupta15june/Moksh#1724]
<img width="234" alt="contri" src="https://github.com/akshitagupta15june/Moksh/assets/157130879/a6872ca0-32dd-42f8-9dc7-6d0966290056">

Issue is there are 2 files Contributing.md and Contributors.md .Having 2 files with same name will cause confusion .
so the content in contributors.md file should be added in contributing.md file and  contributors.md file should be deleted.
So there would be 1 file , avoiding confusion , and reduce the overall file size.

**Comment by akshitagupta15june** [comment]
contributors are the details about contributor and contributing is about the guidelines
