### ISSUE TITLE
The footer and the card division is overlapping in the "Connect with Iskcon Events" page

### ISSUE THREAD

**Issue by suhanigupta23** [akshitagupta15june/Moksh#1725]
The footer and the card division is overlapping in the "Connect with Iskcon Events" page

**Screenshots:**
<img width="1400" alt="Screenshot 2024-06-13 at 3 49 43 PM" src="https://github.com/akshitagupta15june/Moksh/assets/144280247/94a8dc76-fd9e-4240-831b-c80319e4b60d">

I want to work on this issue under GSSoc'24.

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by Akshit462005** [comment]
I kindly request to be assigned to this issue. As a Technical Executive at the IEEE CUIET Organization, I am well-positioned to address this matter. I am committed to delivering optimal results and have prior experience with similar projects, which I believe will enable me to make a meaningful contribution.

reference for prior work / projects :-|
https://www.linkedin.com/in/akshit-verma-596a0824b/
