### ISSUE TITLE
Add Dynamic Background to Gita Storyline Page

### ISSUE THREAD

**Issue by Skb08** [akshitagupta15june/Moksh#1727]
## Description

**Is your feature request related to a problem? Please describe.**
The current static background on the Gita Storyline page lacks visual engagement and dynamism, which can affect the overall user experience. Adding a dynamic background with movement can make the page more visually appealing and engaging.

**Describe the solution you'd like**
I propose adding a dynamic background that includes subtle, moving elements.

**Describe alternatives you've considered**

## Additional Information

**Context**
This feature request aims to improve the user experience on the Gita Storyline page by making it more visually appealing and interactive. A dynamic background can create a more immersive and engaging environment for users.

**Screenshots or Mockups** (optional)

https://github.com/akshitagupta15june/Moksh/assets/113046759/5cecf98e-6ba8-4c10-b3f7-8aaeee44aa0b

**Priority** (optional)
Medium

**Comment by akshitagupta15june** [comment]
Go for it!
