### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sharmaji513** [akshitagupta15june/Moksh#1728]
**Description**
Describe the bug:
The cards on the Iskcon Event page are overflowing into the inner footer section, causing layout issues.

**Expected behavior:**
The cards should be contained within their designated section and should not overflow into the footer.

**Actual behavior:**
The cards extend beyond their designated area and overlap with the footer section.

**Reproduction Steps**

- Go to the Iskcon page.
- Scroll down to the section where the cards are displayed.
- Observe the layout issue where the cards overflow into the footer.

**Expected result:**
The cards should be properly contained within their section, with no overflow into the footer.

**Actual result:**
The cards are extending beyond their section and overlapping with the footer.

**Screenshots**
![2024-06-14-02-03-46](https://github.com/akshitagupta15june/Moksh/assets/66481063/ee5381b3-ac03-4959-946f-6c7caa3f4af1)

 @akshitagupta15june  Please assign me this issue

**Comment by akshitagupta15june** [comment]
someone is working on it
