### ISSUE TITLE
[FEATURE REQUEST]  Addition of multilingual feature

### ISSUE THREAD

**Issue by Damini2004** [akshitagupta15june/Moksh#1730]
## Description

**Is your feature request related to a problem? Please describe.**
I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.

**Describe the solution you'd like**
Implementing multilingual support in a project can significantly enhance its usability, accessibility, and reach. Here are several ways this feature could enhance the use of the project and the benefits it would bring to the project or community:

**Describe alternatives you've considered**
User Inclusivity: By supporting multiple languages, the project becomes accessible to a wider audience who may not be proficient in the primary language. This inclusivity ensures that users from different linguistic backgrounds can use and benefit from the project.
Improved Usability: Users can interact with the project in their native language, which improves their overall experience and satisfaction. This is particularly important for complex projects where understanding the content is crucial for effective use.
Global Reach:

## Additional Information

**Context**
**Potential Implementation** (optional)
![image](https://github.com/akshitagupta15june/Moksh/assets/119414762/5d137c10-7a96-4bae-8cab-30272e077dda)

**Screenshots or Mockups** (optional)
![image](https://github.com/akshitagupta15june/Moksh/assets/119414762/fa87b51d-602b-44cb-b8c2-ed5549a2750a)

**Priority** (optional)
High
**Additional Notes** (optional)
Assign this to me under GSSOC i can implement it within one day

**Comment by akshitagupta15june** [comment]
its not required currently
