### ISSUE TITLE
[FEATURE REQUEST] Addition of Chatbot and Cursor pointer.

### ISSUE THREAD

**Issue by Anjaliavv51** [akshitagupta15june/Moksh#1731]
## Description

Addition of chatbot assistant helps the User to know about webpgae in detailed and custom cursor attractes the page.

custom cursor priview

https://github.com/akshitagupta15june/Moksh/assets/154777864/b187e86c-2671-4355-a041-b3c6dd696406

**Comment by Anjaliavv51** [comment]
@akshitagupta15june please assign me this issue under GSSOC.

**Comment by akshitagupta15june** [comment]
not required currently
