### ISSUE TITLE
[FEATURE REQUEST]  Add Responsive Footer

### ISSUE THREAD

**Issue by revanth1718** [akshitagupta15june/Moksh#1732]
I propose adding a responsive footer to the repository. A well-designed footer enhances the overall user experience by providing important information and navigation links in a consistent manner across all devices.
![footer](https://github.com/akshitagupta15june/Moksh/assets/109272714/a7f6b8c7-febb-4b02-ad84-80d942f1e49f)

**Comment by Harshverma893** [comment]
i am intereted plz asign this to me !

**Comment by akshitagupta15june** [comment]
someone is working on it

**Comment by Harshverma893** [comment]
ok but on right part in Assignees no one assigned
