### ISSUE TITLE
[BUG] Missing FontAwesome Stylesheet in rejuvenate.html

### ISSUE THREAD

**Issue by Bittukr7479** [akshitagupta15june/Moksh#1733]
## Description

The rejuvenate.html page is failing to load the FontAwesome stylesheet due to an incorrect URL.

![Screenshot 2024-06-16 172302](https://github.com/akshitagupta15june/Moksh/assets/123286618/42919054-3844-44ea-b52e-c6b97b035033)

**Comment by akshitagupta15june** [comment]
it is using a common css file
