### ISSUE TITLE
Folder Structuring  

### ISSUE THREAD

**Issue by vaibhav-xt** [akshitagupta15june/Moksh#174]
While seeing the repository I noticed that the structure of this folder is very bad and has to be improved. 

The new structure of the folder:

**Moksh**
 |    
 +-- **Images**
 |  |  
 |  +-- All the images
 |    
 +-- **Sounds**
 |  |  
 |  +-- All the sounds
 |  
 |    
 +-- **CSS**
 |  |  
 |   +-- Contain all the CSS files  
 |
 +-- **HTML**
 |   |
 |    +-- Container all the HTML Files
 |
 +-- Index.html
 |
  +-- Contributing.md file

**Comment by akshitagupta15june** [comment]
I am working on it
