### ISSUE TITLE
In Iskcon page, last card is overlapping on footer.

### ISSUE THREAD

**Issue by anuragkanojiya1** [akshitagupta15june/Moksh#1768]
## Description

**Describe the bug:**
In Iskcon page, last card is overlapping on footer.

**Expected behavior:**
Last card should not be overlapping on footer.

![Screenshot 2024-06-30 181559](https://github.com/akshitagupta15june/Moksh/assets/144598258/df5e511b-7176-4a18-8a41-4c964ca3cfec)

**Actual behavior:**
Last card is overlapping on footer.

![Screenshot 2024-06-30 181511](https://github.com/akshitagupta15june/Moksh/assets/144598258/0f155d37-5142-42ea-b1ea-572adfb6152f)

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'Iskcon page'
2. Scroll down to 'Footer section'
5. See error

## Additional Information

**Device (please complete the following information):**
- OS: [Windows]
- Browser [Chrome]
- Version [22]

**Additional context:**

Kindly Assign this issue to me under SSOC'24 @akshitagupta15june .

**Comment by Pratiksha1661** [comment]
Kindly Assign this issue to me under GSSOC'24
