### ISSUE TITLE
add scroll to top button

### ISSUE THREAD

**Issue by S-ishita** [akshitagupta15june/Moksh#177]
I want to add scroll to top button which will enhance user experience.Please assign this issue to me under GSSOC

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! "

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I can fix
issue by adding a button for scroll to top

**Comment by akshitagupta15june** [comment]
assigning u @S-ishita

**Comment by S-ishita** [comment]
alright @akshitagupta15june will raise pr once the restructuring is done.My code is ready :)

**Comment by Deepanshu0703** [comment]
Can you now assign this issue to me
