### ISSUE TITLE
Navbar Not Showing Up Properly 

### ISSUE THREAD

**Issue by Souravvmishra** [akshitagupta15june/Moksh#179]
The navbar is not correctly showing up in small display. I am using google chrome & have also checked with brave browser. 

Screen shot Provided Below 

![Screenshot_2023-05-20-11-14-33-218_com.android.chrome.jpg](https://github.com/akshitagupta15june/Moksh/assets/89072785/904e9f40-4596-4fd9-915c-6b839bcaf147)

I would like to work on this issue as for gssoc 2023

**Comment by Aditi323** [comment]
I would like to work on this issue as a gssoc contributor.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by akshitagupta15june** [comment]
someone else is working on this
