### ISSUE TITLE
Make the homepage responsive

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#180]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under GSSOC'23

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by PayalPadmalyaPrusty** [comment]
I want to contribute.Please assign me

**Comment by akshitagupta15june** [comment]
someone else is working on this
