### ISSUE TITLE
No other themes in web, Adding a light and dark mode switching button

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#182]
What feature?
I have an idea to create a button on top right corner under the navbar to add a toggle switch for light/dark mode,it would look good with the projects color scheme
please assign me this feature

![moksha](https://github.com/akshitagupta15june/Moksh/assets/83147410/b60a6a0a-7bd2-4c40-a1c1-6e8dcfa7b946)

**Comment by karthiknadar1204** [comment]
hii @HimanshuNarware The idea seems to be good but it doesn't align with the idea of the website, the website is themed around spirituality and a dark them goes against.
Could you please close this issue and explore other issues to contribute to😃
