### ISSUE TITLE
Read a Shlok button is not align with other button 

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#183]
The Read a shlok button is  dislocated . i want to work on this issue kindly assign me.
![moksha btn](https://github.com/akshitagupta15june/Moksh/assets/83147410/42d74720-786b-4971-b5e9-b6eceb420801)

**Comment by AlfiyaSiddique** [comment]
Hi! would like to take this issue can you assign this issue to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
assigning u
