### ISSUE TITLE
Make the Rejuvenate page Responsive

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#186]
While making it Responsive,I was thinking of adding a scrollup button as well to the responsive version of the page

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by akshitagupta15june** [comment]
ok assigning u

**Comment by ankitjt** [comment]
@karthiknadar1204 this was done, can I close it now?

**Comment by karthiknadar1204** [comment]
Working on this one
