### ISSUE TITLE
Web site is not responsive

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#187]
hey !  The website layout  is  not responsive  and the navbar is also not responsive 
 assign me this issue so i can work on this thing
![moksha rspnsv](https://github.com/akshitagupta15june/Moksh/assets/83147410/39b607f0-a9da-41bf-9ec0-18ff461cf52f)

**Comment by Kwamecody** [comment]
Hi there, I will be very happy if you can assign me this issue.

I am a contributor for GSSoC 2023.

Thank you in advance.
