### ISSUE TITLE
Pomodoro Timer Bug

### ISSUE THREAD

**Issue by swapnilgarg7** [akshitagupta15june/Moksh#19]
<img width="443" alt="Screenshot 2023-04-09 at 7 49 39 PM" src="https://user-images.githubusercontent.com/32569674/230778152-0a769b8b-a457-4071-9a22-e55da3802c47.png">
Even after starting the timer, it shows the button as start as not stop. 
Further, if you click on Start again, the timer acts weirdly and reduces 2 seconds at once.

**Comment by akshitagupta15june** [comment]
ok u can work on it

**Comment by swapnilgarg7** [comment]
[Fixed it](https://github.com/akshitagupta15june/Moksh/pull/20)
