### ISSUE TITLE
Blog page is buggy

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/Moksh#190]
Hey @akshitagupta15june The blog page is not properly aligned and also the navigation is not working for the features section from the blog page. Please assign me this issue so I can fix it. Thank you!

**Comment by akhil888binoy** [comment]
can you please add a screenshot?

**Comment by sumitkr2000** [comment]
@akhil888binoy yeah sure!

**Comment by sumitkr2000** [comment]
![Screenshot (744)](https://github.com/akshitagupta15june/Moksh/assets/100675296/c98f1215-5e3c-4a95-88b5-20e6f19462d9)

These links are not working

**Comment by ankitjt** [comment]
@sumitkr2000 do a new pull request, and you'll find the issue is fixed.
