### ISSUE TITLE
Home page overflowing

### ISSUE THREAD

**Issue by tripti033** [akshitagupta15june/Moksh#193]
1) page overflowing
2) features drop-down bug

kindly assign this issue to me for GSSOC'23

**Comment by tripti033** [comment]
![image](https://github.com/akshitagupta15june/Moksh/assets/107789391/350de3a3-7309-4acb-8c5e-1304892b965d)
the home page is overflowing through the right and the UI of features drop down is somehow amendable .

**Comment by Hritik1503** [comment]
kindly assign this issue to me for GSSOC'23

**Comment by ankitjt** [comment]
Hey , this is getting fixed in the latest PR , closing the issue.
