### ISSUE TITLE
Improving UI of button in Shlok section

### ISSUE THREAD

**Issue by Yashika-Agrawal** [akshitagupta15june/Moksh#194]
to improve the color of the button and adding hover effect   to make it more eye catchy and attractive in the shlok section as it is not clearly visible now.

**Comment by Yashika-Agrawal** [comment]
Hey @akshitagupta15june , I am a GSsoc'23 contributor please assign this issue to me.

**Comment by akhil888binoy** [comment]
can you please add a screenshot ?

**Comment by akshitagupta15june** [comment]
assigning u @Yashika-Agrawal
