### ISSUE TITLE
To improve UI of Srila Prabhupada Stories

### ISSUE THREAD

**Issue by Yashika-Agrawal** [akshitagupta15june/Moksh#195]
i want to improve the ui of div containers of the story so that it looks more eye catchy and is easier to read with a hover effect on it.

**Comment by Yashika-Agrawal** [comment]
Hey @akshitagupta15june , I am a GSsoc'23 contributor i want you to assign this issue to me as it comes under my technical skills domain and i need to work on it.

**Comment by karthiknadar1204** [comment]
Hii @Yashika-Agrawal ,this issue has already been assigned refer #170 . Please refer to other issues to contribute to;
Feel free to raise your own issue, we will review them and assign it 
Thank you
