### ISSUE TITLE
[Meditation Page] Play Pause icon psotions are not synced and music cards UI can be imporved 

### ISSUE THREAD

**Issue by Harsh-s0ni** [akshitagupta15june/Moksh#196]
The play - pause icon positions  are not synced (see image attached)
![image](https://github.com/akshitagupta15june/Moksh/assets/94621076/8d1654de-13c9-469e-9783-9d60f94ae5b9)
![image](https://github.com/akshitagupta15june/Moksh/assets/94621076/34e1a5ad-58d8-4b5e-973c-fd436c66354d)

Also, 
The music cards UI can be improved
Improve responsiveness of the page

i would like to contribute in this under GSSOC'23
Please Assign it to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by Harsh-s0ni** [comment]
Thanks,
I have already done all the work
Should I create PR?
