### ISSUE TITLE
Improve hover effect of navbar links and make navbar responsive

### ISSUE THREAD

**Issue by stuti-09** [akshitagupta15june/Moksh#197]
I want to improve hover effect of navbar links and the navbar is not responsive. It look like this-
![Screenshot (169)](https://github.com/akshitagupta15june/Moksh/assets/93007935/89b32fe6-ec92-4661-98bb-d31d3dae978f)
Please assign me this issue under gssoc'23.

**Comment by akhil888binoy** [comment]
#187

**Comment by PatilHarshh** [comment]
Please assign it to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
some are working on the same
