### ISSUE TITLE
Not Reshow the AR Info Cards

### ISSUE THREAD

**Issue by kumarankit999** [akshitagupta15june/Moksh#200]
When I Once Listen the AR Song of any choice if i click once on Play Button the Info Card is being disappear, and never come back,
It should come after playing and pausing too

![image](https://github.com/akshitagupta15june/Moksh/assets/111564362/e7312bbd-7bd3-4dc2-a798-0ce9e0a56710)

**Comment by ankitjt** [comment]
This issue was fixed. Closing.
