### ISSUE TITLE
Same Options in a Quiz

### ISSUE THREAD

**Issue by kumarankit999** [akshitagupta15june/Moksh#202]
There are 2 Same Options in the question "Who was Sanjaya ? "

![image](https://github.com/akshitagupta15june/Moksh/assets/111564362/e2d755a9-56f0-4b33-81c7-fa3ead46147d)

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by kumarankit999** [comment]
I have Created a PR related to this @akshitagupta15june
