### ISSUE TITLE
Improve the footer UI

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [akshitagupta15june/Moksh#204]
I would like to change the UI of footer and make it more informative

**Comment by KhushiKhandelwal610** [comment]
Please assign it to me under GSSOC'23

**Comment by ankitjt** [comment]
Please provide what changes you wish to incorporate and how would you make it more informative?

**Comment by PayalPadmalyaPrusty** [comment]
@ankitjt I want to contribute.Please assign me

**Comment by Pragati-3003** [comment]
Hey @akshitagupta15june 
I would like to work on this issue.
Please assign this issue to me under GSSOC'23.
Thanks
