### ISSUE TITLE
Feature: Improved Srila Prabhupada Stories Sections

### ISSUE THREAD

**Issue by kumarankit999** [akshitagupta15june/Moksh#205]
In this Stories Section ,We can do one thing here is that The information should be in one side and the relevant picture about this information should be on the opposite direction. Ex: If Info will be in right side the picture will be in right and vice-versa.

![image](https://github.com/akshitagupta15june/Moksh/assets/111564362/cad79de9-e94e-4973-be29-a35135057851)

**Comment by karthiknadar1204** [comment]
Hii @kumarankit999 , this issue has already been assigned #170 , could you please explore some issues to contribute.
Please feel free to raise your own issues, we will review them and assign it
