### ISSUE TITLE
[FEATURE] Add a "Scroll-to-Top" button

### ISSUE THREAD

**Issue by harshita-kaushik2** [akshitagupta15june/Moksh#209]
Hey,
As one can observe from viewing the website, it lacks a scroll-to-top button. 
Adding this floating button would enhance the user experience of the website.

I'd love to contribute this feature as I have past experience of creating in my personal projects.
I would request you to assign this issue to me as GSSoC 2023 Contributor.

**Comment by sanketsaurav2411** [comment]
Hi @akshitagupta15june . I would like to give a shot at fixing this issue as well. Could you assign this to me as well under GSSOC'23?

**Comment by karthiknadar1204** [comment]
@harshita-kaushik2 This issue has already been assigned, could you please explore some other issues to contribute to😃
