### ISSUE TITLE
[ENHANCEMENT] Add styling to the scroll bar

### ISSUE THREAD

**Issue by harshita-kaushik2** [akshitagupta15june/Moksh#210]
Hey,
As one can observe from the website, that the scroll bar is plain vanilla and does not match the theme of the website.
Styling the scrollbar as per the theme of the website would add to enhance the overall UI of the page.

I would love to add this feature and request you to assign this issue to me as a GSSoC 2023 contributor.
Thank You :)

**Comment by karthiknadar1204** [comment]
Could you elaborate what would you be doing here in this issue?

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by ankitjt** [comment]
Update status? ASAP

**Comment by harshita-kaushik2** [comment]
Hey @ankitjt Sorry for the delay caused. I seem to have missed that my request to assign this issue was accepted. 
I have made the pull request for the issue !!
