### ISSUE TITLE
[BUG] player not visible in AR page

### ISSUE THREAD

**Issue by Shalini469717** [akshitagupta15june/Moksh#211]
![image](https://github.com/akshitagupta15june/Moksh/assets/99305545/a2212517-cbf7-4e12-a74e-46eab4a8a320)

- [ ] The player should be visible

- [ ] Only one song should be played at a time.

**Comment by Shalini469717** [comment]
Can I work on this issue as part of GSSOC?

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by Shalini469717** [comment]
Seems like the bug is already fixed with the new changes. Maybe we close the issue.

**Comment by mnik7044** [comment]
Yes you can close it.
