### ISSUE TITLE
Adding a Bootstrap Navbar for Mobile Optimization

### ISSUE THREAD

**Issue by sabhisharma-ise** [akshitagupta15june/Moksh#215]
Actual Behavior:
![image](https://github.com/akshitagupta15june/Moksh/assets/100849696/b003af3e-02e6-42e3-bf77-1b1edee25e68)
| *The website is difficult to navigate on mobile devices.* |

Expected Behavior:
The website should be easy to navigate on mobile devices.

Notes:

- A Bootstrap Navbar is a responsive navigation bar that works well on all devices.
- Adding a Bootstrap Navbar to the website would improve the mobile user experience

Possible Solutions:

- Add a Bootstrap Navbar to the website.
- Use a different navigation bar solution that is mobile-friendly.

Please assign me this issue!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Developer-Swati** [comment]
Hi, I am Swati .I want to fix this . Please assign it to me . I have knowledge of Html, Css, Js, and Bootstrap. By the way , Mokesh is the best initiative. I really want to contribute to it .
