### ISSUE TITLE
[BUG] Website is Not Responsive

### ISSUE THREAD

**Issue by sanketsaurav2411** [akshitagupta15june/Moksh#219]
Hi @akshitagupta15june . I would like to make the webpage responsive, so that user can access the website seamlessly on all devices.
Please assign me this issue under GSSOC'23.

**Comment by sanketsaurav2411** [comment]
> Hi @akshitagupta15june . I would like to make the webpage responsive, so that user can access the website seamlessly on all devices. Please assign me this issue under GSSOC'23.


Including Navigation Bar alignment and Mobile-friendly UI.

**Comment by akshitagupta15june** [comment]
some are already working on this
