### ISSUE TITLE
Include a "About ISKCON" part in About section and their achievements

### ISSUE THREAD

**Issue by rayarka26** [akshitagupta15june/Moksh#222]
I would love to do this if you feel you can assign it. I will  populate it with some content

**Comment by PrasunKundu** [comment]
Hey , As a GSSoC contributor i would love to contribute in your issue . Please assign it to me. Little bit about me : I am Prasun Kundu a first year EEE student . I have a keen interest in Spirituality such a ISKCON and its legacy.

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by rayarka26** [comment]
I have done the PR for it
