### ISSUE TITLE
Adding github repo in the footer

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/Moksh#224]
Hey @akshitagupta15june I want to add the GitHub repo in the footer. Please assign me this issue. Thank you!

**Comment by ankitjt** [comment]
this is a good suggestion, we are still finalising the content of the footer, once we do that we can assign you the issue to implement it.  My two cents would be along with the repo url , you can add stars and forks count too.

Pl wait till we get few things streamlined.

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by sumitkr2000** [comment]
Hey @akshitagupta15june is @ankitjt woking on this issue?

**Comment by ankitjt** [comment]
No you can add the features as suggested too.
