### ISSUE TITLE
The images in the website are not fit for the size of the div

### ISSUE THREAD

**Issue by dishal35** [akshitagupta15june/Moksh#225]
They look unnecessarily stretched and get also get cut at certain places. They also don't follow a certain category, i.e some of the images are vectors, others are jpeg files with backgrouds. I would like to suggest other images to improve the UI of the website.

**Comment by ankitjt** [comment]
pl provide a section/ page name where you encountered this issue? Share relevant screenshots.

**Comment by dishal35** [comment]
![Screenshot (19)](https://github.com/akshitagupta15june/Moksh/assets/121967766/f75e064a-0687-4259-9af1-a5093f37003a)
![Screenshot (20)](https://github.com/akshitagupta15june/Moksh/assets/121967766/0d94cf05-23c2-4b41-b779-de80a359c964)

**Comment by karthiknadar1204** [comment]
@dishal35 The images seem to be cut in the corners due to the border radius of the image container not aligning with the external div and the images seem to be stretched  due to the object fit property on the image, Please wait for it to be reviewed and assigned.
Thank you

**Comment by akshitagupta15june** [comment]
they are fine 
Thanks
