### ISSUE TITLE
Improving Card in the ISKCON Events Page

### ISSUE THREAD

**Issue by NehaKariya0309** [akshitagupta15june/Moksh#228]
Issue:
The cards on the event page looks inconsistent with images and text being in different proportions.
Solution:
The cards can be improved by adjusting the width of div element and the height of the images.

I want to work on this issue. I am a GSSoc'23 contributor.
Thanks,
Neha Kariya

**Comment by Mayank2808sharma** [comment]
Kindly assign this issue to me

**Comment by parag477** [comment]
I'd like to work on this issue

**Comment by akshitagupta15june** [comment]
someone is working on it
