### ISSUE TITLE
Improve background video of container below Navbar.

### ISSUE THREAD

**Issue by VivekRaj212** [akshitagupta15june/Moksh#229]
Issue:
The background video of the container below the navbar is blurred. It is not looking aesthetic and not going well with the UI of the website.

Solution:
Its background can be improved and make it look good if we are adding copyright-free video from Unsplash.

@akshitagupta15june  Please assign me this issue under gssoc'23. I will fix it and make it look awesome.

**Comment by akshitagupta15june** [comment]
its not required
thanks

**Comment by VivekRaj212** [comment]
It's okay
