### ISSUE TITLE
Improve the Navbar styling

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#23]

**Comment by R1shabh-Gupta** [comment]
I would like to request permission to work on this issue and contribute to the improvement of the Navbar styling.

**Comment by pamnanaimanish169** [comment]
Hi @karthiknadar1204,

Hope you are doing well! Seems like I could be of some help in solving this issue. Let me know if this is feasible.

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,have shifted the logo to the left and the navbar links to the right,home button is to the extreme right,will correct the directions,have changed the hover effect of the navbar links as well.

Will keep updated and initiate pr soon.

Thank you.

**Comment by karthiknadar1204** [comment]
<img width="1792" alt="Screenshot 2023-04-10 at 3 15 45 PM" src="https://user-images.githubusercontent.com/95973644/230877788-0f3d8029-2949-4d49-a0a1-6f613d8489a9.png">

@akshitagupta15june ,are these changes fine or should i add/delete anything else

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,any opinion, initiating pr
