### ISSUE TITLE
Improving the headings and images in Divine Activities Page

### ISSUE THREAD

**Issue by NehaKariya0309** [akshitagupta15june/Moksh#230]
Issue:
The title in this page can be made catchy and impactful. The images of the exercises are cut off from the screen.
Suggested Solution:
The images can be adjusted by creating a flex container or providing a grid layout. The headlines can be made catchy.

I want to work on this issue. I am a GSSoc'23 contributor.  Please assign this to me.
Thanks and regards,
Neha Kariya

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by akshitagupta15june** [comment]
assigning u
