### ISSUE TITLE
New Quote button

### ISSUE THREAD

**Issue by avnigoyal25** [akshitagupta15june/Moksh#231]
![Screenshot (104)](https://github.com/akshitagupta15june/Moksh/assets/91952706/aedef2b2-3180-49b0-bd40-0b7e368dc9ee)

New quote button is not properly placed. i want to work on this issue

**Comment by NehaKariya0309** [comment]
Hey, even I would like to work on this issue. To resolve this, I think slight adjustments in footer will also be required.

**Comment by avnigoyal25** [comment]
I am good at CSS so i think i can do it properly.

**Comment by akshitagupta15june** [comment]
someone are working on this
