### ISSUE TITLE
The timer in the "Pomodoro Spritual Break" is showing 0.01 as the default value instead of 0.00 as the default value 

### ISSUE THREAD

**Issue by Sch476** [akshitagupta15june/Moksh#235]
Steps to reproduce : 
1)Open the website 
2)Scroll down until you find "Pomodoro Spritual Break"
3)Click on "Take a Break"
4)Click on the "Reset" button

Actual result  : the counter shows 0.01 as the default value of the timer.

Expected Result : The counter should show 0.00 as the default value of the timer.

![Screenshot (95)](https://github.com/akshitagupta15june/Moksh/assets/127319225/392cff1e-63e0-44b9-b6b2-eab437a738fc)

Please assign this issue to me.
GSSOC'23 contributor

Thank You.

**Comment by parag477** [comment]
I'd like to work on this issue. Please assign this issue to me

**Comment by ManashAnand** [comment]
Hi there! I would like to contribute to this issue. I have gone through the problem description and would love to help out. I have experience with similar problems and believe I can provide a solution. Could you please assign this issue to me so that I can start working on it? Thank you!

**Comment by akshitagupta15june** [comment]
assigning u @Sch476

**Comment by Sch476** [comment]
Thank You @akshitagupta15june for assigning this issue to me . Can you guide me where I should start, should I fork the project and start solving the issue. And what should be my steps for final submission. Also please give me the deadline for submitting this project.
