### ISSUE TITLE
## Issue: Improve File Structure in Repository

### ISSUE THREAD

**Issue by Kalyan-velu** [akshitagupta15june/Moksh#236]
### Description
I've noticed that the file structure in the [Moksh repository](https://github.com/akshitagupta15june/Moksh) requires improvement. Currently, all types of files, including JavaScript, GIF, CSS, HTML, and the README.md file, are located in the root directory. This makes it challenging to understand the purpose of each file and troubleshoot issues effectively.

### Goals
The main objective of this issue is to restructure the file organization in the repository to enhance the overall experience. By doing so, we aim to achieve the following:

- Improve clarity and maintainability: Organize files in a logical and intuitive manner to make it easier for contributors to understand their purpose and navigate the repository.
- Simplify debugging: Group related files together based on their functionality or module, enabling efficient issue identification and debugging.
- Streamline collaboration: Establish a consistent and coherent file structure to facilitate collaboration among contributors.

### Proposed Solution
I would appreciate suggestions for the new file structure. Here are a few initial ideas:

1. Create separate directories for different file types, such as "js," "gif," "css," and "html."
2. Group related files together based on their functionality or module.
3. Consider adopting a modular approach, where each module has its own directory containing all relevant files.

Please provide your input and suggestions regarding the new file structure.

### GirlScript Summer of Code 2023
This issue is part of my contribution to GirlScript Summer of Code 2023. I am open to fixing this issue.

If you have any additional information or considerations to add to this issue, please let know.

**Comment by Kalyan-velu** [comment]
## Comment: I want to contribute to this issue

Hi there! I would like to contribute to this issue and help improve the file structure in the Moksh repository. I understand the challenges posed by the current file organization, and I'm eager to help create a more organized and efficient structure.

I would be happy to work on implementing the proposed solution, such as creating separate directories for different file types and grouping related files based on their functionality or module. Please let me know how I can get started and contribute to this effort.

Looking forward to collaborating with you on this!

Best regards,
@Kalyan-velu

**Comment by karthiknadar1204** [comment]
@Kalyan-velu @akshitagupta15june is already working on this issue,Please explore some other issues to contribute to for time being😃
