### ISSUE TITLE
Non-functional Navbar Elements on Different Screen Sizes

### ISSUE THREAD

**Issue by premsaivarmachekuri** [akshitagupta15june/Moksh#237]
Hi @akshitagupta15june 

I have identified an issue with the non-functional navbar on the website, specifically related to the Home, About, Power of Knowledge Blogs, Features, and Select Language elements. The navbar is not functioning properly on different screen sizes, which affects user navigation.

**Problem:**
The navbar is non-functional and does not allow users to access important sections of the website.
Mobile
![image](https://github.com/akshitagupta15june/Moksh/assets/110842297/9cdc835c-183d-4e79-b3a1-5ef9e33ed6d4)

Tablet
![image](https://github.com/akshitagupta15june/Moksh/assets/110842297/8834bade-b4bd-438f-b020-f46ef54a8fdb)

Desktop
![image](https://github.com/akshitagupta15june/Moksh/assets/110842297/d6256810-ef04-4f10-9c31-88e3f1cef9bc)

**Feature:**
The navbar should be fully functional and responsive, allowing users to navigate to Home, About, Power of Knowledge Blogs, Features, and Select Language sections seamlessly.

**Additional Information:**
The issue is observed on multiple screen sizes, including mobile, tablet, and desktop.
It is crucial to fix this issue to enhance the usability and accessibility of the website.
The website is being developed as part of GSSOC23, and I have prior experience in resolving similar issues on different projects.
I have followed the [code of conduct](https://github.com/akshitagupta15june/Moksh/blob/main/CODE_OF_CONDUCT.md) for this project and I look forward to your response.

Best regards,
Premsai Varma

**Comment by ankitjt** [comment]
pl include on which page(s) do you find this issue. Currently not all pages are updated with the latest changes pertaining to the navbar and footer.

**Comment by premsaivarmachekuri** [comment]
> pl include on which page(s) do you find this issue. Currently not all pages are updated with the latest changes pertaining to the navbar and footer.

I have found this issue on the Home page.

**Comment by akshitagupta15june** [comment]
some are working on the same

**Comment by premsaivarmachekuri** [comment]
ok noted

**Comment by premsaivarmachekuri** [comment]
Dear Ashitha,

I hope this email finds you well. I wanted to seek your guidance regarding
a matter related to the Moksh spiritual website. I have recently come
across three to four issues that have not been addressed by anyone yet.
These issues involve important enhancements that can significantly improve
the overall user experience on the website.

Now, I am contemplating whether it would be more effective to raise all the
issues simultaneously or address them one by one. I value your expertise in
such matters and would greatly appreciate your guidance on this decision.

Thank you for your time and consideration. I look forward to your valuable
insights.

Regards,

Premsai Varma
