### ISSUE TITLE
Adding certificates on completion of a goal!

### ISSUE THREAD

**Issue by anan262** [akshitagupta15june/Moksh#242]
Hey! I'm super thrilled to be a part of GSSOC and would like to contribute to this one! I'm in my sophomore year and would be deeply excited to use all my expereinces in numerous projects in this one! My idea is to add certificates in this website to motivate learners to stick to their goals and stay consistent in their goal for a countable number of days!

**Comment by ankitjt** [comment]
what kind of certificates?
Creating any kind of profile where user's progress is stored would like database implementation, oAuth and related setup. 
So far implementing that is under discussion.

**Comment by anan262** [comment]
Hey! This idea would make use of the stored progress and in case any goal/session such as doing the pomodoro technique for 10 days or so is done, they will get awarded a certificate of appreciation sorta thing

**Comment by akshitagupta15june** [comment]
its not required now
