### ISSUE TITLE
[GGSoC'23] Adding animation on scroll on the cards.

### ISSUE THREAD

**Issue by VC6378** [akshitagupta15june/Moksh#244]
Hey,
I would like to make the cards responsive and would add animation on scroll, which would make the website more interactive.

**Comment by ombhojane** [comment]
Hello, I'm Om.
I'd worked on similar issue. I want to work on this issue, can you explain a bit more. I will happy to contribute in this issue.

**Comment by GazalBandil** [comment]
Hello , @akshitagupta15june  I am good with css and animations and I would like to contribute in this project please assign to me so that I can start working.

**Comment by akshitagupta15june** [comment]
some are working on it
