### ISSUE TITLE
social media icons

### ISSUE THREAD

**Issue by NehaSharma101** [akshitagupta15june/Moksh#246]
Greetings, I want to add some social media icons in the footer section of the website

**Comment by PR1YAM9** [comment]
hello,
I would like to add the social media icon links to the footer section and make it responsive on all media widths for the best user experience.
Regards Priyam Maini

**Comment by Nikitaparmar04** [comment]
creating attractive social media icons for websites involves a combination of design principles and technical implementation.
Determine the design style: Consider the overall look and feel of your website and decide on a design style for the icons. They should match the aesthetics and branding of your website while being visually appealing.

Choose the right icon set: Select a set of social media icons that align with your design style. You can find many free and premium icon sets online. Ensure the icons are recognizable and represent the respective social media platforms clearly.

Customize the icons: To make the icons attractive and unique, you can customize them using graphic design software such as Adobe Photoshop or Illustrator. Here are some customization ideas:

Adjust the color scheme to match your website's color palette.
Add subtle gradients, shadows, or highlights to give them depth.
Experiment with different shapes, outlines, or borders.
Incorporate your logo or brand elements into the icons.
Optimize the icons for web: After customizing the icons, you need to optimize them for web use. Consider the following aspects:

Size: Resize the icons to an appropriate dimension that fits well within your website layout.
File format: Save the icons in a suitable web format, such as PNG or SVG, to maintain quality and ensure compatibility.
File size: Compress the icons to reduce file size without compromising too much on quality. This helps improve website loading speed.
Placement and visibility: Decide where to position the social media icons on your website. They are commonly placed in the header, footer, sidebar, or floating bar. Ensure the icons are easily noticeable and accessible to visitors.

Hover effects: Consider adding interactive hover effects to the icons. For example, the color could change, or a subtle animation or tooltip could appear when users hover over an icon. This enhances the user experience and makes the icons more engaging.

Linking the icons: Once you have your customized social media icons, you need to link them to your respective social media profiles. Use the appropriate URLs for each platform to ensure visitors are directed to the correct page.

Testing and responsiveness: Test the icons across different devices and screen sizes to ensure they display properly and are responsive. Icons should adapt well to different screen resolutions, maintaining their visibility and usability.

**Comment by akshitagupta15june** [comment]
i am working it
