### ISSUE TITLE
Adding the social media icons in footer section

### ISSUE THREAD

**Issue by shineishukla** [akshitagupta15june/Moksh#248]
Assign this issue to me under GSSoC'23

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by VanshKing30** [comment]
The Footer Section Seems Very simple , I can Give it a nice modern look 
Assign this issue to me under Gssoc'23

**Comment by akshitagupta15june** [comment]
I on process of making one soon
thanks
