### ISSUE TITLE
The UI of the webpage

### ISSUE THREAD

**Issue by shivani-tripurari** [akshitagupta15june/Moksh#249]
- The layout of page
- Making the website more user friendly
- Social media handles 
- Contact us section
- Modifying navbar 

Please assign this issue to me and I'll surely help in improving the overall user experience.
@akshitagupta15june

**Comment by ankitjt** [comment]
Please provide a specific page and section you would like to take up and update your issue accordingly.  

To provide other interested contributors opportunity to work on issues/features we would prefer not to assign the entire makeover to one contributor.

**Comment by shivani-tripurari** [comment]
I would like to work on home page and about section

> Please provide a specific page and section you would like to take up and update your issue accordingly.
> 
> To provide other interested contributors opportunity to work on issues/features we would prefer not to assign the entire makeover to one contributor.

I would like to work on home and about section.

**Comment by akshitagupta15june** [comment]
please join discord channel for discussion on the UI
