### ISSUE TITLE
Issue: Grammatical Error in the Augmented Reality Description [GSSoC'23]

### ISSUE THREAD

**Issue by Sriparno08** [akshitagupta15june/Moksh#253]
The Description:

> AR meditation combines ancient teachings of the Gita with AR technology, making it more accessible and engaging for modern practitioners. This unique and immersive meditation experience helps people connect more deeply with their inner self and the divine.

Here, the word `self` needs to be changed to `selves` as it is referring to people (plural).

**Comment by Sriparno08** [comment]
I would like to work on this.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it @akshitagupta15june
