### ISSUE TITLE
Issue: Grammatical Errors in the Divine Activities for All Generation Description [GSSoC'23]

### ISSUE THREAD

**Issue by Sriparno08** [akshitagupta15june/Moksh#254]
The Description:

> Moksh offers interactive activities for all generation to reduce stress and also learn about our holy book BhagwadGita and its principles. It contains eye exercises to reduces eye stress while working and also some desk exercises to reduce back pain while working.

Changes that need to be made:

- `generation` -> `generations`
- `reduces` -> `reduce`

**Comment by Sriparno08** [comment]
I would like to work on this.

**Comment by 0xSaksham** [comment]
Hey, I can work on this issue.

**Comment by SanchitMahajan236** [comment]
I would like to work on this issue as part of GSSoC'23

**Comment by ADITI-2003** [comment]
Hello, @akshitagupta15june ma'am,
I would like to improve the blog page grammatically, please assign this issue to me under GSSoC 2023.
Thank you

**Comment by akshitagupta15june** [comment]
assigning
