### ISSUE TITLE
Adding dark mode feature [GSSOC'23]

### ISSUE THREAD

**Issue by Shubhcs01** [akshitagupta15june/Moksh#256]
Website currently have no dark mode fearure.

Adding dark mode feature will give following benefits to users:

- Enhanced visual comfort and reduced eye strain in low-light environments.
- Potential energy savings on devices with OLED or AMOLED screens, leading to improved battery life.
- Improved accessibility for users with visual impairments or sensitivity to light.
- Aesthetic appeal and keeping up with design trends.
- Personalization and catering to user preferences.

**Comment by sang-4** [comment]
I'd like to work on this issue. Kindly assign

**Comment by Shubhcs01** [comment]
> I'd like to work on this issue. Kindly assign

Hi @sang-4 , Actually I'm working on this issue. You can look out for any other issues.

**Comment by karthiknadar1204** [comment]
Hii @Shubhcs01 @sang-4 We are not looking for a light/dark theme functionality in the website for now.
Please explore other issues to contribute to .
Feel free to raise more issues , we will review them and assign them to you
Thank you
