### ISSUE TITLE
Fixing grammatical and punctuation mistakes in the blog page [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [akshitagupta15june/Moksh#261]
There are many grammatical and punctuation mistakes in Topic 1 of blog page. Would like to fix them. Please assign this issue to me.
I am a GSSOC'23 contributor.

**Comment by karthiknadar1204** [comment]
Could you please share screenshots of these errors @Anshul439

**Comment by Anshul439** [comment]
![2023-05-22](https://github.com/akshitagupta15june/Moksh/assets/123325132/82d8e083-ff34-41e3-b988-3126b272501d)
![2023-05-22 (1)](https://github.com/akshitagupta15june/Moksh/assets/123325132/c315df45-ccbd-4477-b2c3-9ef623f0efbf)

**Comment by akshitagupta15june** [comment]
assigning u
