### ISSUE TITLE
Adding the navbar in Home page

### ISSUE THREAD

**Issue by jayantajm1** [akshitagupta15june/Moksh#262]
Hi,I am contributor of GSSOC'23, I just checked that in home page navbar is not working on mobile view . I want to added this feature in this project that's will be user friendly and attractive. As a front-end developer geek I can fixed this issue.it will be my nice starter in open source contribution, So Please assign me this issue. @akshitagupta15june  
Thank you

**Comment by akshitagupta15june** [comment]
some are working on it

**Comment by jayantajm1** [comment]
ok, thank you @akshitagupta15june  for replying to me.
 I'll try to figure out another issue or add new features and rise my request later.
