### ISSUE TITLE
website need black color theme in it

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#266]
I can create a button to change the  theme  of the website, which improves the overall user experience
kindly assign me this issue
![moksha](https://github.com/akshitagupta15june/Moksh/assets/83147410/98ab617f-96a7-42e3-937d-a7d728fc5b35)

**Comment by akshitagupta15june** [comment]
not needed in this website

**Comment by karthiknadar1204** [comment]
Hii @HimanshuNarware  We are not looking for a light/dark theme functionality in the website for now.
Please explore other issues to contribute to .
Feel free to raise more issues , we will review them and assign them to you
Thank you
