### ISSUE TITLE
Grammitical errors in website

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#268]
website content has some grammatical errors
kindly assign me this issue
![Screenshot 2023-05-21 234044](https://github.com/akshitagupta15june/Moksh/assets/83147410/27e6503d-69b8-4ed3-98e3-60b837f88123)
![Uploading Screenshot 2023-05-21 234102.png…]()

**Comment by garimatanejaa** [comment]
Hi there! I would to enhance the readability and engagement of your website that will impact user experience and encourage visitors to spend more time on your site.
Please assign it to me under GSSOC'23 
Thank you!

**Comment by DhairyaMajmudar** [comment]
Hey, I am Dhairya Majmudar. I would love to contribute To this issue under GSSoC'23. It will be really good if you assign me this issue.

**Comment by akshitagupta15june** [comment]
its not required now
