### ISSUE TITLE
Augmented Reality Meditation page background quality  is bad

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/Moksh#269]
I want to  improve the quality of the  background image
please assign me this issue
![bkg](https://github.com/akshitagupta15june/Moksh/assets/83147410/fbd18b4c-94a1-4bde-a9a6-0062471032f4)
![moksha btn](https://github.com/akshitagupta15june/Moksh/assets/83147410/bfebae06-53c4-4b7f-a4d4-f5a9656f8381)
![page](https://github.com/akshitagupta15june/Moksh/assets/83147410/df251df7-179e-42aa-84a6-7951ecd7fd20)

**Comment by akshitagupta15june** [comment]
some are working on this
