### ISSUE TITLE
underline hover on features button on nabar

### ISSUE THREAD

**Issue by laibaahsan27** [akshitagupta15june/Moksh#270]
![image](https://github.com/akshitagupta15june/Moksh/assets/123810454/8b03088f-0848-4a34-a806-7445363cabad)
As you can see that when i scrolled over to the features button then the hover on underline is coming in black colour whereas on all other buttons hover underline is of white colour. 
@akshitagupta15june  I can change it if you allow me by assigning this task to me under the label of GSSOC 2023.

**Comment by Harshs0891** [comment]
@akshitagupta15june  Plz assign me this issue under GSSOC 2023. I wants to work on it.

**Comment by akshitagupta15june** [comment]
some are working on this
