### ISSUE TITLE
[GSSOC'23] Fixing bug in the augmented reality page

### ISSUE THREAD

**Issue by Soumyajit2825** [akshitagupta15june/Moksh#271]
![Screenshot 2023-05-22 001357](https://github.com/akshitagupta15june/Moksh/assets/100519291/b0f16b5a-703b-4566-b65a-fbc6a2904121)

Here after playing the music the title box is vanishing. It looks like there is something error in the code
I want to work on this issue
Kindly assign me under GSSOC'23

**Comment by akshitagupta15june** [comment]
some are working on this
