### ISSUE TITLE
[GSSOC'23] Fixing the NavBar, making it Responsive, Clean and Organized

### ISSUE THREAD

**Issue by VamilP** [akshitagupta15june/Moksh#272]
Hi Team,

Good Day!

I have made changes to the code and created a responsive navbar. This was achieved by taking the below steps.

1. Made the navbar more clean
2. Made it responsive

Kindly find the attached snapshots of the updates done by me.

<img width="947" alt="update-responsive-navbar-desktop-view" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/d692c5ac-d89d-4af6-85bc-71d5c965aca8">
<img width="339" alt="update-responsive-navbar-mobile-view" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/d65310ed-35dd-492b-ad9f-7c2aa8df1f4f">
<img width="334" alt="update-responsive-navbar-mobile-view-menu" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/442e57fd-a268-4a92-94cb-f06db8409c32">

I would request you to assign me this task so that I can raise the pull request for the same.

GSSOC'23 contributor

**Comment by karthiknadar1204** [comment]
Hii @VamilP The changes look really good but this issue has already been assigned refer #184 
Please explore other issues to contribute to.
Feel free to raise new issues, we will review them and assign them to you.
Thank you

**Comment by VamilP** [comment]
Hi @karthiknadar1204,
Please let me know if you need above changes in the navbar in the future, thank you!
