### ISSUE TITLE
Improve 'Read a Shlok' page

### ISSUE THREAD

**Issue by VSatwika** [akshitagupta15june/Moksh#283]
- Adjusting the New Quote Button:
    The New Quote button needs to be positioned properly to ensure it does not interfere with the readability of the quotes or 
     overlap with other elements on the page.

- Adjusting the Twitter Button:
    Same issue as New Quote Button

- Improve spacing of elements in footer:
      The current layout can be made more clean and easy to read if spacing/padding between elements is improved.

I would like to work on these. Could you assign this to me @akshitagupta15june?

**Comment by akshitagupta15june** [comment]
some are working on this
