### ISSUE TITLE
gifs unfit in "divine activities for all" section

### ISSUE THREAD

**Issue by piwuxk** [akshitagupta15june/Moksh#286]
hello ma'am
i found issue in "divine activities for all" section that all gifs all not visible in ui because of the size and poor alignment of gifs. ss attached-

 please assign me this issue! i would love to fix this issue in this wonderful project!

![Screenshot 2023-05-22 193742](https://github.com/akshitagupta15june/Moksh/assets/131276821/b6421da8-9bdf-4608-bb1f-83c971682772)

**Comment by akshitagupta15june** [comment]
some are working on this
