### ISSUE TITLE
hover effect issue in dropdown menu of feature in different pages 

### ISSUE THREAD

**Issue by piwuxk** [akshitagupta15june/Moksh#288]
i found issue in your site that there is different layout and hover effects for drop down menu of "feature" for different pages. ss attached-
i would love to apply same properties to "features" across your whole site to give it more genuine ui. kindle assign me this issue, i'll be responsible for it.

![image](https://github.com/akshitagupta15june/Moksh/assets/131276821/fea8fa2d-9dd4-42a8-90ce-82c36659c52a)
 
![image](https://github.com/akshitagupta15june/Moksh/assets/131276821/bb9d1301-2359-4d17-b986-175d0c7e47d2)

![image](https://github.com/akshitagupta15june/Moksh/assets/131276821/79675a2d-3daa-4c65-b012-494c03b3cb7a)

**Comment by akshitagupta15june** [comment]
some are working on this
