### ISSUE TITLE
Update footer section in the 'Read a shloka' page

### ISSUE THREAD

**Issue by piwuxk** [akshitagupta15june/Moksh#290]
The footer section of the page is experiencing a spacing issue, with inadequate spacing between the elements. This affects the overall visual appearance and user experience of the website.

please assign me this issue! i would be able to fix this!

![Screenshot 2023-05-22 201123](https://github.com/akshitagupta15june/Moksh/assets/131276821/ca666656-d2c8-4f49-9dfd-f679fa5b655c)

**Comment by akshitagupta15june** [comment]
some are working on this
