### ISSUE TITLE
Disalignment between 'New quote'  button and twitter logo in the 'Read a shloka' page

### ISSUE THREAD

**Issue by piwuxk** [akshitagupta15june/Moksh#291]
There's a disalignment between 'New quote'  button and twitter logo in the 'Read a shloka' page. This affects the overall visual appearance and user experience of the website.

Please asign me this issue I would be able to fix this!

![image](https://github.com/akshitagupta15june/Moksh/assets/131276821/8d1e238c-eb67-4272-b4d6-154082b90598)

**Comment by karthiknadar1204** [comment]
@piwuxk This issue has already been assigned  refer #203 
Please explore other issues to contribute to.
Feel free to raise more issues, we will review them and assign it to you
Thank you
