### ISSUE TITLE
[GSSOC'23] Restructuring the project

### ISSUE THREAD

**Issue by Vidhish-Trivedi** [akshitagupta15june/Moksh#294]
## Issue: Restructuring the project
- As of now, the project is not well-structured, all code files are in the project root.
- Restructuring the project into multiple meaningful directories would lead to ease in maintenance and contributions.

**Screenshots:**
- For example,
![image](https://github.com/akshitagupta15june/Moksh/assets/96025781/f03eae0a-f7c0-4e9c-92c7-b8fcd5cb321c)

**Expected:**
- Ideally, the CSS files should be grouped into a single directory. Similarly, the HTML and other files should too.

**Actual:**
- A lot of files are currently in the project root, which would make the project difficult to maintain as it grows.

**Additional Details:**
This issue has been opened as part of GSSOC'23

**Comment by Vidhish-Trivedi** [comment]
@akshitagupta15june I would like to work on this as part of GSSOC'23, please assign it to me.

**Comment by karthiknadar1204** [comment]
@Vidhish-Trivedi This issue is already under progress refer #154 
Please explore other issues to contribute to.
Feel free to raise more issues, we will review them and assign those issues.
Thank you

**Comment by Vidhish-Trivedi** [comment]
Sure, thanks @karthiknadar1204
