### ISSUE TITLE
Updating content on the  "Divine activities for all generation" page

### ISSUE THREAD

**Issue by Shikha954** [akshitagupta15june/Moksh#298]
I want to add different Asanas in it along with pictures or youtube videos.

**Comment by karthiknadar1204** [comment]
@Shikha954 
  Could you please elaborate what content do you wish to add.

**Comment by Shikha954** [comment]
@karthiknadar1204, I want to add  different Asanas in it along with pictures or youtube videos

**Comment by Shikha954** [comment]
@akshitagupta15june ma'am,Please assign this issue to me. I will contribute to this issue under GSSoC'23

**Comment by karthiknadar1204** [comment]
That sounds good @Shikha954 ,please wait for @akshitagupta15june to assign this issue to you.
Thank you

**Comment by Shikha954** [comment]
@akshitagupta15june ma'am please assign me this issue

**Comment by Rakesh9100** [comment]
Assigned @Shikha954 Proceed

**Comment by Shikha954** [comment]
@Rakesh9100 thank you sir for this opportunity.
