### ISSUE TITLE
To resolve the horizontal overflow of the webpage

### ISSUE THREAD

**Issue by DhairyaMajmudar** [akshitagupta15june/Moksh#299]
The website is having an issue with horizontal overflow 

I can solve this issue by adding the required CSS and HTML code 
![Screenshot 2023-05-22 221912](https://github.com/akshitagupta15june/Moksh/assets/124715224/44234bdf-9d80-4cb1-b382-02b3b9bba06b)

![Screenshot 2023-05-22 221929](https://github.com/akshitagupta15june/Moksh/assets/124715224/887b4e22-b74d-4d2f-bb54-bea2412bb9b2)

**Comment by DhairyaMajmudar** [comment]
Please assign me this issue
/assign

**Comment by akshitagupta15june** [comment]
some are working on it
