### ISSUE TITLE
To improve alignment of Read a Shlok Page

### ISSUE THREAD

**Issue by DhairyaMajmudar** [akshitagupta15june/Moksh#302]
To properly align the content of the Read a Shlok page using the necessary code of HTML and CSS 
![Screenshot 2023-05-22 224345](https://github.com/akshitagupta15june/Moksh/assets/124715224/543781bf-a400-4674-bead-6067c5721cc9)

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me. I will contribute to this issue under GSSoC'23

**Comment by akshitagupta15june** [comment]
go for it

**Comment by DhairyaMajmudar** [comment]
Thank to for assigning. Happy to contribute

**Comment by ritik48** [comment]
Hey @DhairyaMajmudar , 
Are you still working on it ?

**Comment by DhairyaMajmudar** [comment]
No @akshitagupta15june I have sent the pr and that pr is also merged with the codebase.
