### ISSUE TITLE
Issue : The Start, Reset and timer elements are very closely attached to each other in Pomodoro Page

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/Moksh#304]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

In Pomodoro Page, the start button, Timer, and reset button are very closely attached to each other, it doesn't seem good. Can I work on this issue under GSSOC '22 

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/89779447/e8465187-b492-42f8-a600-fc85ab1354fb)

**Comment by akshitagupta15june** [comment]
its not required
