### ISSUE TITLE
Divine Activities for All Generation component is not working properly.

### ISSUE THREAD

**Issue by heyhimansh** [akshitagupta15june/Moksh#305]
Hey @akshitagupta15june , I think your Divine Activities for All Generation component is not working properly.I can make it fully responsive with good interface .

[Link](https://akshitagupta15june.github.io/Moksh/story.html)

![Inbox (5,927) - himanshu_co21a4_27@dtu ac in - Delhi Technological University Mail and 119 more pages - Personal 2 - Microsoft​ Edge 22-05-2023 22_54_41 (2)](https://github.com/akshitagupta15june/Moksh/assets/72097380/b377b3b8-75a4-443f-8776-3af76c9cd324)

I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023

**Comment by akshitagupta15june** [comment]
some are working on it
