### ISSUE TITLE
Issue: Updating contribution.md with steps to contribute

### ISSUE THREAD

**Issue by mohammadshaad** [akshitagupta15june/Moksh#306]
## Description:
Currently, the contribution.md file in the repository does not provide clear instructions on how to contribute to the project. This lack of guidance can be a barrier for potential contributors who are interested in getting involved. This issue aims to improve the contribution.md file by adding comprehensive and easy-to-follow steps for contributing to the project.

## Proposed Changes:
The contribution.md file should be updated with the following steps to contribute:

1. Fork the repository to your own GitHub account.
2. Clone the forked repository to your local machine.
3. Create a new branch for your changes.
4. Make the necessary changes or additions to the codebase.
5. Commit your changes with a descriptive commit message.
6. Push the changes to your forked repository.
7. Submit a pull request from your forked repository to the original repository.
8. Provide a clear and concise description of your changes in the pull request.
9. Engage in any follow-up discussions or address any feedback received during the review process.
10. Once approved, your changes will be merged into the main branch of the project.

## Expected Outcome:
By updating the contribution.md file with these clear and comprehensive steps, we aim to provide a more welcoming and inclusive environment for potential contributors. This will encourage more community involvement and facilitate a smoother contribution process.

I am a GSSoC'23 contributor and I really want to work on this issue. Kindly assign me this issue.

**Comment by mohammadshaad** [comment]
@akshitagupta15june

**Comment by akshitagupta15june** [comment]
already added
