### ISSUE TITLE
Glass morphism effect in Iskon Event Page Cards

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/Moksh#307]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
The Cards present on Iskcon Events Page have only box-shadow property, they can also have Blur property so that it can have a glass like effect. 

**Before:**
![image](https://github.com/akshitagupta15june/Moksh/assets/89779447/0e969cef-62e4-4b07-85f6-1e844036d064)

**After:**
![image](https://github.com/akshitagupta15june/Moksh/assets/89779447/46c6c935-cd9d-4b64-bdb4-b2ffba581d8e)

**Comment by GleanCoder** [comment]
hello  Can you assign me this section I think the text alignment  and Buttons are not  looking attractive , I think the Cards can be better and I would like to work on it.

**Comment by MohitNamdev22** [comment]
@akshitagupta15june Can I work on this?
