### ISSUE TITLE
About not working in Quick links

### ISSUE THREAD

**Issue by Killer2OP** [akshitagupta15june/Moksh#310]
**Details**

The about in the quick link section in Iskcon Events is not working. 
As it is not redirecting us to the about section of the main page.
I can resolve this issue.
Assign me this under GSSoC'23

**Screenshot**

![image](https://github.com/akshitagupta15june/Moksh/assets/111378171/8347e3f1-a8aa-4b42-af9b-606298730fe4)

**Comment by akshitagupta15june** [comment]
its not required
