### ISSUE TITLE
Issue/Suggestion: Making website's navbar responsive

### ISSUE THREAD

**Issue by Akanksha-202** [akshitagupta15june/Moksh#316]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:** 
Readjustment of navbar for it to fit into the mobile view as well along with a hamburger option(fa-bars) for enhancing user experience.

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/100708686/6c5e1f5a-7bac-4c18-8f3b-302f9c22724a)

**Expected:**
When clicked over the hamburger option the navbar will slide from right to left (will take 1/4 size of the screen)

**Actual:**
Random placement of the navbar in mobile view also hinders the content on the landing page.
![image](https://github.com/akshitagupta15june/Moksh/assets/100708686/1816213f-dd9f-412d-b2f4-6e92b2fc9a4b)

Please assign this issue to me under GSSoC'23  label

**Comment by Akanksha-202** [comment]
None of the issues are of this type

**Comment by marshadkhn** [comment]
#164 
#215 
Check the above issue, hope you get!

**Comment by Akanksha-202** [comment]
Thankyou !
Must have missed

**Comment by karthiknadar1204** [comment]
Please close this issue @Akanksha-202 .
Thank you
