### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by Sandeep0306** [akshitagupta15june/Moksh#326]
HIi, I want to add scroll to top Button which will become easy for user's to navigate to top of the page . Please assign me this issue under GSSOC'23.

**Comment by sirajlekhak** [comment]
I am eager to contribute as a valuable team member and demonstrate my skills in GSSoC'23. If you would kindly assign me an issue, I would be delighted to work on it and showcase my abilities effectively within the program.
