### ISSUE TITLE
Add steps in wrist and finger stretch ui is not good

### ISSUE THREAD

**Issue by Shrejal123** [akshitagupta15june/Moksh#328]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**
![moksh1](https://github.com/akshitagupta15june/Moksh/assets/114261409/5b8e998a-9496-4c6e-b4b3-53ceb82553c1)

**Expected:**
I wants to add steps involve in wrist and finger stretch  performing yoga on chair.
**Actual:**

**Additional Details:**
Please assign this issue under gssoc23.

**Comment by riyaVerma1726** [comment]
In the yoga section there are very less yoga asanas mentioned while many more can be added. We can make this part very informative by adding all the necessary asanas their steps and their advantages. Moreover the this page requires some changes on UI and responsiveness.

PROPOSED SOLUTION -
1. We can make separate div for Sitting asanas, Standing asanas, Pranayam, Kapalbhati, Suryanamskar.
2. We can add Advantages of each asana along with the steps to make it easier for the user to select a particular asana for them.
3. 
![image](https://github.com/akshitagupta15june/Moksh/assets/114503561/cbe69813-4311-484c-9411-dd6aff5b8207)
This part require center alignment and some addition.

kindly assign me this issue, I have a good knowledge of yoga asanas and I have previously worked on such project.
@akshitagupta15june

**Comment by karthiknadar1204** [comment]
@Shrejal123 Those are images taken directly from google so might not be feasible to add additional steps for the same.
@riyaVerma1726 The points seem to be good, please raise a issue for the same, will review it and assign it.
Thank you

**Comment by riyaVerma1726** [comment]
sure sir

**Comment by riyaVerma1726** [comment]
I have raised the issue #343.
Kindly assign me the same.
Thankyou.
