### ISSUE TITLE
Ui is not looking good due to margin and padding

### ISSUE THREAD

**Issue by Shrejal123** [akshitagupta15june/Moksh#329]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
I wants to add margin and padding in footer section of this page .
**Screenshots:**
![moksh2](https://github.com/akshitagupta15june/Moksh/assets/114261409/bf23dcd7-4678-4e5f-a622-655f714077d5)

**Expected:**

**Actual:**

**Additional Details:**
Please assign this issue under gssoc23

**Comment by akshitagupta15june** [comment]
its not required
