### ISSUE TITLE
Improving Navbar's Responsiveness and Padding

### ISSUE THREAD

**Issue by KhushiVaiskyar** [akshitagupta15june/Moksh#333]
**Screenshots:**
![Screenshot (1)](https://github.com/akshitagupta15june/Moksh/assets/132345782/0e17a516-311f-45c0-b5b0-8af5aaabe11f)

The navbar needs more padding from the sides and has responsiveness issues. Kindly assign this issue to me.

**Additional Details:**
I'm in GSSoC'23.

**Comment by mnik7044** [comment]
Hey @KhushiVaiskyar  a lot of people already raised issue related to Navbar and many are getting assigned. I would want you to go find some other issue and write proper description of the issue and how u will proceed with that issue.

**Comment by mnik7044** [comment]
Hey @akshitagupta15june close this issue as one of duplicate issue.
