### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by munish-on-git** [akshitagupta15june/Moksh#334]
Adding react and react-dom to render the UI components and react-bootstrap for styling and overall experience as I think the Moksh is more about user experience. Using basic html and Vanila js make the project structure confusing and ineffcient. So converting it to use react will help a lot.

I really like the concept of this project and have some really good concept to add, so in order to do that I'm suggesting the above think.

So @akshitagupta15june please give your thought about it (In brief). And also something you particularly want to add.
And assign me this. I'm GSSOC contributor.

**Comment by ankitjt** [comment]
We are keeping the project beginner friendly and for the time being will not migrate to react. 

@akshitagupta15june to close.

**Comment by munish-on-git** [comment]
React is  beginner friendly its just Javascript, instead of making so Many file in project which is totally unstructured and using js to render blogs is not efficient react will save these major issue. As by the time Moksh user experience which at last matters. 
<img width="1348" alt="Screenshot 2023-05-23 at 12 11 51 PM" src="https://github.com/akshitagupta15june/Moksh/assets/110280635/bd8b44ad-1fc6-48b3-9203-1063922a8bf8">
Using template literals for writing long html is highly uneffective.
