### ISSUE TITLE
embed the video in website index page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#337]
https://youtu.be/BEsKgEGRjYU
please embed this video in index.html below mental problems

**Comment by NisargPipaliya** [comment]
I can do that.
Can you please assign me that?

**Comment by VardaPanchal005** [comment]
I 've worked on this type of project before too. Can you assign this issue to me?

**Comment by Veena4512** [comment]
Hello @akshitagupta15june , can I work on this issue please?

**Comment by anand2025** [comment]
Hello @akshitagupta15june ma'am, can I please work on this

**Comment by Sumit-pd** [comment]
i would like to work on this issue! @akshitagupta15june

**Comment by ABiiitH** [comment]
Hey , It would be great if you could _**assign me this issue**_ as I am familiar with the technology used. I am contributing under **GSSoC'23.**
It would be great to hear from you soon!

**Comment by akshitagupta15june** [comment]
completed
