### ISSUE TITLE
UI IMPROVEMENT IN NAVIGATION BAR

### ISSUE THREAD

**Issue by marshadkhn** [akshitagupta15june/Moksh#338]
### UI IMPROVEMENT
Hello @akshitagupta15june  and @karthiknadar1204. I go through the *MOKSH* and saw a issue not the major one but the one that should be fixed soon. It is a UI improvement in navigation bar `HOME PAGE`. The hover of each element is black underline which is not looking good at all, instead it should be white as it matches the environment of navigation bar 

**Expected:**
![Screenshot 2023-05-23 124555](https://github.com/akshitagupta15june/Moksh/assets/80325579/27f018d8-c5ce-4c28-af96-79c8cd145f39)

**Actual:**
![Screenshot 2023-05-23 004655](https://github.com/akshitagupta15june/Moksh/assets/80325579/7a021085-b329-41cf-8e32-0b1482321e2f)

**Additional Details:**
You can check the difference between the above photos. I did all the changes and waiting for you to assign me this issue so that I can push it to code base
My branch name - marshadkhn

**Assign me this issue** @akshitagupta15june

**Comment by shubhisingh184** [comment]
Please assign this task to me. I would like to improve the whole navbar including the drop down list and hover effects on the buttons

**Comment by mnik7044** [comment]
Hey @marshadkhn  I really liked the way you explained the issue but the issue regarding the Navbar is already assigned and people are working on it I will suggest you to close this issue and find some other issues to work on.

**Comment by mnik7044** [comment]
And one more thing @marshadkhn   It's highly recommended to not start working on issues till you get assigned.

**Comment by marshadkhn** [comment]
@mnik7044 I appreciate your effort but the navbar issue is assigned is for overflow the elements #215, none of any person is working in the hover effect
For assigning the issue you have to open the issue first hope you get

**Comment by marshadkhn** [comment]
@shubhisingh184 raise a issue

**Comment by mnik7044** [comment]
@akshitagupta15june Please close this issue as it is a duplicate.
