### ISSUE TITLE
Issue/Suggestion: [GSSoc'23] Alignment and UI of the exercises to do at desk

### ISSUE THREAD

**Issue by nishita2104** [akshitagupta15june/Moksh#348]
**Issue and Steps to Reproduce:**
The images in the below mentioned screenshot go beyond the website's width and are unreachable. 
**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/98174888/1ec62ce5-9993-4365-bc73-570b9f5c87a4)

**Expected:**
All the images should be visible.
**Actual:**
Only 2 are fully visible.
**Additional Details:**
I can fix this. Please assign it to me under GSSoC'23

**Comment by akshitagupta15june** [comment]
improved
