### ISSUE TITLE
Issue: [GSSoC'23] Improving the Pomodoro Feature

### ISSUE THREAD

**Issue by nishita2104** [akshitagupta15june/Moksh#349]
**Issue and Steps to Reproduce:**
In the pomodoro feature, there are no options to select 25 mins or 5 mins or 30 mins. Due to this, if timer is paused and reset before the completion of the set timer, it glitches and fixes on the 5 min timer only. 
**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/98174888/b9e1b2d2-7cce-45e8-9e90-5e1d2ef4f695)

After Reset:
![image](https://github.com/akshitagupta15june/Moksh/assets/98174888/12f6f0b7-f2f6-4f94-b77e-c65ba11929bf)

**Expected:**
We should have options of 25 mins, 5 mins or 30 mins so as to control the time of the breaks.
**Actual:**
The timer resets to 5 mins only. 
**Additional Details:**
Please assign this to me under GSSoC'23.

**Comment by akshitagupta15june** [comment]
improved recently
