### ISSUE TITLE
Issue/Suggestion: Can improve the landing page 

### ISSUE THREAD

**Issue by AditiSingh2003** [akshitagupta15june/Moksh#351]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by ankitjt** [comment]
@AditiSingh2003 You have not mentioned anything in your issues , pl update the same.
