### ISSUE TITLE
[Feat]: Add audio control bar in meditation.html

### ISSUE THREAD

**Issue by harmeetsingh11** [akshitagupta15june/Moksh#352]
## Description
In [Augmented Reality Meditation page](https://akshitagupta15june.github.io/Moksh/meditation.html), their are different music listed with play button. When the user clicks on play button, the particular music name disappears and displays a pause button. Additionally, when the user plays more than one music, all music plays simultaneously.
 
**Steps to Reproduce:**
1. I can add an audio control bar with play/pause button, volume control, time progress bar.
2. To prevent playing more than one music at the same time, I will add a javascript function which will make sure to play one music at a time.  

**Screenshots:**

**Current Behavior**

[current.webm](https://github.com/akshitagupta15june/Moksh/assets/130365071/d12e5f9d-bf0f-4e76-9a0d-4330955aac06)

## Program In which I am contributing
Girlscript Summer of Code 2023 (GSSoC'23)

## Code of Conduct
- [x] I follow [CODE OF CONDUCT](https://github.com/akshitagupta15june/Moksh/blob/main/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/akshitagupta15june/Moksh/blob/main/Contributing.md) of this project.

Please assign me this issue under GSSoC'23.
Thanks

**Comment by akshitagupta15june** [comment]
its been improved recently
thanks
