### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SrishtiSonam** [akshitagupta15june/Moksh#353]
Improving responsiveness and display of navbar.

The navbar is not responsive as well as div blocks are not even spaced properly.
This issue can be solved by using flexbox and improving some css.

**Screenshots:**
<img width="478" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/113123593/c55e9b18-bd7d-44c1-8eff-6f3de566dad1">
<img width="952" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/113123593/574e34ee-f15b-41c7-b7f1-96a0b13d194c">

**Expected:**
improving the navbar look to something like this..
<img width="671" alt="image" src="https://github.com/akshitagupta15june/Moksh/assets/113123593/e7c937e2-e198-458a-8e96-a5a28f60ad27">

**Actual:**

**Additional Details:**
assign this issue to me under GSSOC'23.

**Comment by SrishtiSonam** [comment]
The issue raised was found on the main front page's navbar.
[image: image.png]

**Comment by akshitagupta15june** [comment]
its not required
