### ISSUE TITLE
Adding Pre loader page [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [akshitagupta15june/Moksh#354]
Adding a pre loader page feature can improve the attractiveness and give fun to the website.
If this feature is needed do assign it to me under GSSOC 2023 .  :)

## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by akshitagupta15june** [comment]
its not required
