### ISSUE TITLE
Black underline on hover under the home and features tag of the nav bar instead of navbar of home page

### ISSUE THREAD

**Issue by Sumit-pd** [akshitagupta15june/Moksh#368]
## Black underline on hover under the home and features tag of the nav bar instead of navbar of home page##

**Issue and Steps to Reproduce:**
- go to http://127.0.0.1:5500/index.html
- hover over home and features tag of the navbar
- see the issue

**Screenshots:**

![Screenshot from 2023-05-23 22-06-04](https://github.com/akshitagupta15june/Moksh/assets/88550925/94aa82cb-969e-4e83-8ca6-ffc248214679)

**Expected:** the under line should be in white color

**Actual:**

**Additional Details:**
@akshitagupta15june i would like to work on this issue under gssoc!

**Comment by mnik7044** [comment]
Hey @Sumit-pd the issue related to the navbar is already assigned and people are working on it.

**Comment by mnik7044** [comment]
I would like you to close this issue and go find some other issues to work on, @Sumit-pd

**Comment by Sumit-pd** [comment]
hey @mnik7044 can you pin the issue that you are talking about?

**Comment by Hritik1503** [comment]
@akshitagupta15june i would like to work on this issue under gssoc!
