### ISSUE TITLE
Request to Add Issue Templates: Bug Report, Feature Request, and Styling

### ISSUE THREAD

**Issue by mhdamaan79** [akshitagupta15june/Moksh#372]
I propose adding three important templates to our project: **Bug Report, Feature Request, and Styling.** Including these templates will make project management and collaboration easier by providing standardized formats for reporting bugs, suggesting new features, and addressing styling issues. This will help us communicate more efficiently, keep track of problems effectively, and ensure consistency in our development and design processes.

I would like to work on this issue under the **GSSoC'23.** @akshitagupta15june

**Comment by akshitagupta15june** [comment]
go for it

**Comment by mhdamaan79** [comment]
I've raised a PR. Please review it and kindly add the **gssoc23 level** for this PR. Thank you! @akshitagupta15june
