### ISSUE TITLE
[UI]: Improve UI of Shlok on motivation.html page

### ISSUE THREAD

**Issue by harmeetsingh11** [akshitagupta15june/Moksh#373]
## Description
I can improve the UI of the Shlok on the [Read a Shlok](https://akshitagupta15june.github.io/Moksh/motivation.html)

**Steps to Reproduce:**

1. Add a box around Shlok and make it more eye-catching by styling.

**Screenshots:**
![shlok](https://github.com/akshitagupta15june/Moksh/assets/130365071/b17eb46d-41b0-40d5-ad9d-84f05ec6efa6)

## Program In which I am contributing
Girlscript Summer of Code 2023 (GSSoC'23)

## Code of Conduct
 - [x] I follow [CODE OF CONDUCT](https://github.com/akshitagupta15june/Moksh/blob/main/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/akshitagupta15june/Moksh/blob/main/Contributing.md) of this project.

Please assign me this issue under GSSoC'23.
Thanks

**Comment by mnik7044** [comment]
Hey @harmeetsingh11 if you have any suggestions regarding UI you can join our discord channel and after a proper discussion, u will be assigned.
You can also share, the expected behavior.

**Comment by harmeetsingh11** [comment]
yeah sure @mnik7044 . It would look something like this.

![proposed changes](https://github.com/akshitagupta15june/Moksh/assets/130365071/b14ba6a7-60b2-4277-9ffc-2f0901e01cdb)

Please assign me this issue under GSSoC'23.
Thanks

**Comment by mnik7044** [comment]
We are working on the folder structure right know @harmeetsingh11 wait a bit and the admin will assign you, do share the screenshot with description in the respective discord channel.

**Comment by akshitagupta15june** [comment]
go for it also makesure that whatever content is there we can tweet that on clicking twitter button
