### ISSUE TITLE
To add copy button for copying Shlok in Random Shlok Generator

### ISSUE THREAD

**Issue by divyansh2212** [akshitagupta15june/Moksh#374]
Adding **copy** button for copying Shlok to clipboard in Random Shlok Generator. User can easily copy the generated quote using this feature.

Please assign me this issue as GSSOC 2023 contributor.

**Comment by mnik7044** [comment]
I think this is a good idea wait a bit till we finish structuring the folders and then @akshitagupta15june can assign it to you.

**Comment by Hritik1503** [comment]
I would like to fix it under gssoc'23, please assign me this issue.

**Comment by akshitagupta15june** [comment]
some contributors are working on it
