### ISSUE TITLE
Change text placement/alignment of footer section

### ISSUE THREAD

**Issue by rishitachail** [akshitagupta15june/Moksh#376]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**

![Divine activities for all Generation - Google Chrome 5_24_2023 1_16_34 AM](https://github.com/akshitagupta15june/Moksh/assets/108628119/ee6dcfca-4347-42ed-ab62-470d692365e2)

**Expected:**

![Divine activities for all Generation - Google Chrome 5_24_2023 1_23_50 AM](https://github.com/akshitagupta15june/Moksh/assets/108628119/f274a385-0b12-47c0-9dc4-47c3295fbd7b)

**Actual:**

**Additional Details:**
I would like to make changes in first image so that it looks like the second.
Kindly assign me the task under GSSOC'23

**Comment by karthiknadar1204** [comment]
Which page did you encounter this issue on @rishitachail

**Comment by rishitachail** [comment]
Expect the augmented reality meditation page ,every page has that issue.
Also I must inform you that ,none of the pages are mobile responsive except
the above mentioned page though they are already assigned.

**Comment by Hritik1503** [comment]
I would like to fix it under gssoc'23, please assign me this issue.

**Comment by akshitagupta15june** [comment]
some contributors are working on it and i will myself create issues for seprate pages
