### ISSUE TITLE
Add contact section in readme.md

### ISSUE THREAD

**Issue by rishitachail** [akshitagupta15june/Moksh#377]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
I would like to add social handles of project admin and maintainers so that contributors can connect with me easily.
Kindly assign me the task under GSSOC'23.
**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by akshitagupta15june** [comment]
not required
