### ISSUE TITLE
can add more content and blogs to the blog section

### ISSUE THREAD

**Issue by divy-asharma141** [akshitagupta15june/Moksh#383]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by ankitjt** [comment]
you can submit your content for review, if its accepted you can raise a new issue and @akshitagupta15june will merge.

For the time being we are closing the issue.

@akshitagupta15june to close.

**Comment by divy-asharma141** [comment]
ok i'll work on that

**Comment by divy-asharma141** [comment]
https://docs.google.com/document/d/1lFNB0WTMRvlLzO2eE6K9ELihsP4JwnzESfrzcBhk994/edit?usp=sharing
HERE IS THE CONTENT @ankitjt  @akshitagupta15june  PLEASE REVIEW

**Comment by akshitagupta15june** [comment]
actually the blog are added here have a proper source so thats why i am not accepting any random blogs
