### ISSUE TITLE
Remove browser console messages

### ISSUE THREAD

**Issue by Avinash905** [akshitagupta15june/Moksh#389]
**Issue Description:**
The console.log messages are shown on the browser of the https://akshitagupta15june.github.io/Moksh/reward.html page

**Screenshots:**
![Screenshot (434)](https://github.com/akshitagupta15june/Moksh/assets/56786344/777b0cf6-0b58-4636-ae43-dde3ae285bee)

**Expected:**
Remove the console.log messages

**Additional Details:**
Please assign me this issue under **GSSOC'23**

**Comment by Hritik1503** [comment]
Please assign me this issue under GSSOC'23

**Comment by akshitagupta15june** [comment]
its not required
thanks
