### ISSUE TITLE
Adding "Contact us" page

### ISSUE THREAD

**Issue by anirudhsalaria** [akshitagupta15june/Moksh#390]
"Contact us" page will add more value to your website, as the clients who are surfing your website will be able to contact you directly.
The "Contact us" page will contain your linkedin, twitter and a text message box using which clients can send you the message directly.
For the text box, I will be using formspree. You can generate your own formspree link and I will add it to the backend, after this you will directly receive all the messages of your clients.
Rest I assure that you will get a good user interface.

**Comment by Hritik1503** [comment]
I am a GSSoC'23 contributor, and I would like to work on this. Kindly assign it to me.

**Comment by akshitagupta15june** [comment]
not required
