### ISSUE TITLE
Correcting links

### ISSUE THREAD

**Issue by Deepanshu0703** [akshitagupta15june/Moksh#392]
**Issue and Steps to Reproduce:**
i want to correct few links because roues are not opening instead they are prsent in the file

**Screenshots:**
![Screenshot (18)](https://github.com/akshitagupta15june/Moksh/assets/114489502/9a08eb7a-b60c-4b36-ae93-559400e7bc35)

**Expected:**
It should show story.html as it is present here
![image](https://github.com/akshitagupta15june/Moksh/assets/114489502/21619fac-46a1-4520-bed3-a3b4dd782fff)

**Actual:**
not showing , showing 404 error

**Comment by Hritik1503** [comment]
I am a GSSoC'23 contributor, and I would like to work on this. Kindly assign it to me.

**Comment by mnik7044** [comment]
Hey @Hritik1503 the work on the path is being done by us and is in progress I will suggest you to go find other issue and raise it.

**Comment by mnik7044** [comment]
Please close this issue.

**Comment by Deepanshu0703** [comment]
Issue number @Hritik1503
