### ISSUE TITLE
Fixing for a responsive website

### ISSUE THREAD

**Issue by aasthagracy** [akshitagupta15june/Moksh#393]
@akshitagupta15june 
I want to make this a responsive website, please assign me this task.
![WhatsApp Image 2023-05-24 at 3 18 55 PM](https://github.com/akshitagupta15june/Moksh/assets/108082021/a672ff07-0957-4288-ac58-eff4e86fbaa5)

**Comment by Hritik1503** [comment]
I am a GSSoC'23 contributor, and I would like to work on this. Kindly assign it to me.

**Comment by akshitagupta15june** [comment]
its fine now
