### ISSUE TITLE
adding a bhajan's section in the page

### ISSUE THREAD

**Issue by Shikha954** [akshitagupta15june/Moksh#394]
I want to add a bhajan's section on the page that include different kind of bhajan's which will attract more user and they don't need to go to other site like spotify or youtube to listen it.

<img width="956" alt="Screenshot 2023-05-24 161835" src="https://github.com/akshitagupta15june/Moksh/assets/84771860/05ad41a9-f76a-43a1-af16-de97a6018cf9">

**Comment by akshitagupta15june** [comment]
its not required
