### ISSUE TITLE
improvisation of the index page

### ISSUE THREAD

**Issue by MetiUmashri** [akshitagupta15june/Moksh#395]
If we try to improve the starting index page that would be more appealing as well as include the spiritual aspects with sum catchy yet spiritual heading.
![image](https://github.com/akshitagupta15june/Moksh/assets/97387069/2990648b-8c2b-443c-9f3c-72090cb7d266)

**Comment by Hritik1503** [comment]
I am a GSSoC'23 contributor, and I would like to work on this. Kindly assign it to me.

**Comment by akshitagupta15june** [comment]
@MetiUmashri what changes u will can u join discord channel https://discord.com/invite/Jmc97prqjb and show your designs there

**Comment by akshitagupta15june** [comment]
I am very sorry @MetiUmashri actually at that time site was under construction restructuring, Let me assure you and will assign u a issue myself
would you like to work on https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html improving the responsiveness?

**Comment by akshitagupta15june** [comment]
I will create a issue for the same and comment on that https://github.com/akshitagupta15june/Moksh/issues/501
