### ISSUE TITLE
Navbar Improvements

### ISSUE THREAD

**Issue by manaver** [akshitagupta15june/Moksh#398]
## Description:
The current navbar on the website requires some improvements to enhance its overall appearance and functionality. The following issues have been identified:

1. Underline and Bold Text:
The underline effect for the navbar links is not sufficient to highlight the active link. To improve visibility, the underline should be more pronounced and accompanied by bold text. This will ensure that users can easily identify the active link.

2. Alignment of Navbar Links:
The alignment of the navbar links appears to be disorganized and inconsistent. To enhance user experience, the links should be arranged in a more orderly and aligned manner. This will give the navbar a cleaner and more professional look.

3. Select Language Section:
The select language section in the navbar requires improvement. It is essential to provide a clear indication that allows users to change the language of the website. Consider adding a dropdown menu or an icon that signifies language selection. This will enhance the usability and accessibility of the website for users from different regions.

4. Responsive Design:
The navbar should be responsive to accommodate various screen sizes, including mobile devices and tablets. Currently, it may not adjust appropriately, leading to a poor user experience on smaller screens. Implementing a responsive design for the navbar will ensure that it remains functional and visually appealing across different devices.

### Proposed Solution:
To address these issues and improve the navbar:

1. Increase the thickness and visibility of the underline effect for active links. Additionally, apply a bold style to the text to make it stand out.

2. Adjust the alignment and organization of the navbar links for a cleaner and more professional appearance.

3. Improve the language selection section by adding a dropdown menu or an easily recognizable icon.

4. Implement a responsive design for the navbar to ensure it adapts well to different screen sizes.

Improvement Sections: 

![image](https://github.com/akshitagupta15june/Moksh/assets/78682260/103ce35c-0784-4e01-bc84-938d9e06983e)
![image](https://github.com/akshitagupta15june/Moksh/assets/78682260/ceca11cd-9a11-4252-a520-e34fa9dcbcd1)

**Comment by manaver** [comment]
Please assign this issue to me

**Comment by Moksh05** [comment]
I would like to fix the navbar on this page , Will align the buttons and the spacing between them. Which will for sure beautify this page 

please assign this task to me.

**Comment by akshitagupta15june** [comment]
its working fine now
