### ISSUE TITLE
Add a cool readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#4]

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by Sayan2k3** [comment]
hey @akshitagupta15june I would like to work on the issue and want to build a readme file . It would be great if you could assign me the issue under the program GSSOC'23

**Comment by ankitjt** [comment]
@Sayan2k3 did you submit your PR and is it merged ?pl update
