### ISSUE TITLE
Different questions in the bhagvad gita quiz.

### ISSUE THREAD

**Issue by tangorishi** [akshitagupta15june/Moksh#40]
If an user visits the website multiple times and they hop onto bhagwad gita quiz then , there can be seen repetititon of the questions asked every time on giving the quiz again same questions and that too in same order pops up , therefore there should be random questions every time giving the quiz 

![Screenshot (273)](https://user-images.githubusercontent.com/110519406/231003004-f34f0c15-f955-4821-b770-e75a2c5f34ab.png)

I can resolve this one on being assigned.

**Comment by akshitagupta15june** [comment]
ok

**Comment by ankitjt** [comment]
@tangorishi what is the status of this issue? Is it completed?, did you send a PR for the same?
