### ISSUE TITLE
[SUGGESTION] Add a line of explanantion when a wrong answer is given in the quiz. Link to learn more can also be added.

### ISSUE THREAD

**Issue by ivanMehvish** [akshitagupta15june/Moksh#403]
This will make quiz a little more informative. Kindly assign it to me for GSSoC'23, I'd love to work on it.
I will edit the basic HTML text, add a line about the correct answer and add hyperlinks to learn more.

**Comment by ivanMehvish** [comment]
I'll modify the index.html, questions.js and quiz.js add a new field in each question number object that'll have property having a line related to the answer of the question.
The information will be taken from vedabase [https://vedabase.io/en/]
ill create a new div for it.
Each time a wrong option will be selected, the innerHTML of  "info" div will be changed to the info property of the question object in questions.js file

**Comment by ivanMehvish** [comment]
![image](https://github.com/akshitagupta15june/Moksh/assets/87938552/9bd7ae64-3cb4-4292-97f5-aaf0afc226b7)

I will add info property in questions.js, for each question and it will look something like this.

**Comment by akshitagupta15june** [comment]
Why do you want to change index.html

**Comment by ivanMehvish** [comment]
> Why do you want to change index.html

Just a new div in the quiz box section whose innerHTML I'll change to accommodate the text and display it.
