### ISSUE TITLE
unresponsive buttons on homepage under 'moksh features' heading

### ISSUE THREAD

**Issue by trashw1n** [akshitagupta15june/Moksh#407]
**Issue and Steps to Reproduce:**
scroll down on homepage to see the boxes under the 'moksh features' heading;
try to open any feature except the augmented reality meditation feature;
**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/95612256/60a2846d-f9e1-4f25-9d98-72d9cf4bd0a8)

**Expected:**
respective pages to open
**Actual:**
404 message

**Comment by trashw1n** [comment]
@akshitagupta15june please assign this issue to me

**Comment by ankitjt** [comment]
Do a fresh fetch request and check again. All links are working.
