### ISSUE TITLE
[SUGGESTION] improve repetitive UI in the features dropdown in the navbar

### ISSUE THREAD

**Issue by trashw1n** [akshitagupta15june/Moksh#408]
**Issue and Steps to Reproduce:**
the features dropdown contains links which are available just one or two scrolls down the page.
It makes the UI unnecessarily repetitive. 
*the features dropdown should instead be a button which takes the user/scrolls to the features section.*

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/95612256/f1c9390a-da2b-41d1-936a-188d6a973d9a)

**Comment by trashw1n** [comment]
@akshitagupta15june please assign this issue to me under GSSOC'23

**Comment by karthiknadar1204** [comment]
@trashw1n Could you elaborate what are you trying to implement, can't comprehend what are you trying to do add here

**Comment by trashw1n** [comment]
@karthiknadar1204  the feature dropdown in navbar has links which are already available by scrolling down a bit which makes it redundant. Could make it a button instead which takes the user to the features sections on the page.
