### ISSUE TITLE
Issue: Navbar is not designed properly for small screen

### ISSUE THREAD

**Issue by bhaskarkumar1** [akshitagupta15june/Moksh#409]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
Please assign me this task to fix the navbar for small screen view as you can see in the screenshot attached below. I want to fix the navbar for small screen as a hamburger button.
**Screenshots:**
![navbar](https://github.com/akshitagupta15june/Moksh/assets/84345649/b1c18600-98d1-41ad-b838-34333c5df78d)

**Expected:**
Navbar was to be expected as a hamburger button

**Additional Details:**
Let me fix the css by adding some style to the media query

**Comment by akshitagupta15june** [comment]
its working fine 
check again
