### ISSUE TITLE
Implementing a better Navbar UI for Mobile screen device 

### ISSUE THREAD

**Issue by LadityaGogoi** [akshitagupta15june/Moksh#418]
### **Figma Design**
![6](https://github.com/akshitagupta15june/Moksh/assets/108052802/6ad640e4-4274-463a-a789-84c34a3c405e)

**I want to add this figma design to your website, which will give users mobile app like experience on your web**

**Please assign this issue to me, Under @GSSOC2023**

**Comment by ankitjt** [comment]
Navbar is responsive on mobile screens for some pages, although it'll be the same on all pages soon.
