### ISSUE TITLE
Want to add a FAQ Section in your Website

### ISSUE THREAD

**Issue by Lobi29** [akshitagupta15june/Moksh#419]
### **Figma Design**
![21](https://github.com/akshitagupta15june/Moksh/assets/108052802/93ffeef3-b4a9-4ab8-a30e-9dabc943a4b2)

**I want to add a FAQ section to your website, such that if somebody has any doubt then they can clarify in FAQ section.
If user need more help then, In FAQ section we will also have FAQ form through which they can communicate with us.**

**I am sure that this feature will give users, a better experience in the site.**

**Please assign this task to me, under @GSSOC2023**

**Comment by ankitjt** [comment]
@akshitagupta15june Good first issue

**Comment by Lobi29** [comment]
are you admin of this project !!! 

if yes then assign this task to me

**Comment by ankitjt** [comment]
Moderator !!!

**Comment by Lobi29** [comment]
Ohhh,
Can you assign me -> this task
Or I have to wait for admin ?

**Comment by RajeevDash007** [comment]
Assign me this issue under gssoc

**Comment by akshitagupta15june** [comment]
not required
