### ISSUE TITLE
no home tab in the nav bar!

### ISSUE THREAD

**Issue by Sumit-pd** [akshitagupta15june/Moksh#420]
**Issue and Steps to Reproduce:**
There is no home bar on the navbar

**Screenshots:**
![Screenshot from 2023-05-24 23-27-58](https://github.com/akshitagupta15june/Moksh/assets/88550925/3cf7a664-e6e2-44e6-9c2d-89ff6383b7fc)

**Additional Details:**
i would like to work on this issue

**Comment by ankitjt** [comment]
Refer @akshitagupta15june comment in the channel. 

@akshitagupta15june To close.

**Comment by RajeevDash007** [comment]
I would like to work on this issue
