### ISSUE TITLE
UI Update Login/Logout Function

### ISSUE THREAD

**Issue by AbhishekCS3459** [akshitagupta15june/Moksh#422]
<h1>Addition of login/logout page in the top right corner </h1>

Screenshots:

![image](https://github.com/akshitagupta15june/Moksh/assets/94506000/219212fc-7fbd-4919-ad17-ba31a46aef98)

Expected: User Profile Button for Login/Logout function

Actual: Change Language Button is Present

Kindly Assign this issue to me I can easily update it using google firebase .

**Comment by ankitjt** [comment]
As of now this functionality is not incorporated.
