### ISSUE TITLE
Issue/Suggestion: [GSSoc'23] Improving Footer Design

### ISSUE THREAD

**Issue by ShreyaDhiman24** [akshitagupta15june/Moksh#428]
I wanted to work on the design. Kindly, assign this issue to me under GSSoC'23.

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/98320971/0ddc5fe3-29d5-4e12-9cc9-26a9a7df8723)
![image](https://github.com/akshitagupta15june/Moksh/assets/98320971/828b64c7-f889-4e0b-bbe4-913e675b20e0)

**Comment by Mittalkashish** [comment]
mam i want to work on this issue, i will make ui better of footer  
![Screenshot from 2023-05-25 06-30-19](https://github.com/akshitagupta15june/Moksh/assets/103743582/3ad26787-6e96-4419-a74e-3df100dcb371)

**Comment by Mittalkashish** [comment]
mam i want to work on this issue . i will try to make footer  like this but not in black colour as it doesn't suit the website colour  
![Screenshot from 2023-05-25 06-30-19](https://github.com/akshitagupta15june/Moksh/assets/103743582/722e217d-f9f3-4008-af12-b76ac91de6bb)
![Screenshot from 2023-05-25 06-33-50](https://github.com/akshitagupta15june/Moksh/assets/103743582/8e1d22c3-b20e-429c-b076-3b0fc6432787)

**Comment by ShreyaDhiman24** [comment]
Can you please tell why till issue get closed as it is not done?
