### ISSUE TITLE
[BUG] Wrong link

### ISSUE THREAD

**Issue by Shalini469717** [akshitagupta15june/Moksh#429]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
Go to AR meditation page: https://akshitagupta15june.github.io/Moksh/AR_Meditate/meditation.html
Click on Moksh icon.

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/99305545/f2d0bb1a-2e0c-46db-bde5-1af06c2942eb)

**Expected:**
It should be redirected to https://akshitagupta15june.github.io/Moksh/index.html
But it is getting redirected to https://akshitagupta15june.github.io/Moksh/AR_Meditate/index.html

**Additional Details:**
Can you assign this to me under gssoc

**Comment by RajeevDash007** [comment]
Can you assign this to me under gssoc
