### ISSUE TITLE
Improvisation of index page 

### ISSUE THREAD

**Issue by MetiUmashri** [akshitagupta15june/Moksh#438]
The starting page could be made more appealing by adding few catchy yet spiritual related content.
Kindly assign this issue so as to make the initial page more appealing as well as responsive.

**Comment by karthiknadar1204** [comment]
hii @MetiUmashri What kind of contents do you wish to add to the index page

**Comment by MetiUmashri** [comment]
1. The vedio been inserted at the beginning is not in an appealing form hence would try to insert at the end probably
2. The pictures are unecessary so would try to give a peaceful aspect to the website rather than small pics
3. Trying to add a quote (spirituality related) which could be more appealing 
4. Google thing shown on right corner
![image](https://github.com/akshitagupta15june/Moksh/assets/97387069/67484cdb-c023-4efb-9d25-d354c1cf1d9d)

**Comment by akshitagupta15june** [comment]
some contributors are working on it
