### ISSUE TITLE
Adding a `Chat Bot` 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [akshitagupta15june/Moksh#439]
Hello Project Admin/Manager,
I will be happy to work with you, let's upgrade the website using the new industry 4.0

### Adding Chat Bot ~

**Soon will raise a `PR`**

**Comment by karthiknadar1204** [comment]
@SyedImtiyaz-1 Please wait for the issue to be assigned before raising a pr

**Comment by SyedImtiyaz-1** [comment]
@karthiknadar1204 okay

**Comment by akshitagupta15june** [comment]
not required currently
