### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iriteshmishra** [akshitagupta15june/Moksh#444]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
We can change from New Quote to New Sloka or New Verse. It will be good from my POV.
**Screenshots:**
![sss](https://github.com/akshitagupta15june/Moksh/assets/96378085/b9bc34ad-5fea-4a55-82a0-9686cf5b1b81)

**Expected:**
Change to new sloka or new verse whatever you like to keep.
**Actual:**
Null
**Additional Details:**
You can assign me if you like. We could talk more about this on discord.

**Comment by karthiknadar1204** [comment]
Hii @iriteshmishra , well  i think we could also add some additional styling to the button and "New Verse" sounds good to me.
Please wait for @akshitagupta15june to assign it to you.
Thank you

**Comment by akshitagupta15june** [comment]
some contributors are working on it

**Comment by iriteshmishra** [comment]
Is this issue completed @akshitagupta15june ?

**Comment by iriteshmishra** [comment]
Hi, is this issue is solved? Kindly verify once. @akshitagupta15june
