### ISSUE TITLE
iframe on the website is not responsive

### ISSUE THREAD

**Issue by sabhisharma-ise** [akshitagupta15june/Moksh#445]
**Issue and Steps to Reproduce:**
The iframe on the website is not responsive when viewed in a mobile device. This means that the iframe does not resize to fit the width of the mobile screen. 

**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/100849696/7881e448-c198-43f8-aacb-cbd02dbdff20)

**Expected:**
![image](https://github.com/akshitagupta15june/Moksh/assets/100849696/9baccffe-9a25-407b-a4d0-bda49308175f)

**Additional Details:**
Please assign this issue to me!

**Comment by akshitagupta15june** [comment]
it is now
