### ISSUE TITLE
[BUG] Text Overlapping in placards in Iskcon Events 

### ISSUE THREAD

**Issue by Anshika-Jain02** [akshitagupta15june/Moksh#452]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as a duplicate

**Issue and Steps to Reproduce:**
*The date and content are overlapping in the placard on the event.html page. we can resolve this issue by using margin and padding between two \<p> tags of date and content.*

**Screenshots:**
![moksh](https://github.com/akshitagupta15june/Moksh/assets/104912087/e87dd1b0-cc21-4dfe-a3fd-832faf5c85ca)

**Expected:**
*Nill*

**Actual:**
*Nill*

**Additional Details:**
*Please assign me this issue under Gssoc'23 @akshitagupta15june*

**Comment by akshitagupta15june** [comment]
some contributors are working on it
