### ISSUE TITLE
Suggestion : Improvement in Pomodoro Page

### ISSUE THREAD

**Issue by gayatriagarwal19** [akshitagupta15june/Moksh#453]
**Issue and Steps to Reproduce:** 
The navbar links are not centered
  The  timer buttons need improvement

**Screenshots:![pomodro page](https://github.com/akshitagupta15june/Moksh/assets/98116507/361cd551-ea7b-48b3-8181-b28f1dacf2f4)**

**Expected:**
nill

**Actual:**
nill

**Additional Details:**
Please assign me this issue under Gssoc'23 @akshitagupta15june

**Comment by akshitagupta15june** [comment]
some contributors are working on it
