### ISSUE TITLE
Suggestion for adding more questions and blogs of other spiritual books like Upanishads and Puranas.

### ISSUE THREAD

**Issue by swastika2108** [akshitagupta15june/Moksh#458]
I would like to make an initiative to include questions from other spiritual books such as the **Upanishads and Puranas**. It's important to provide a broader perspective and offer more spiritual resources to users. Additionally, incorporating additional shlokas and Sanskrit quotes will enhance the richness and diversity of the content, allowing people to explore different facets of spirituality.
Hey @akshitagupta15june requesting to add this feature!

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
