### ISSUE TITLE
Suggestion for adding Health Care Services

### ISSUE THREAD

**Issue by MetiUmashri** [akshitagupta15june/Moksh#459]
We can  add an another section of providing health care services. Wherein we can specify what kind of treatment been provided through ayurveda such as panchakarma treatment and so on...

**Comment by MetiUmashri** [comment]
Like adding
![image](https://github.com/akshitagupta15june/Moksh/assets/97387069/2098592c-1192-475c-90d3-48beec74f747)

something similar to this

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
