### ISSUE TITLE
Error in Augmented Reality Meditation Section

### ISSUE THREAD

**Issue by ayushkumarbhadani** [akshitagupta15june/Moksh#461]
<h3>Issue:</h3>
There is an error saying "You have used all your project's credits" when I opened the webpage after scanning the QR code at: https://akshitagupta15june.github.io/Moksh/AR_Meditate/meditation.html

<br/><br/>
<b>Screenshot: </b><br/>
<img src="https://github.com/akshitagupta15june/Moksh/assets/73775939/31bd7ea1-a645-46db-9082-f40c1569ea9c" height="300px"/>

**Comment by akshitagupta15june** [comment]
yes because it was on free plan i will see to it
