### ISSUE TITLE
Multiple audios are playing at the same time.

### ISSUE THREAD

**Issue by ayushkumarbhadani** [akshitagupta15june/Moksh#462]
<h2>Issue:</h2>
Multiple audios are playing at the same time.

Link to the page: https://akshitagupta15june.github.io/Moksh/AR_Meditate/meditation.html

https://github.com/akshitagupta15june/Moksh/assets/73775939/0d815d8d-2073-4f54-bed5-2baf15724ebe

<h2>Fix:</h2>
Audio playback can be controlled by Javascript to pause the previously played audio.

**Comment by ayushkumarbhadani** [comment]
I can solve this issue, Can you please assign this task to me?

**Comment by ankitjt** [comment]
@akshitagupta15june To assign

**Comment by akshitagupta15june** [comment]
go for it

**Comment by ayushkumarbhadani** [comment]
Thanks!

**Comment by ayushkumarbhadani** [comment]
Hey @akshitagupta15june, Kindly review it please.
