### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by vivekrawat21** [akshitagupta15june/Moksh#463]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

The ifame tag is not responsive 

**Expected:**
![Screenshot from 2023-05-25 22-03-28](https://github.com/akshitagupta15june/Moksh/assets/116631005/1af121f4-7d88-4cd8-8844-bca65f79cf23)

**Actual**
![Screenshot from 2023-05-25 22-01-44](https://github.com/akshitagupta15june/Moksh/assets/116631005/a2657f59-1d81-475d-b6ec-45d0e8019fea)

**Additional Details:**
For making a responsive site one should have to be reponse in every device

**Comment by akshitagupta15june** [comment]
someone is working on it

**Comment by vivekrawat21** [comment]
ohk
