### ISSUE TITLE
[GSSOC '23]: Enhancement of 'Back to Top' button at footer of every page from only index page

### ISSUE THREAD

**Issue by sujanrupu** [akshitagupta15june/Moksh#464]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
Adding a 'back to top' button at the footer part of every page.
**Screenshots:**
![testing](https://github.com/akshitagupta15june/Moksh/assets/103595490/6d398675-ed34-4347-b22f-7886885ef1fb)

**Expected:**

**Actual:**

**Additional Details:**

**Comment by sujanrupu** [comment]
@akshitagupta15june  Please assign me this issue

**Comment by sujanrupu** [comment]
@akshitagupta15june I want to **add 'Back to top' button at the footer of every page, not only the index page**, please assign me the issue under **GSSOC '23**.

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
