### ISSUE TITLE
{GSSOC'23} overlapping of text and images on Iskcon Events page

### ISSUE THREAD

**Issue by thekirti02** [akshitagupta15june/Moksh#467]
## {GSSOC'23}

**Screenshots:**
<img width="948" alt="moksh issue " src="https://github.com/akshitagupta15june/Moksh/assets/105008820/1b9b559c-31da-4fc2-8409-c2a9972c60a8">

<img width="943" alt="issue 1" src="https://github.com/akshitagupta15june/Moksh/assets/105008820/ff7df4ba-3b30-45a9-b5d1-3b7b205c2825">

**Issue and Steps to Reproduce:**
 I think there is a lot of overlapping of text; some text like "EVENT" is half hidden, and below it, dates and the event names overlap. 
There should be some changes in its UI, which I would like to improve. And I would like to ask you to assign this issue to me.

**Comment by karthiknadar1204** [comment]
Hii @thekirti02 This issue is already being worked on refer #76 , please explore other issues to contribute to.
Feel free to raise more issues, we will review them and assign it to you.
Thank you
