### ISSUE TITLE
{GSSOC 23} Wanted to improve design and fixing of overlapped text in ISKCON section

### ISSUE THREAD

**Issue by Utkers-h** [akshitagupta15june/Moksh#468]
The header of the iskcon page appears quite simple , and have poor alignment.. and color scheme.Also there are some overlapping text in EVENT section

![Screenshot (159)](https://github.com/akshitagupta15june/Moksh/assets/102818047/536f4a03-b2a8-49ef-9639-720cf62b7308)
![Screenshot (160)](https://github.com/akshitagupta15june/Moksh/assets/102818047/9d7d843e-3fc0-4cbe-a307-ebb084963d61)

hence, i request u to assign me this issue...

**Comment by karthiknadar1204** [comment]
Hii utkarsh, This issue has already been assigned refer #76 , please explore other issues to contribute to .
Feel free to raise more issues, we will review them and assign it to you

**Comment by Utkers-h** [comment]
Ok
