### ISSUE TITLE
clicking on the logo button when on blogs page "file not found" error occurs rather then the home page

### ISSUE THREAD

**Issue by Himanshu-Kumatiya** [akshitagupta15june/Moksh#473]
when the user is at blogs section and try to move to the home page on clicking the logo the "file not found" error occurs.
I can fix it, assign me this under GSSOC'23.

![Screenshot (102)](https://github.com/akshitagupta15june/Moksh/assets/88624005/e153045c-16f8-44b5-8e5e-a4e1deaf5ca5)

when clicked the  logo to navigate to home page
![Screenshot (103)](https://github.com/akshitagupta15june/Moksh/assets/88624005/0c09f868-714c-41f1-875c-1e0d114ede4b)

**Comment by karthiknadar1204** [comment]
It seems the path is incorrect on the logo.
@akshitagupta15june will assign it to you, once you are assigned, you can start working and raise a pr

**Comment by akshitagupta15june** [comment]
its working fine, check it again
