### ISSUE TITLE
Better realistic images for cards!

### ISSUE THREAD

**Issue by Shr-reny** [akshitagupta15june/Moksh#475]
We can add more realistic and contrast images for edgy look.

**Comment by karthiknadar1204** [comment]
Could you share the images you wish to add and also the page to which you want to make these changes @Shr-reny

**Comment by Shr-reny** [comment]
[https://drive.google.com/drive/folders/1SpUrCRfpVTVDJx7wYs_Cdnuh4zyc0ozc?usp=share_link]

You can find the images in this drive folder. I'll like to add them in the home page cards section.

**Comment by Shr-reny** [comment]
Thank you for assigning the issue. I've made the changes in PR #549.
