### ISSUE TITLE
Want to Add more Blogs

### ISSUE THREAD

**Issue by vk20july** [akshitagupta15june/Moksh#477]

**Comment by Eiman-Zulfiqar** [comment]
Hi, I do like to contribute. Assign me this task under label GSSoC23

**Comment by swastika2108** [comment]
Hey I would like to contribute either i am into bhagawad gita and other spiritual books also into content writer under Student Activity Center so I can create a good blog for the readers to gain knowledge. Please assign this task to me under label Gssoc
@akshitagupta15june.

**Comment by vk20july** [comment]
@akshitagupta15june sir can you please assign this issue to me
as i open this issue first time

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
