### ISSUE TITLE
Integrating Bhavad Gita API 

### ISSUE THREAD

**Issue by resonating-homesh** [akshitagupta15june/Moksh#478]
# Suggestion/New feature

## After exploring the website I felt we could integrate more user friendly features from Bhagvad Gita API. 
It is an opensource rest API on Vedic Scripture Shrimad Bhagavad Gita.

The features I propose to add are:
1) Readable Holy Bhagavad Gita with a summary for easy understanding of each shlok. 
2) Also, the existing feature can be of 'Read a Shlok' can be enhanced by integrating this api as it takes it sources from multiple recognized translations.

More details about API: https://bhagavadgitaapi.in/

More features are welcome!!

**Comment by resonating-homesh** [comment]
I can work on adding this feature. Can you please assign this task to me under the GSSOC'23 label?

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
