### ISSUE TITLE
lack of incorrect options to 2nd question of bhagwat gita quiz

### ISSUE THREAD

**Issue by Sumit-pd** [akshitagupta15june/Moksh#484]
**Screenshots:**
![Screenshot from 2023-05-26 14-50-30](https://github.com/akshitagupta15june/Moksh/assets/88550925/afca3a97-78ad-413d-aff1-f362871a215d)
**Expected:**
the question says to identify the non Pandav , ideally , here should be names of three Pandavs and one non Pandav so the answer will be unique

**Actual:**
but there are 3 non pandav options in the quiz

**Comment by Sumit-pd** [comment]
I would like to work on this issue under gssoc!

**Comment by akshitagupta15june** [comment]
yes go for it!
