### ISSUE TITLE
Issue/Suggestion : Increase in number of blogs

### ISSUE THREAD

**Issue by arpitaarora25** [akshitagupta15june/Moksh#485]
#477 Want to add more blogs 
It would be great if more writers are invited to contribute and shower their knowledge and thoughts. Young writers have new approach to handle these issues and thus prompt solutions for the same. 
![image](https://github.com/akshitagupta15june/Moksh/assets/133668393/b0929362-b940-4b00-b787-d87de51c63e2)

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
