### ISSUE TITLE
Issue/Suggestion Logo not visible properly

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#487]
**Issue and Steps to Reproduce:**
Logo is not visible properly on the (Power of Knowledge Blogs) Blogs page as a similar Logo shows consistency on webpages.

**Screenshots:**
<img width="220" alt="Screenshot 2023-05-26 171503" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/efaa8e32-c13b-4523-869d-5a7a09188e59">

**Expected:**
<img width="178" alt="Screenshot 2023-05-26 172043" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/42d0819a-e89e-4134-832f-fb126a32f093">

**Actual:**
NIL

**Additional Details:**
Please assign this to me under GSSoC'23. @akshitagupta15june

**Comment by akshitagupta15june** [comment]
go for it

**Comment by DivyanshiNarang** [comment]
Hello, @prathamesh-borse I am working on this issue and will require two more days as my semester exams are going on.
Sorry for the delay.
