### ISSUE TITLE
Rejuvenate videos overlaps on small screen [ GSSoC '23]

### ISSUE THREAD

**Issue by ritik48** [akshitagupta15june/Moksh#489]
**Issue and Steps to Reproduce:**
The 'inspirational videos' on the rejuvenate page, overlaps when viewed on small screen. And so it's difficult to play any particular videos.

**Screenshots:**
![moksh rejuventae overlap](https://github.com/akshitagupta15june/Moksh/assets/84488726/b8d17752-7436-4e8d-b219-c51c466fef84)

Please assign this issue to me so that I can work on this under GSSoC'23.

**Comment by akshitagupta15june** [comment]
go for it

**Comment by ritik48** [comment]
hey @akshitagupta15june , please review my pr #510
