### ISSUE TITLE
Add more sounds in Moksh/tree/main/sounds

### ISSUE THREAD

**Issue by guptafactory** [akshitagupta15june/Moksh#491]
**Issue and Steps to Reproduce:**
Want to add more song to the directory: Moksh/tree/main/sounds

**Screenshots:**
![Screenshot 2023-05-26 202641](https://github.com/akshitagupta15june/Moksh/assets/97209900/f6191573-d927-4ecb-b74e-eda221f875cf)

**Expected:**
Users can listen to multiple sounds and can help reduce stress.

**Actual:**
More music can then be added to Moksh/blob/main/AR_Meditate/meditation.html

**Additional Details:**
Kindly assign this task with GSsoc'23 label.

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
