### ISSUE TITLE
Adding Contact us option

### ISSUE THREAD

**Issue by Ujwala12327** [akshitagupta15june/Moksh#492]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

Issue: I have obsrved that there is no contact us option
 Steps to Reproduce:
Step1: I can add contact us where we can solve the doubts of user which is important to every new user

![Screenshot (26)](https://github.com/akshitagupta15june/Moksh/assets/114301056/1d60990d-1177-49ea-971e-dca581e84c68)
Screenshots:

Expected: No chance to contact anybody who gets doubt

Actual: Chance of getting contact if new user gets any doubt

Additional Details: I want to solve this issue

**Comment by akshitagupta15june** [comment]
hey its not needed currently in the website
Thankyou
