### ISSUE TITLE
the features section in footer section are not clearly visible when hovered[BUG] 

### ISSUE THREAD

**Issue by mridulsaggi** [akshitagupta15june/Moksh#497]
the features section in footer section are not clearly visible when hovered. please assign me this issue as i would like to contribute to this issue by improving the font color and hover effect of the links and features section for better user experience
example of the issue:
![image](https://github.com/akshitagupta15june/Moksh/assets/91930535/70ab92af-8e76-48ed-aa5a-a8114ce9affb)

**Comment by Rakesh9100** [comment]
Proceed @mridulsaggi
