### ISSUE TITLE
Improve the UI of main page index.html

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#5]

**Comment by karthiknadar1204** [comment]
can i work on this issue,i can reframe the main page along with the footer.
Please assign it to me

**Comment by akshitagupta15june** [comment]
ok

**Comment by karthiknadar1204** [comment]
The main page seems fine overall,will add a few changes necessary and submit pr for review today
Thank you

**Comment by karthiknadar1204** [comment]
@akshitagupta15june will submit pr for this by today evenung,Thank you
