### ISSUE TITLE
Contact us Form

### ISSUE THREAD

**Issue by Abhishek8287** [akshitagupta15june/Moksh#502]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.
A contact us page is a need for the website . It helps the user to give feedback to the website owner about any issue.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.
I want to add a contact us section in the website .

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.
![Screenshot (73)](https://github.com/akshitagupta15june/Moksh/assets/100223167/6d47cd2a-f0bc-49f9-84e3-ce8b1a2cc07f)

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).
Medium

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.
assign me this issue under GSSoC'23

**Comment by Rakesh9100** [comment]
Currently this feature is not needed in the website. Pls work on other issues.
