### ISSUE TITLE
Quick links of Event Page are not working.

### ISSUE THREAD

**Issue by harshraj005** [akshitagupta15june/Moksh#504]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
While checking the demo site, I found that the Links in the Quick link part of the Iskon Events page are not working.
**Screenshots:**
![image](https://github.com/akshitagupta15june/Moksh/assets/132002718/3d5ef3fc-5192-48fa-9f58-cc6020b9be73)
![image](https://github.com/akshitagupta15june/Moksh/assets/132002718/de0ac6cf-f5fa-433b-844d-e6397aef36c1)
**Expected:**
![image](https://github.com/akshitagupta15june/Moksh/assets/132002718/4c054b92-8c1c-45f2-a768-617d9137181c)

**Actual:**
![image](https://github.com/akshitagupta15june/Moksh/assets/132002718/de0ac6cf-f5fa-433b-844d-e6397aef36c1)
**Additional Details:**
I can solve this problem and I will be thankful if you assign this to me under GSSoC'23.

**Comment by Rakesh9100** [comment]
Start working @harshraj005

**Comment by Rakesh9100** [comment]
Same issue is already opened. Pls work on other new issues. @harshraj005
