### ISSUE TITLE
multiple audio played at once in ar mediate page

### ISSUE THREAD

**Issue by Sumit-pd** [akshitagupta15june/Moksh#517]
## Description

**Describe the bug:**
when you play a new audio while an audio is already playing. Then both the audio play simultanouly
**Expected behavior:**
when one audio is played the other should be paused!

**Actual behavior:**
multiple audio can be played at once causing a mess

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'http://127.0.0.1:5500/AR_Meditate/meditation.html'
2. play a audio
3. play another audio
4. both the audio is being played simultanously

## Screenshots

![Screenshot from 2023-05-27 11-03-45](https://github.com/akshitagupta15june/Moksh/assets/88550925/be216919-fd19-4c9b-a2c8-83639a277920)

## Additional Information

**Device (please complete the following information):**
- OS: Linux
- Browser :Chrome,
- Version : Ubuntu 22.04.1 LTS

**Comment by Sumit-pd** [comment]
I would like to work on this issue under gssoc!

**Comment by ayushkumarbhadani** [comment]
Hey @Sumit-pd, thanks for raising this issue but this issue is already raised previously and assigned to me. Have a look at issue #462

**Comment by Sumit-pd** [comment]
ok I will close this issue!
