### ISSUE TITLE
Issue/Suggestion Poor text contrast and visibility 

### ISSUE THREAD

**Issue by Pursottam6003** [akshitagupta15june/Moksh#529]
### Poor text contrast and visibility 

Hii @akshitagupta15june I have just cloned and forked the repository and found out the there were lots of sections where text contrast is not in a proper format 

![image](https://github.com/akshitagupta15june/Moksh/assets/81693090/6bf2c534-7e7f-4808-b4f6-c0ab9ee11716)

**Issue and Steps to Reproduce:**
1. Clone the repository and start the server
2. inspect the page and click on the arrow toggle button to select the element 
3. Select the element of the footer or any text with a background color 

**Screenshots:**

[Screencast from 27-05-23 01:23:35 PM IST.webm](https://github.com/akshitagupta15june/Moksh/assets/81693090/2aaaaa6f-8a96-406a-b4b7-803950e80d91)

What we can do to fix this issue?
1. Either we should change the layout and color of our page 
2. use of proper color contrast text and background colors with proper design 

**Expected:**
It should have good contrast and visibility 

**Actual:**

I would like to work on this issue  please assign me if possible ```GSSOC'23```  @akshitagupta15june 

**Additional Details:**

**Comment by akshitagupta15june** [comment]
contributors are working on creating a common footer for all pages
Thanks
