### ISSUE TITLE
[Issue/Suggestion] [GSSOC] Distance between elements are not perfect

### ISSUE THREAD

**Issue by AnanyaSDhar** [akshitagupta15june/Moksh#532]
**Issue and Steps to Reproduce:**
The distance between elements does not look perfect. I would like to correct them. Please assign under GSSOC'23 label.

**Screenshots:**

For example the top bar -->
How it looks:
![moksh wrong](https://github.com/akshitagupta15june/Moksh/assets/90474789/fd8574c5-d57f-409a-b339-5df37749144d)
How it should look:
![moksh right](https://github.com/akshitagupta15june/Moksh/assets/90474789/c155c7b0-0299-4b8d-bb36-53f963a4f641)

**Comment by aditya-stoic-sharma** [comment]
Hey @AnanyaSDhar  I would like to correct them. Please assign under GSSOC'23 label.

**Comment by Chandna-Soni** [comment]
Hey @AnanyaSDhar Please assign me this under GSSOC'23 label.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by ankitjt** [comment]
navbar was updated, pl do a fresh fetch to see the changes.
