### ISSUE TITLE
[STYLE CHANGE] The navbar hover effect looks little off

### ISSUE THREAD

**Issue by PoulavBhowmick03** [akshitagupta15june/Moksh#533]
**Description:**

On hovering over the elements in the navbar, a black underline appears, which doesn't look much pleasing. 
The logo on the Navbar and the logo text on the footer is unresponsive

**Reason for Change:**

The navbar hover would look quite good, instead of a black underline
The logo is unresponsive right now

**Proposed Styling:**

I would like to change that to something more soothing
Also, add the home page link to the logo in the top left navbar and the bottom footer

**Priority Level (optional):**

- [X] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

1 to 2 hours of being assigned

**Possible Implementation Approach (optional):**

Change the CSS pseudoclass styling for navbar and add a link to the logo for the navbar and for the footer

**Comment by PoulavBhowmick03** [comment]
@akshitagupta15june is this relevant to be assigned?

**Comment by mnik7044** [comment]
Navbar had a lot of issues in the past many are fixed and many are in the pipeline, i.e we are fixing it by ourselves, so I think it would be better for you to go find some other issues.

**Comment by mnik7044** [comment]
Hey  @PoulavBhowmick03 please close this issue and raise any other issue other than ux, if you are interested about the ux you can join the discord and have a discussion about it.

**Comment by PoulavBhowmick03** [comment]
Okay
