### ISSUE TITLE
[BUG] Glitch in Navbar in Mobile View

### ISSUE THREAD

**Issue by abhi03ruchi** [akshitagupta15june/Moksh#534]
## Description

**Describe the bug:**
There is a glitch in the navbar in the mobile view. 

- In mobile view, the navbar doesn't change to the close button on click. I want to fix this issue.
- Enhance the navbar UI in mobile view by adding a smooth transition effect.

**Current behaviour:**
A clear and concise description of what actually happened.

## Screenshots: 

https://github.com/akshitagupta15june/Moksh/assets/105661636/de722fac-5ac2-4c18-bf69-964cf3fb9725

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**
Please assign me this task under Gssoc'23.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by ankitjt** [comment]
Navbar is already updated, pl do a fresh fetch and check.
