### ISSUE TITLE
[STYLE CHANGE] Would like to update the card UI on the homepage

### ISSUE THREAD

**Issue by parag477** [akshitagupta15june/Moksh#536]
**Description:**

As I have seen that the UI of the card on the homepage is not that much attractive. So I thought of making it more attractive and beautiful.

**Reason for Change:**

Current styling is not looking that much attractive.

**Current Styling:**

Currently the card has simple styling which is not looking so good.

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

Please assign me this issue under GSSoC-2023

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by ankitjt** [comment]
homepage was updated, pl do a fresh fetch to see the changes.
