### ISSUE TITLE
All the links of image is broken

### ISSUE THREAD

**Issue by rohansx** [akshitagupta15june/Moksh#54]
All the links of image is broken in readme file

**Comment by harmeetsingh11** [comment]
Hello, Can I work on this issue?

**Comment by harmeetsingh11** [comment]
All the links of the images are broken when run locally. Please find attached screenshots for your reference.  
## Current Output
![current_output_1](https://user-images.githubusercontent.com/130365071/233395952-419fa808-47b4-4bac-b319-74b84b686314.PNG)
![current_output_2](https://user-images.githubusercontent.com/130365071/233395946-b258432f-0270-4bbc-94b9-e5b60bd3203c.PNG)

## Desired Output
![desired_output_1](https://user-images.githubusercontent.com/130365071/233396346-8ef0af47-1b4a-4c59-8d8c-3cba991263b5.PNG)
![desired_output_2](https://user-images.githubusercontent.com/130365071/233396322-2d73a3cb-cdd4-47bd-a18a-29b532fec744.PNG)

Can you reopen this issue and assign to me?
Thanks
