### ISSUE TITLE
[BUG] The Rejuvenate page has navigation problems

### ISSUE THREAD

**Issue by PoulavBhowmick03** [akshitagupta15june/Moksh#545]
## Description

**Describe the bug:**
The "Read a Shlok" and  "Pomodoro Spiritual Break" page is not opening from the Rejuvenate page
**Expected behavior:**
On clicking on the "Read a Shlok" and  "Pomodoro Spiritual Break" options in the feature, present on the Rejuvenate page, it should be redirected to those respective pages 

**Actual behavior:**
It is showing error 404 on clicking the "Read a Shlok" and  "Pomodoro Spiritual Break" 

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to https://akshitagupta15june.github.io/Moksh/Rejuvenate_page/rejuvenate.html
2. Click on 'Features'
3.  Click on 'Read a Shlok' or "Pomodoro Spiritual Break"

**Expected result:**
On clicking on the "Read a Shlok" and  "Pomodoro Spiritual Break" options in the feature, present on the Rejuvenate page, it should be redirected to those respective pages 
**Actual result:**
Error 404 is displayed

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/133862694/db978b40-2df6-4900-9535-20384aacc12a)

## Additional Information

**Device (please complete the following information):**
- OS: Windows
- Browser: Chrome

**Comment by Chhavi-Adlakkha** [comment]
can you please assign this issue to me ,I can fix this bug.

**Comment by karthiknadar1204** [comment]
@PoulavBhowmick03 there is an issue with the path here,
Please wait for @akshitagupta15june or @Rakesh9100 to assign this issue to you

**Comment by PoulavBhowmick03** [comment]
Okay!

**Comment by Rakesh9100** [comment]
Proceed @PoulavBhowmick03
