### ISSUE TITLE
[BUG] Website is not mobile responsive. Making it responsive [GSSoC'23].

### ISSUE THREAD

**Issue by 1Shubham7** [akshitagupta15june/Moksh#547]
## Description

**Describe the bug:**
The website is not mobile responsive
![monile_responsive](https://github.com/akshitagupta15june/Moksh/assets/116020663/6981fcb2-d7ce-4dbe-bc71-bb2e11643444)

**Expected behavior:**
We expect the text and cards to go look responsive

**Actual behavior:**
They look very unprofessional when viewed with mobile

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux] Windows
- Browser [e.g., Chrome, Safari, Firefox] Chrome
- Version [e.g., 22]

**Additional context:**
Please Assign me this issue under GSSoC'23

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by 1Shubham7** [comment]
I am interested to work under this issue, please assign me this issue.

**Comment by Once-kaur** [comment]
I am gssoc'23 contributor  i would also like to work on this issue
