### ISSUE TITLE
add the discord link in moksh readme 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#55]
https://discord.gg/Jmc97prqjb
create a button UI in readme and add this link for the contributors to join this channel for asking any doubts if they have

**Comment by Yashdon999** [comment]
I want to Work on This issue

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by Yashdon999** [comment]
The issue you had is fixed @akshitagupta15june

**Comment by Yashdon999** [comment]
can i give some ideas for your website!
