### ISSUE TITLE
[BUG] Overflowing and Overlapping Issues

### ISSUE THREAD

**Issue by Vidip-Ghosh** [akshitagupta15june/Moksh#550]
## Description

**Describe the bug:**
In mobile view, Iskcon Events page, contents are getting overlapped with each other. 
Components are not taking the full width i.e. there are some spaces. 
Footer and Navbar requires improvement. 

**Expected behavior:**
Every components like Map, Navbar, Footer are supposed to take full width. 
Cards elements should not overlap. 
Responsive for all devices. 

**Actual behavior:**
Overlapping, Space left i.e. not taking full width. 

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
Media Query for responsiveness in all devices.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

<img width="477" alt="Screenshot 2023-05-28 at 10 55 13" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/037b0117-1522-42d4-9c38-76674dcb64a4">
<img width="493" alt="Screenshot 2023-05-28 at 10 53 58" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/83bab54d-ce71-4f77-bf67-33ca0d5af53b">
<img width="498" alt="Screenshot 2023-05-28 at 10 53 07" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/02a6e8fd-7331-4611-bcaa-bce7ec0c1684">

## Additional Information

**Device (please complete the following information):**
- OS: Redmi Note 9 Pro Max
- Browser Chrome
- Version 113.0.5672.126

**Additional context:**

I would like to work on this issue, Please assign me under GSSoC'23.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor
