### ISSUE TITLE
[STYLE CHANGE] Improving the Navbar of Home Page

### ISSUE THREAD

**Issue by anirudhsalaria** [akshitagupta15june/Moksh#551]
**Description:**
Improving the Navbar of the home page by removing the underline effect we get, when we hover on the options present in the Navbar.

**Screenshots or Design Mockups**
![Screenshot (1)](https://github.com/akshitagupta15june/Moksh/assets/109616328/e813863e-886d-47f5-8394-7ff74b6b21d0)

**Priority Level**

- [ ] Low
- [x] Medium
- [ ] High

**Comment by khadesamrudhi** [comment]
please assign me this project.

**Comment by aniketnimkar** [comment]
Please assign me this issue under GSSoC-2023 i love to contribute to this issue.

**Comment by anshujichaudhari** [comment]
I would like to work on this project . Please assign it to me .

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by ankitjt** [comment]
It's done. Do a fresh fetch to get the changes.
