### ISSUE TITLE
Enhance: Card UI of the blog page 

### ISSUE THREAD

**Issue by Pragati-3003** [akshitagupta15june/Moksh#555]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by karthiknadar1204** [comment]
@Pragati-3003 Please share the details of the issue.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Please share the details of the issue.

I would like to change the ui of  cards of the blog page .
![Screenshot 2023-05-31 163432](https://github.com/akshitagupta15june/Moksh/assets/132778037/7763a8bd-80f8-4282-a640-abfb295f5d15)
I would like to add the cool hover and box shadow effects .
