### ISSUE TITLE
[GSSOC] Fixing The Navbar

### ISSUE THREAD

**Issue by GeekWolf007** [akshitagupta15june/Moksh#558]
**Description:**

The navbar is not looking good and the alignment is also not correct

![Screenshot 2023-05-28 200432](https://github.com/akshitagupta15june/Moksh/assets/126271100/f1c25d79-377b-4cef-ae62-90b69a0d64e6)
 
I have experience in webdev and I can improve the designing of this issue

Please assign me this issue

**Comment by aniketnimkar** [comment]
##Reason for change:
even I noticed that the nav bar ui looks bad I have created several nav bars before so 
Please assign me this issue under GSSoC-2023 I love to contribute to this issue.

**Comment by anshujichaudhari** [comment]
I would like to work on this project . Please assign it to me.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by ankitjt** [comment]
Navbar is already updated, pl do a fresh fetch to get the latest changes.
