### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by iamRabia-N** [akshitagupta15june/Moksh#562]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by karthiknadar1204** [comment]
@iamRabia-N Please close this issue
