### ISSUE TITLE
[BUG] Links not working from Rejuvenate page

### ISSUE THREAD

**Issue by Prakriti2003** [akshitagupta15june/Moksh#571]
## Description

**Describe the bug:**
Links to go the Augmented Reality page, Pomodora page and read a shlok page not working from the Rejuvented page.

**Expected behavior:**
When clicked on the mentioned options they should redirect to proper pages for each of the options.

**Actual behavior:**
After clicking on the AR , Pomodora and read a shlok they are showing page not found.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'Rejuvenate'
2. Click on 'Features'
3. Scroll down to 'Augmented Reality Vision'
4. Click on it.
5. See error

1. Go to 'Rejuvenate'
2. Click on 'Features'
3. Scroll down to 'Pomodora Spiritual Break'
4. Click on it.
5. See error

1. Go to 'Rejuvenate'
2. Click on 'Features'
3. Scroll down to 'Read a Shlok'
4. Click on it.
5. See error

**Expected result:**
Should redirect to the applicable page.

**Actual result:**
Showing '404 error' page not found.

## Screenshots

![2023-05-29 (3)](https://github.com/akshitagupta15june/Moksh/assets/96686092/4c24bbed-b9f3-4e63-ac00-c9afa310be6f)
![2023-05-29 (4)](https://github.com/akshitagupta15june/Moksh/assets/96686092/5a421f72-5c35-4b5a-9bec-81a2ee7d1b88)
![2023-05-29 (5)](https://github.com/akshitagupta15june/Moksh/assets/96686092/495c9c41-f3da-442e-bb2f-c531ec186135)

## Additional Information

**Device (please complete the following information):**
- OS: Windows, Linux
- Browser: Microsoft Edge, Chrome, Brave
- Version [e.g., 22]

Please assign me this issue under GSSOC'23.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor
