### ISSUE TITLE
Add A Creative Footer Section

### ISSUE THREAD

**Issue by deepeshgupta3257** [akshitagupta15june/Moksh#573]
## Description

**Is your feature request related to a problem? Please describe.**
It's not a problem but to have a good footer makes a website look cool and easy for a user to get the details about the social media handles and many more important part from the bottom also.

**Describe the solution you'd like**
I have a quite good solution for your website to add a attractive and informative footer section which will consist of all the important information about the website and all the official social media handles.

**Describe alternatives you've considered**
It can be a better option for the user that uses the website to get information about the website form the footer section also.

I can add all the informative details in this section of your footer

## Additional Information

**Context**
Its a very basic footer that has been uesd, but I can update it to make it appears attractive and creative

![image](https://github.com/akshitagupta15june/Moksh/assets/108192513/aed8e0dc-f524-46cc-bbc5-989b681dbd60)

I can make your website footer page similar to this 

![image](https://github.com/akshitagupta15june/Moksh/assets/108192513/03bdfc24-c7a5-4601-8b5b-0c080edf8c27)

So, please assign me this issue under GSSOC'23.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by Snigdha2712** [comment]
Please assign this project to me. I will fix the issue.

**Comment by ankitjt** [comment]
pl do a fresh fetch footer was updated.
