### ISSUE TITLE
Fix link path of rejuvenate page

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#574]

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by Prakriti2003** [comment]
I have already mentioned this in a previous issue #571. Please review that issue and assign it to me under GSSOC'23.

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me I will solve this issue under GSSOC'23. I will solve the mentioned issue with the help of the required HTML and CSS code
