### ISSUE TITLE
[FEATURE REQUEST] Want to add a 'NewsLetter' section

### ISSUE THREAD

**Issue by splusb** [akshitagupta15june/Moksh#575]
Hi, I think if we add a 'NewsLetter' section on the home page, then it will be more user-friendly.
It will ask users about their Email addresses and then update them each time there is some feature addition or change in the website.

Please look into this issue and assign it to me under GSSOC'23

**Comment by Akanksha038** [comment]
Hello @akshitagupta15june Ma'am,
I want to add a 'NewsLetter' section in the website. I am a Frontend Developer and I want to work on these issues So, can you please assign this issue to me under GSSOC'23?

**Comment by ankitjt** [comment]
This would require a database setup along with email services. 

It will not be incorporated at the moment , please find some other issue to work on.
