### ISSUE TITLE
[BUG] : Resize the Navbar

### ISSUE THREAD

**Issue by shishiro26** [akshitagupta15june/Moksh#586]
## Description

**Describe the bug:**
The navbar is extending beyond the screen and is not properly fixed in place.
**Expected behavior:**
The navbar should remain fixed and fit perfectly within the computer screen.
**Actual behavior:**
The navbar extends beyond the screen boundaries, causing difficulties in using the UI.

## Reproduction Steps

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/113853868/1d4f5411-825b-4f51-b0b8-f889a37d47d7)

**Additional context:**

I would like work on this

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me I will solve this issue under GSSOC'23. I will solve this issue by resizing the navbar width with the help of required HTML and CSS code

**Comment by manshasinghal** [comment]
the navbar is not fixed properly i can fix this and make navbar look good please assign this issue to me.

**Comment by ankitjt** [comment]
navbar is updated, pl do a fresh fetch to see the changes.
