### ISSUE TITLE
[FEATURE REQUEST] Request for Responsive Website Design Implementation

### ISSUE THREAD

**Issue by shishiro26** [akshitagupta15june/Moksh#587]
## Description

**Is your feature request related to a problem? Please describe:**
The website is currently not responsive, which means it does not adapt well to different screen sizes and devices.

**Describe the solution you'd like:**
I would like to request making the website responsive so that it can provide a seamless and optimized user experience across various devices.

**Describe alternatives you've considered:**
I have considered a few alternative solutions to address the responsiveness issue. These include:
- Manually adjusting the website layout for different screen sizes.
- Utilizing a responsive CSS framework, such as Bootstrap or Tailwind CSS, to facilitate the responsive design implementation.

## Additional Information

**Context:**
The website currently lacks responsiveness, which leads to difficulties in viewing and navigating the content on different devices.

**Potential Implementation:** (optional)
To make the website responsive, we could follow these steps:
1. Identify the key sections and elements that need to be adjusted for different screen sizes.
2. Apply CSS media queries to define specific styles for different breakpoints.
3. Utilize responsive design techniques to rearrange and resize elements as needed.
4. Test the website on various devices and screen sizes to ensure a consistent and optimal user experience.

**Screenshots or Mockups:** (optional)
Here is a link to a screenshot of the current website design: 
![Screenshot](https://github.com/akshitagupta15june/Moksh/assets/113853868/6874d099-0a7a-4031-9608-731aef2f9281)

**Priority:** (optional)
High

**Comment by huamanraj** [comment]
hey, I want to work on this website UI and make it responsive for more devices as well, please assign me this issue for gssoc 2023

**Comment by ankitjt** [comment]
This is already under work and will be updated soon. 

Please find some other issue to work on.
