### ISSUE TITLE
[FEATURE REQUEST] Adding Router for routing one page to another 

### ISSUE THREAD

**Issue by tajmalnas** [akshitagupta15june/Moksh#588]
As of now when click on navbar elements it reloads page or we can say redirect us to new page .But it is not property of react JS anchor tag should be changes with LINK and router should be used to make it proper react JS web app

**Priority** 
High

I can do this single day and UI will not be affected but make web app more faster

**Comment by karthiknadar1204** [comment]
The project is built using pure html,css and js, it does not  us react js
Please close this issue
