### ISSUE TITLE
bug in infinite scroll

### ISSUE THREAD

**Issue by laibaahsan27** [akshitagupta15june/Moksh#590]
The inifinite scroll with contributors is going out of frame at a perticular width.
![image](https://github.com/akshitagupta15june/Moksh/assets/123810454/8ce626cc-3361-46de-990c-e08ee5eba8d7)
I can make it responsive and fix the bug.
@akshitagupta15june please assign it to me under the label GSSOC 2023.

**Comment by ankitjt** [comment]
The homepage is already under some UI changes, issues like responsiveness will be fixed soon. 

Pl find another issue to work on.
