### ISSUE TITLE
adding footer section on pages

### ISSUE THREAD

**Issue by mridulsaggi** [akshitagupta15june/Moksh#592]
some pages such as ar meditate and read a shlok page are missing the footer section which inhibits the user from accesing the features of the website and navigate to features section.
i would like to contribute to this project by adding the footer sections for enhancing the user experience
example of missing footer:
![image](https://github.com/akshitagupta15june/Moksh/assets/91930535/77a6f7c8-398b-4b72-91ea-1492a436edcd)

**Comment by karthiknadar1204** [comment]
@mridulsaggi The ar-vr page already has a footer and we dont need any links to be added to the footer as of now.
If you have any other suggestions then please feel free to share them else please close this issue

**Comment by ankitjt** [comment]
Closing this.
