### ISSUE TITLE
Improve the UI of the features section in index.html

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#6]

**Comment by karthiknadar1204** [comment]
please assign this issue to me.

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by karthiknadar1204** [comment]
@akshitagupta15june ,i was thinking of reducing the height of the cards the the featured section,make the border round,add proper alignment to the buttons and was also thinking of improvng the font used in the card.

are these changes fine or should i add/delete something

**Comment by akshitagupta15june** [comment]
Yes you can

**Comment by karthiknadar1204** [comment]
Have added a hover effect to the buttons as well,alignment of the buttons is left,will align the buttons and initiate a pr

**Comment by karthiknadar1204** [comment]
<img width="1754" alt="Screenshot 2023-04-09 at 7 43 18 PM" src="https://user-images.githubusercontent.com/95973644/230777798-3c14a535-129b-419d-aa39-0224d1b63c69.png">


are these changes fine or should i add anything more,tried increasing the border of the cards but it is not getting applied. @akshitagupta15june

**Comment by akshitagupta15june** [comment]
@ritik48 ok I am assigning you

**Comment by ritik48** [comment]
hey @karthiknadar1204,
please review my pr #323
