### ISSUE TITLE
[STYLE CHANGE] 

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [akshitagupta15june/Moksh#602]
**Description:**
I would like to add night mode to the application.
[Provide a clear and concise description of the style change you are requesting.]

**Reason for Change:**
Night mode would help to provide a better user experience.
[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**
The blue-white theme will be changed to a darker theme.
[Describe the current styling that needs to be changed.]

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by ankitjt** [comment]
Hi please read old issues, dark mode is not required.
