### ISSUE TITLE
Issue/Suggestion : Addition of more blogs related to mental health

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [akshitagupta15june/Moksh#603]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##
**Issue and Steps to Reproduce:**
Addition of more blogs related to mental health.
**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**
Addition of more blogs related to identifying mental health problems, dealing with mental heath issues and stories of people who fought such issues will make the website a lot more helpful for the users.

**Comment by ankitjt** [comment]
Most of the blogs are published by the administrators, but please feel free to submit any content in the discord channel for review.
