### ISSUE TITLE
[FEATURE REQUEST] Add a contact us section with social media icon for users to contact conveniently.

### ISSUE THREAD

**Issue by prathanab** [akshitagupta15june/Moksh#604]
## Description

**Is your feature request related to a problem? Please describe.**
while we scroll through a website we always checkout social media accounts so they should be easy to find for user.

**Describe the solution you'd like**
Add a contact us section with social media icon for users to contact conveniently using html and css below contributors serction.

**Describe alternatives you've considered**
.

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)

![WhatsApp Image 2023-05-26 at 10 36 24 PM](https://github.com/akshitagupta15june/Moksh/assets/121685069/cf154fb4-878d-4eab-8013-22a859da008c)

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by rawalgeetika** [comment]
@prathanab Pls assign me this issue under GSSOC'23 .Would like to work on this issue.
