### ISSUE TITLE
Making a few changes for accessibility 

### ISSUE THREAD

**Issue by Enhancer18** [akshitagupta15june/Moksh#607]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**

The page is not responsive.The contents of the page i.e the contributors part is scrolling from outside the box upon the border.
![Screenshot_2023-05-31-10-32-15-02_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/akshitagupta15june/Moksh/assets/102911149/288ad490-1267-45f7-90c3-7abbf71849de)

**Screenshots:**
_Page opened on mobile:_

![Screenshot_2023-05-31-10-30-23-39_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/akshitagupta15june/Moksh/assets/102911149/0fc57a2f-9995-44d0-a53e-c25d663e2071)

_This is the page after clicking on the desktop view:_

![Screenshot_2023-05-31-10-30-31-81_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/akshitagupta15june/Moksh/assets/102911149/40f59d36-0869-4d20-b44c-46d79cf41421)

**Expected:**

The page should load in the total place allocated to it and the contents should - arrange itself accordingly and the contributors list should scroll inside the box.

**Comment by ankitjt** [comment]
The homepage is already under UI changes, pl wait or work on some other issues.
