### ISSUE TITLE
[BUG] Fix Text in Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [akshitagupta15june/Moksh#608]
## Description

**Describe the bug:**

There is a typo in the landing page. The word 'spiritual' is spelt incorrect.

**Expected behavior:**

The spelling should be 'spiritual'.

**Actual behavior:**

The spelling is 'spritual'.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to the Moksh Landing Page
2. Scroll down to the 'Pomodoro Spritual Break' section
3. See error

## Screenshots

![Screenshot 2023-05-31 123910](https://github.com/akshitagupta15june/Moksh/assets/89148144/5fccfb6e-577c-4e68-a7d4-9e8bd8b19ceb)

## Additional Information

**Device (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 113

**Additional context:**

I would like to contribute as part of GSSoC'23.

**Comment by Siddhant422** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.
