### ISSUE TITLE
uniform gap between the sections in the navigation bar

### ISSUE THREAD

**Issue by shruuti321** [akshitagupta15june/Moksh#611]
I would like to fix the spacing i.e move the sections towards left in  the navigation bar. Kindly assign this issue to me under GSSOC'23

**Comment by ankitjt** [comment]
share the page on which you would like to work , take screenshots of the issue.

Use the issue template to raise an issue.

Also, issue pertaining to navbar have been raised multiple times, do check existing issues first.

**Comment by shruuti321** [comment]
I would like to shift the sections in the navigation bar towards the left instead of being spread on the entire navigation bar.
![image](https://github.com/akshitagupta15june/Moksh/assets/114770273/1f561534-d3b0-42b4-8d4e-7325b41edd01)
Kindly assign me this issue under GSSOC'23

**Comment by ankitjt** [comment]
navbar on the homepage is updated, pl do a fresh fetch request to see the changes.
