### ISSUE TITLE
[BUG] navigation bar elements are showing hovering effect

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#617]
## Description
When we are not hovering on the about element in the navigation bar also it is showing the hovering property 

**Describe the bug:**
When we are not hovering on the about element in the navigation bar also it is showing the hovering property 
it is due to padding we can remove it by adding white-space property.

**Expected behavior:**
![WhatsApp Image 2023-05-31 at 16 45 22](https://github.com/akshitagupta15june/Moksh/assets/124120102/4fb2b2eb-1a6d-46e1-bcc3-c4bf439d0def)

**Actual behavior:**
![WhatsApp Image 2023-05-31 at 16 43 24](https://github.com/akshitagupta15june/Moksh/assets/124120102/8c80411d-5184-4100-ba7f-98e2f94c59e4)

A clear and concise description of what actually happened.

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by khadar1020** [comment]
please assign this issue to me i am contributing first time to open source

**Comment by khadar1020** [comment]
@ankitjt can i please work on this issue

**Comment by khadar1020** [comment]
@akshitagupta15june can i please work on this issue

**Comment by ankitjt** [comment]
Specify the page, is it the homepage?

**Comment by khadar1020** [comment]
yes it is in the homepage that is index.html page

**Comment by ankitjt** [comment]
do a new fetch request, homepage has been updated.
