### ISSUE TITLE
Hovering change [STYLE CHANGE] 

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#625]
**Description:**
when we click on [Power of Knowledge Blogs] and inside there is a navigation bar with HOME BLOG and FEATURES when we hover on it there is no underline that is there is no hovering effect

**Reason for Change:**

to make webpage beautiful

**Current Styling:**
![WhatsApp Image 2023-05-31 at 20 18 58](https://github.com/akshitagupta15june/Moksh/assets/124120102/8330b197-abfa-4cbb-844e-51f59cb4af64)

[Describe the current styling that needs to be changed.]

**Proposed Styling:**
we can make an underline when we hover over it with a transition of 0.15s so that it looks great

[Describe the desired styling or changes you would like to see.]

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**
![WhatsApp Image 2023-05-31 at 20 18 58](https://github.com/akshitagupta15june/Moksh/assets/124120102/791add2a-3a5c-45e9-8711-f4e63525e68f)

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by khadar1020** [comment]
Iam contributing first time to open source please assign this issue to me

**Comment by ankitjt** [comment]
The blog page was updated few days back, do a new fetch to see the changes.
