### ISSUE TITLE
Navbar looks crude and unrefined

### ISSUE THREAD

**Issue by harsh-kumar213** [akshitagupta15june/Moksh#627]
**Description:**

The navbar of the website looks very plain and not properly spaced.

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

**Current Styling:**

[Describe the current styling that needs to be changed.]

**Proposed Styling:**

I will like to center the elements of the navbar also change the main color of the site to suit the conceipt of spirituality.

Please assign me.

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

 Medium

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by parulchaddha** [comment]
Please assign this issue to me

**Comment by ankitjt** [comment]
do a new fetch , there are changes with regards to the navbar.
