### ISSUE TITLE
Blog Card Improvement 

### ISSUE THREAD

**Issue by 9520prashant** [akshitagupta15june/Moksh#629]
## Description

If we improve blog card styling then it should be looks very good

**Describe the solution you'd like**
For Improvement we simply use scale property as we have already used in Home section but in other way.

**Screenshots or Mockups** (optional)

**Before Adding Feature**

https://github.com/akshitagupta15june/Moksh/assets/99237795/805b8a22-4e02-4083-9316-dc45d0f95f3d

**After Adding Feature** 

https://github.com/akshitagupta15june/Moksh/assets/99237795/aeba2f5a-454d-471f-a2d2-f8ec605f93e3

**Additional Notes** (optional)
Hey @akshitagupta15june Kindly assign me this feature under gssoc.

**Comment by ankitjt** [comment]
Do a fresh fetch, blog page is updated.  
Closing this issue for now.
