### ISSUE TITLE
[BUG] The landing page  and its Video section is not responsive. Its get messed up when in small screen

### ISSUE THREAD

**Issue by samSoumyajitD** [akshitagupta15june/Moksh#637]
## Description

**Describe the bug:**
The landing page's video section lacks responsiveness, causing it to become distorted on smaller screens. This issue adversely affects the user-friendliness of the website and diminishes the overall user experience. It is crucial to address this problem and make necessary improvements to ensure that the video section adapts seamlessly to different screen sizes. By enhancing the responsiveness of the landing page's video section, users will have a more enjoyable and user-friendly experience, ultimately improving their overall satisfaction with the website.

**Expected behavior:**
To address the issue of the landing page's video section lacking responsiveness and causing distortion on smaller screens, here are some improvements that can be made:

Responsive design: Implement a responsive design approach for the video section, allowing it to adapt fluidly to different screen sizes. This can be achieved by using CSS media queries and flexible layouts to ensure that the video scales appropriately.

Aspect ratio adjustment: Consider adjusting the aspect ratio of the video to maintain its proportions on various devices. This can prevent distortion and ensure that the video content remains visually appealing.

**Actual behavior:**
The landing page's video section lacks responsiveness, causing it to become distorted on smaller screens. 

## Reproduction Steps

**Expected result:**
The video should come up properly when the website is opened in small screen.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![dq](https://github.com/akshitagupta15june/Moksh/assets/92439710/9bce0ad2-e3fe-439b-919d-1a50b5734db3)

## Additional Information

**Device (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version 22

**Additional context:**

I m a GSSOC'23 contributor. I want to contribute to this amazing project pls assign me this. under the label gssoc'23.

**Comment by BhartiNagpure** [comment]
I  would like to resolve this issue , please assign me.

**Comment by ankitjt** [comment]
Issue was already raised and is under works. Please find some other issue to work on as the homepage will be updated soon.
