### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sachin4219** [akshitagupta15june/Moksh#638]
## Description
The homepage is not responsive

**Describe the bug:**
The home page has many components that do not have proper styling (width, height, media queries, bootstrap classes)
1) The contributor section has fixed width and height overflows against defined parent container styling and disrupts the sizing of many elements by allowing the full width of the body to expand
2) The iframe for youtube video has a fixed width and height which cause it to overflow the header section on small screens

**Expected behavior:**
The body should be the controller of the child element's width and images should have responsive sizing

**Actual behavior:**
For window width below 1163px the contributor section overflows is container causes body to have higher width and disrupts styling of other elements

## Reproduction Steps

1. Go to 'https://akshitagupta15june.github.io/Moksh/index.html'
2. Go to 'developer tools'
3. Reduce width below '1163px'
4. See error all over the page

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/91952010/c8fa0b90-6cb4-41d7-98be-cc0cd133f7af)

## Additional Information

**Device (please complete the following information):**
- OS: [Windows]
- Browser [Chrome]
- Version [113.0.5672.127]

**Comment by Sachin4219** [comment]
A similar issue was opened few weeks ago but no one has resolved this problem yet and as a result the website does not look good on smaller screens

**Comment by ankitjt** [comment]
The changes are submitted , it's under review and will be updated soon.
