### ISSUE TITLE
[STYLE CHANGE] 

### ISSUE THREAD

**Issue by mitalijambhulkar67** [akshitagupta15june/Moksh#648]
**Issue Description:**
I would like to make some modifications to the website's header section at line number 148, where there is a heading. It would be beneficial from the user's perspective if the heading attracts their attention and clearly conveys the purpose of the section, which is 'Moksh Features.' This change aims to help users understand what the section entails and improve their overall experience.

**Reason for Change:**

There can be several reasons to make modifications to the website's header and improve the heading to attract users and enhance their experience. Here are some potential reasons:

1.User engagement: A compelling heading in the header section can grab users' attention and encourage them to explore further. By clearly conveying the purpose of the section, users are more likely to engage with the content and spend more time on the website.

2.Clarity and understanding: A well-crafted heading helps users quickly understand what the section is about. It sets clear expectations and enables users to navigate the website more efficiently, finding the information they need without confusion.

3.Branding and messaging: The heading in the header section can serve as a branding element, reinforcing the website's identity and message. A strong and captivating heading can align with the overall brand image, leaving a lasting impression on users.

4.User satisfaction: When users can easily comprehend the content and purpose of a section, it enhances their overall satisfaction with the website. By optimizing the heading, you contribute to a positive user experience, leading to increased user engagement, repeat visits, and potential conversions.

5.SEO considerations: Well-optimized headings with relevant keywords can positively impact search engine rankings. By improving the heading in the header section, you can potentially enhance the website's visibility in search engine results and attract organic traffic.

**Current Styling:**
The Current Styling in the index.html , h1 part is as follows -
margin-bottom: 0.5rem;
font-weight: 500;
line-height: 1.2;
font-size: 2.5rem;

**Proposed Styling:**

There is no animation in the heading, not even a different color to show that it is a heading. I will add some animations and color, while also maintaining the font-size and font-family CSS. I will change some styling features in the index.html page, including the following:

1.Font-family
2.Font-size
3.Justify-content
4.Some hover properties
5.Animations.

**Screenshots or Design Mockups (optional):**
Current Heading Text--
![Screenshot (175)](https://github.com/akshitagupta15june/Moksh/assets/123642577/197489fe-0256-49ea-af9c-f318d3491842)

Styling Use--
![Screenshot (176)](https://github.com/akshitagupta15june/Moksh/assets/123642577/ea1f60c9-a357-4731-9955-a898c9702a38)

**Priority Level **

- [ ] Low
- [ ] Medium
- [x] High

To update the following codes, please assign this issue to me. As this is very important to attract users. It will be very great of you, if you assign it to me. I will take responsibility for making these changes by June 5th, 2023.

**Comment by ankitjt** [comment]
do a fresh fetch, pages have been updated.
