### ISSUE TITLE
Grammatical Errors  and Typo in Documentation

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#649]
## Description

**Describe the bug:**
The documentation contains several grammatical errors and a noticeable typo that need to be addressed for improved clarity 

**Expected behavior:**
I expect the documentation to be free of grammatical errors and typos, ensuring a clear and coherent message for users.

**Actual behavior:**
The documentation currently contains grammatical errors and a typographical mistake, which hinder the comprehension and overall quality of the content.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to the documentation page (readme.md).
2.Navigate to the section related to [doubt section and GSSOC'23 Issue TimeLine ].
3. Read through the content, paying attention to grammar and spelling.
4. Identify the grammatical errors and the typo.

**Expected result:**
The documentation should demonstrate correct grammar and spelling throughout the text, maintaining a professional and polished appearance.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/c4959fb3-b981-4bbc-bc7a-bae4b0fb0da6)
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/a07d6487-b219-40b9-996f-15488477a81e)
We can improve this more for clarity

## Additional Context
Under **GSSOC23** assign this to me thank you!

**Comment by Akanksha2011** [comment]
I would like to work on this project. Please assign it to me.

**Comment by jfmartinz** [comment]
@ankitjt can you check this issue? pls assign this issue to me under gssoc

**Comment by savinineeli** [comment]
I have selected this project. I would like to get started. Please guide me
further regarding this.

**Comment by jfmartinz** [comment]
@akshitagupta15june can you check this issue?

**Comment by jfmartinz** [comment]
@ankitjt sorry for mentioning you for the 2nd time. can you check this issue? I want to work on this under gssoc

**Comment by akshitagupta15june** [comment]
Ok
