### ISSUE TITLE
The steps on creating a pull request lacked the git checkout -b

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#650]
## Description

Describe the bug:
The README file lacks the inclusion of the <code>git checkout -b</code> command in the instructions for creating a new branch to make changes.

Expected behavior:
I expected the README file to provide clear instructions on creating a new branch using <code>git checkout -b</code> before making changes for bug fixes or improvements.

Actual behavior:
The README file does not mention the <code>git checkout -b</code> command, which may lead to confusion for contributors who are unaware of the need to create a separate branch for their changes.

Reproduction Steps

1. Go to the README file of the project repository.
2. Read the instructions or guidelines for contributing.
3. Look for the section that describes creating a new branch for making changes.
4. Observe that the git checkout -b command is missing or not mentioned.

Expected result:
The README file should include clear instructions on utilizing the git checkout -b command to create a new branch for changes, ensuring a proper workflow for contributors.

## Screenshots
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/bf42f5e2-5847-4836-ae6b-2746b2e9516e)

## Additional Context
Assign this to me Under GSSOC23

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Comment by ankitjt** [comment]
Check the [contributing.md](https://github.com/akshitagupta15june/Moksh/blob/main/Contributing.md) file, instructions on how to work on the repository like forking the repo, creating a branch are mentioned there.
Readme.md file has a general layout on how to work.
