### ISSUE TITLE
I want  to add a pdf Issue/Suggestion

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#653]
if you are in interested in adding any pdf then you see my issue.
[Yoga Notes final (1).pdf](https://github.com/akshitagupta15june/Moksh/files/11636129/Yoga.Notes.final.1.pdf)
I want to add this pdf to the webpage so that it open in a new tab.If you are interested I have attached the pdf above. 

**Actual:**

**Additional Details:**

**Comment by khadar1020** [comment]
@akshitagupta15june
 please assign me this issue

**Comment by ankitjt** [comment]
as of now we are only uploading articles in form of blog.
