### ISSUE TITLE
Add a cool Dark Mode feature 

### ISSUE THREAD

**Issue by Saikatssd** [akshitagupta15june/Moksh#655]
## Description

**Is your feature request related to a problem? Please describe.**
There is no Dark mode option for this website

**Describe the solution you'd like**
The dark Mode feature will attract more peeps.
 I will add a toggle button which act as theme changer from dark mode to light mode

**Comment by Saikatssd** [comment]
@akshitagupta15june  Please assign this issue to me so that I can contribute in GSSOC 23.

**Comment by ankitjt** [comment]
Since it's spiritual project we have decided not to go with dark mode.
