### ISSUE TITLE
Making your website responsive [GSSoC'23]

### ISSUE THREAD

**Issue by adityatyagi-av** [akshitagupta15june/Moksh#656]
Your website is not responsive for small screens like mobile phone and tablets. 
Assign this issue to me under GSSoC'23.

**Comment by ankitjt** [comment]
We cannot assign the entire website to one contributor.

Find an issue/page you would like to work on and raise an issue for that.

Before raising a new issue, go through the existing list to see whether a similar issue is already raised or assigned to avoid getting yours marked as duplicate.
