### ISSUE TITLE
I would like to add media Query [GSSoC'23]

### ISSUE THREAD

**Issue by Abhishekvk04** [akshitagupta15june/Moksh#660]
# **I would like to add Media Query**

## Issues:
- [x] No proper media qurey was added in the code.
- [x] Moksh logo overlap and not arranged properly.
- [x] Alignment of app to <1000 width.

## Steps to solve the issue
1. By adding a proper media Query.
2. aligning the logo properly

![Screenshot 2023-06-03 195058](https://github.com/akshitagupta15june/Moksh/assets/117388178/751e2a1c-0ca6-4b43-99e0-f66d9938c9dc)

**Comment by ankitjt** [comment]
The homepage is getting revamped and is under process. Pl wait same will be updated soon.

**Comment by Abhishekvk04** [comment]
OK I have resolved this issue through pull request #661 please check this.

**Comment by Abhishekvk04** [comment]
And please assign this to me.

**Comment by ankitjt** [comment]
pl do a new fetch, the UI of the homepage is updated and is responsive. 

If you find any other issues, pl create a new issue.
