### ISSUE TITLE
[FEATURE REQUEST] add navbar and footer to Augmented Reality Meditation page [GSSOC'23]

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [akshitagupta15june/Moksh#662]
## Description

**Is your feature request related to a problem? Please describe.*
navbar is not present on this page then how the user will redirect to the home page? also, the footer section is blank. 

**Describe the solution you'd like**
add navbar and footer 

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
![image](https://github.com/akshitagupta15june/Moksh/assets/112896644/f0b33277-23ef-4238-b9e3-7de4e1d7e299)
![image](https://github.com/akshitagupta15june/Moksh/assets/112896644/9f2f8a3c-a978-4240-9dc2-c8ff0050837b)

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I will fix the issue.

**Comment by ankitjt** [comment]
@shivaniyuvrajyadav Assigned, do submit your PR within a week.
