### ISSUE TITLE
Missing Pull Request template

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#663]
Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

Please assign this issue to me under GSSoC'23
@akshitagupta15june

**Comment by ankitjt** [comment]
@DivyanshiNarang assigning the issue to you, pl adher to the time frame you have one week to submit your changes (Pull Request).
