### ISSUE TITLE
Not showing site in AR 

### ISSUE THREAD

**Issue by vaibhav4gaur** [akshitagupta15june/Moksh#664]
## Description

**Describe the bug:**
opening in mobile not showing AR website 

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![Screenshot 2023-06-04 at 2 57 03 PM](https://github.com/akshitagupta15june/Moksh/assets/110227490/d2b3070f-a309-4ff4-bb6f-fcb290f29725)
![WhatsApp Image 2023-06-04 at 2 58 02 PM](https://github.com/akshitagupta15june/Moksh/assets/110227490/1283f26b-cc33-441d-b7af-15c4aa42089a)

when we scan this QR code so the website directly open the API 3d .com and it does not show the 3d view of AR

it shows that you have used all your project's credits
## Additional Information

**Device (please complete the following information):**
 -MacOS,Browser 
 -Version 12.6.3

**Additional context:**

can you assign this problem to me under SSOC 2.0

**Comment by ankitjt** [comment]
at the moment all the credits are consumed hence the QR code is not working. It'll work once we replenish our credits.
