### ISSUE TITLE
Adding links to the social media handles in the "Power of Knowledge Blogs" footer

### ISSUE THREAD

**Issue by BhavyaVohra08** [akshitagupta15june/Moksh#669]
I am a contributor in GSSOC'23. Kindly assign this issue to me.

**Comment by ankitjt** [comment]
Those profiles are getting created , we will update once it's created.

**Comment by ankitjt** [comment]
We will update in the readme
file.

**Comment by ankitjt** [comment]
It'll be added in the readme section of the repository, you can refer to it and add if required.

**Comment by BhavyaVohra08** [comment]
Kindly assign this issue to me, whenever they are created, so that I can get notified.
