### ISSUE TITLE
About button in the Quick Links is not working [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [akshitagupta15june/Moksh#676]
## Description

**Describe the bug:**
About button in the Quick Links in Iskcon Events page is not working

**Expected behavior:**
It should have opened About page.

## Screenshots

![Screenshot 2023-06-06 001117](https://github.com/akshitagupta15june/Moksh/assets/123325132/2f43984e-b510-447f-ba12-229036ef35ed)

Please assign me this issue under GSSoC'23.

**Comment by akshitagupta15june** [comment]
its not needed now because footer will be changing

**Comment by Anshul439** [comment]
Ok mam
