### ISSUE TITLE
Issue/Suggestion   

### ISSUE THREAD

**Issue by Krishkumar2005** [akshitagupta15june/Moksh#682]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue 
when are we click any link which is provided in home page feature section , it is open in the same page which is not good so to make it attractive it should be open in the blank page.
**Screenshots:**

**Expected:**

**Actual:**

**Additional Details:**

**Comment by ankitjt** [comment]
opening each page on different tabs would put load on RAM and will make the browser slow. 
Plus the navbar is present on each page if the user wants to go a page they can use the navbar directly.
