### ISSUE TITLE
[STYLE CHANGE] : Improve the UI of navbar menu link [GSSOC'23]

### ISSUE THREAD

**Issue by itsmohit097** [akshitagupta15june/Moksh#691]
**Description:**

Improving the navbar menu UI

**Reason for Change:**

Improving the navbar menu UI to make it more attractive

**Current Styling:**

The navbar menu is taking the half of the space and it is not much attractive

**Proposed Styling:**

Reduce the space taking by it and giving it a glassmorphism effect

**Screenshots**
BBEFORE
![Screenshot (82)](https://github.com/akshitagupta15june/Moksh/assets/125040386/ef433b1e-62bb-4e87-a441-bc493728c7c4)
AFTER
![Screenshot (83)](https://github.com/akshitagupta15june/Moksh/assets/125040386/76b60a87-df03-4282-851d-ef15fac7bc76)

**Priority Level (optional):**
High

**Request**
As  i am seeing there are lots of issues and PRs which has to be reviewed but it is not review yet. I am requesting that i want to work as a mentor and contributor both.

**Comment by itsmohit097** [comment]
I've used the tailwind css. I already did it u just have to assign it to me and i just have to raise  a PR to merge it. That's it.

To give a glassmorphism effect I did :-
1. add the backdrop blur effect to the navbar and navbar menu liks and give it  a background of  white with opactiy of 30.
![Screenshot 2023-06-08 011237](https://github.com/akshitagupta15june/Moksh/assets/125040386/94065681-f5dd-4b84-a9fe-d73839bde446)

2. reduce the width of the navbar menu links by wd-1/5.
3. add the slate divider between the nav menu links

**Comment by itsmohit097** [comment]
One more thing i want to say that the existing UI of the all features section doesn't suits to the Home page. And i'm seeing there are many issues were raised related to that whole section. We should make some changes to the UI first then we look into the further issues. I have some ideas to modify it if you're interested we can talk about it.
OR 
If someone is working on this, i would love to collaborate.

**Comment by itsmohit097** [comment]
@ankitjt @akshitagupta15june  please respond

**Comment by ankitjt** [comment]
For desktop screens we are keeping the navbar open so it can be accessed directly , you can do it for mobile screen. 
Do a new fetch to get the latest changed and then work on it.
