### ISSUE TITLE
i want to add page with meditation songs.

### ISSUE THREAD

**Issue by ritikasrv12** [akshitagupta15june/Moksh#694]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
People while get relax after listening to the song.
**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Akanksha038** [comment]
Hello @akshitagupta15june Ma'am,
I would like to add page with meditation songs. This will help to enhance the user experience.
Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #694.

**Comment by ankitjt** [comment]
on AR Meditate page there are songs for meditating. Pl check.
