### ISSUE TITLE
[SCROLL BUTTON-push directly to top ] 

### ISSUE THREAD

**Issue by Sushilverma002** [akshitagupta15june/Moksh#695]
## Description

**Is your feature request related to a problem? Please describe.**
I  want to add the scroll button .
**Describe the solution you'd like**
for that user when ever link on the button it will redirected to top .

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by krspriya** [comment]
please assign this task to me.
@akshitagupta15june
