### ISSUE TITLE
[STYLE CHANGE]  Add a  nav  bar

### ISSUE THREAD

**Issue by krspriya** [akshitagupta15june/Moksh#697]
**Description:**

i want to add a nav bar which will have options like home , blogs , etc.

**Reason for Change:**
it would look better and for a user it would be easier to have a go through the website.

**Current Styling:**
 in current styling when we click to a button then we are able to see other options.

**Proposed Styling:**
in nav bar every option would be easily seen.

**Comment by ankitjt** [comment]
navbar is already updated.
