### ISSUE TITLE
[FEATURE REQUEST]  add CONTACT US 

### ISSUE THREAD

**Issue by krspriya** [akshitagupta15june/Moksh#698]
## Description

**Is your feature request related to a problem? Please describe.**
if anyone want to contact us, then can easily contact us for asking their various questions or doubts.

**Describe the solution you'd like**
by adding a contact us section, a user can easily contact us. they can easily ask their doubts.

@akshitagupta15june

**Comment by ansh-star** [comment]
Please assign this issue to me .I m Girlscript contributor

**Comment by ankitjt** [comment]
we are not adding this feature as of now.
