### ISSUE TITLE
[FEATURE REQUEST] Adding Social media icon to the footer section

### ISSUE THREAD

**Issue by bhaskarkumar1** [akshitagupta15june/Moksh#704]
I I want to add the social media icon to the footer section as you can see in the screenshot there is name but not social media icon.
So assign me this task, s o that I could work on it.
![moksha](https://github.com/akshitagupta15june/Moksh/assets/84345649/500ad6d4-1009-4bd9-94e9-127feaab05f9)

**Comment by ankitjt** [comment]
do a fresh fetch , social media icons are already added.
