### ISSUE TITLE
Add redirection on clicking know more

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#706]
https://akshitagupta15june.github.io/Moksh/index.html#knowMore
redirect to same page mental health problem section

**Comment by PoulavBhowmick03** [comment]
i can work on this. Please assign it to me

**Comment by dishamodi0910** [comment]
I would like to work on this issue.
Please assign it to me.

**Comment by debdutta04** [comment]
please assign me this to me

**Comment by Anshul439** [comment]
Please assign this issue to me under GSSOC'23

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
Assigning @S-ishita
