### ISSUE TITLE
remove the instagram and facebook text from footer

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#708]
only twitter and github are needed
Add twitter account link https://twitter.com/ExperienceMoksh
Github https://github.com/akshitagupta15june/Moksh

**Comment by rayarka26** [comment]
Please assign me this issue #gssoc23

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue under GSSOC'23

**Comment by smritimangal26** [comment]
Please assign this issue to me I would like to work on this under GSSOC'23

**Comment by akshitagupta15june** [comment]
Assigning @Vidip-Ghosh as @rayarka26 is already assigned another issue
