### ISSUE TITLE
add the same footer which is present in the index.html in the reward page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#711]
https://akshitagupta15june.github.io/Moksh/Pomodro_page/reward.html

**Comment by akshitagupta15june** [comment]
@Shreyans2004 would u like to work in this?

**Comment by DhairyaMajmudar** [comment]
Ma'am please assign this issue to me under GSSoC'23

**Comment by abhi03ruchi** [comment]
Plz assign this issue to me. I would like to work on it under gssoc'23.

**Comment by Shreyans2004** [comment]
Can you assign this issue to me?
