### ISSUE TITLE
[BUG] "Facebook" and "Instagram" is not appearing in Footer of the home page 

### ISSUE THREAD

**Issue by druvkotwani** [akshitagupta15june/Moksh#718]
## Description

**Describe the bug:**
"Facebook" and "Instagram"  is not appearing on the home page. 
Current Img: 
![image](https://github.com/akshitagupta15june/Moksh/assets/96691139/22931b63-fe5a-4792-b501-f020e1ee2b54)

**Expected behavior:**
All four handle: "Twitter", "Facebook", "Instagram" and "Github" should be appearing side by side.

Should look like this: 
![image](https://github.com/akshitagupta15june/Moksh/assets/96691139/9a39a36a-2421-4774-86c1-d2cd52303e08)

**Actual behavior:**
Some Code might me missing.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to the home page
2. Scroll down to the bottom 
3. See error in footer section

**Comment by ankitjt** [comment]
It was removed as it was not needed.

**Comment by druvkotwani** [comment]
@ankitjt its also there on blog page.!

**Comment by ankitjt** [comment]
It'll be updated there too
