### ISSUE TITLE
[FEATURE REQUEST] : Add Twitter and GitHub Logo instead of text 

### ISSUE THREAD

**Issue by aparna03dubey** [akshitagupta15june/Moksh#725]
## Description
Problem-
It will look more fascinating if we add the logo of twitter and github in the footer section of the home page.
Solution- 
Instead of the text, one can add the icon of the platforms.
![moksh](https://github.com/akshitagupta15june/Moksh/assets/101944716/741e4fe8-fc19-4853-9583-8015c9dcb0b4)

**Comment by akshitagupta15june** [comment]
Go for it
