### ISSUE TITLE
[FEATURE REQUEST] Sidebar has high width

### ISSUE THREAD

**Issue by Vidip-Ghosh** [akshitagupta15june/Moksh#728]
## Description

I found that the sidebar has greater width and half of the space is empty.

<img width="1680" alt="Screenshot 2023-06-09 at 13 26 46" src="https://github.com/akshitagupta15june/Moksh/assets/91741581/cc967291-88c7-4f1f-badf-42936d869ce2">

**Describe the solution you'd like**
I would make it bit short. 

**Additional Notes** (optional)
I would like to work on this issue under GSSOC'23

**Comment by ankitjt** [comment]
this is fixed.
