### ISSUE TITLE
Enhancing Layout and Styling for Paragraphs, Images, and Video Embeds on Webpages

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#729]
**Description:**
The visual presentation of paragraphs, images, and video embeds on webpages currently lacks proper spacing and takes up the full width of the webpage, without any margin or space on the left and right sides. This issue pertains to multiple breakpoints where the elements, including paragraphs, images, and videos, are affected.

**Reason for Change:**

Improving the style and layout of paragraphs, images, and video embeds is essential for enhancing the overall user experience. The current lack of spacing and cramped layout negatively impact readability, aesthetics, and user engagement. By implementing appropriate styling changes, we aim to create a more visually pleasing and user-friendly experience.

**Current Styling:**

Currently, paragraphs, images, and video embeds span the entire width of the webpage, without any margin or spacing on the left and right sides. 

**Proposed Styling:**

The desired styling changes include introducing margins and spacing for paragraphs, images, and video embeds. By providing a defined space on the left and right sides, we can improve the visual separation between elements and create a more balanced layout. The spacing should be consistent across different breakpoints to ensure a cohesive and harmonious design.

**Additional Information (optional):**
Under gssoc assign this to me

![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/76f256da-7c70-4c61-92b0-ce8344c1afb9)
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/94c1b456-b7c9-46fa-b4fc-f9107f0e5e27)
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/73c16c92-a30a-4467-8bcf-745ad9cdc627)
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/4b114d37-3c1e-4932-a98e-6d60c892e80c)

**Priority Level (optional):**

- [] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by akshitagupta15june** [comment]
Go for it
