### ISSUE TITLE
[STYLE CHANGE] "Know More" Button Styling Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [akshitagupta15june/Moksh#731]
**Description:**
The design of the button is nice but it can be improved by making some design adjustments. By working on certain styling aspects of this button, I can make it look even better.

**Reason for Change:**
In order to make it look more realistic and attractive, I want to enhance styling of this button.

**Current Styling:**
The current styling is nice but it is looking more static. Wide border is taking all the user's attention.

**Proposed Styling:**
Styling changes like updating border design, background, font, margin, etc. to make it look even good.

**Screenshots or Design Mockups (optional):**

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**
1 day

**Possible Implementation Approach (optional):**
Styling changes in the css file.

**Comment by akshitagupta15june** [comment]
Go for it
