### ISSUE TITLE
[FEATURE REQUEST]: Workflow to greet when new issue/pull request opens

### ISSUE THREAD

**Issue by harmeetsingh11** [akshitagupta15june/Moksh#734]
## Description

Currently, this project does not have any action to greet to contributors. Github action is the great tool to automate the manual stuff for your project. I would like to add Github Action workflow to greet to the new PR and issue creator.

## Record
- [x] I agree to follow Contributing guidelines and [Code of conduct](CODE_OF_CONDUCT.md) of this project.
- [x] I am a GSSoC'23 Contributor.

Please assign me this issue under GSSoC'23
Thanks

**Comment by akshitagupta15june** [comment]
Go for it
