### ISSUE TITLE
Improve this blog page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#735]
https://akshitagupta15june.github.io/Moksh/Blogs/Strength.html the picture have distorted

**Comment by Anshul439** [comment]
Please assign this issue to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
assigning u

**Comment by Anshul439** [comment]
Are you talking about the image, or the button?

**Comment by Anshul439** [comment]
![Screenshot 2023-06-10 133315](https://github.com/akshitagupta15june/Moksh/assets/123325132/3a0c5770-8c39-455b-af9c-63ad9f4a7ccd)

Is it fine?
