### ISSUE TITLE
<Improve> Folder structure

### ISSUE THREAD

**Issue by jayk-gupta** [akshitagupta15june/Moksh#74]
Create seperate folders for html, css and js.

**Comment by akshitagupta15june** [comment]
yes i will see to this issue by myself

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Lavesh12** [comment]
Can I work on this issue?

**Comment by ankitjt** [comment]
@akshitagupta15june I think restructuring of files are done, pl close the issue. @akshitagupta15june
