### ISSUE TITLE
[BUG] The navbar text is overflowing in smaller screens [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [akshitagupta15june/Moksh#742]
## Description
The navbar of the website is looking very poor in smaller screens. The text is overflowing.

## Screenshots
![navbarissue](https://github.com/akshitagupta15june/Moksh/assets/116020663/0ac343cb-3a91-4e69-ad88-d524c70a0169)

This is looking very poor. Imagine anyone opening the website from a mobile phone.

Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue.

**Comment by gauravsingh1281** [comment]
Please assign this issue to me because I have raised the same issue #727  first and I want to work on it.
