### ISSUE TITLE
[FEATURE REQUEST] Want to add color themes in the website 

### ISSUE THREAD

**Issue by lakhan06** [akshitagupta15june/Moksh#748]
## Description

**Is your feature request related to a problem? Please describe.**
I thought the brown color is not o good and we can more different color so to Improve the User experience I want to add color themes in the website so that the user have 4-5 color themes and he can choose color themes according to his/her choices.

**Describe the solution you'd like**
I want that their should be a option so that user can select color theme of the website according to his/her choice and get a better user experience .

**Describe alternatives you've considered**

I can also add dark and light mode toggle button so that user can select between dark or light mode.

## Additional Information

.

**Potential Implementation** (optional)
I will add a themes option on the right side of each page and will change the color according to user choice by using JavaScript.
I will uses root elements to change the color according to user choice.
I will also stored the data of color theme that user choose and when user again come on website then he will se the color theme according to his/her choice.

**Comment by ankitjt** [comment]
refer old issues, we are not implementing dark theme by choice, and we would like to keep the colors as is. Pl find some other issue to work on.
