### ISSUE TITLE
[BUG] nav-bar while moving down

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#766]
## Description
in cardinalVices, the nav-bar is not having a correct background color so the nav-bar is coinciding with the text
**Describe the bug:**
![Screenshot (343)](https://github.com/akshitagupta15june/Moksh/assets/124120102/1249fd41-bf8d-4cdc-8222-f7f2b5a374e5)

please assign me this issue

**Comment by karthiknadar1204** [comment]
@khadar1020 Please wait for the issue to be assigned before Submitting a pr for review
