### ISSUE TITLE
[FEATURE REQUEST] Dark mode option

### ISSUE THREAD

**Issue by kaashikaagrawal** [akshitagupta15june/Moksh#768]
## Description
Dark mode option that changes the theme of the website from light colours to dark ones for those who prefer.

**Describe the solution you'd like**
I can provide a toggle dark mode button near the top of the page to change the page from light mode to dark mode.

**Comment by kaashikaagrawal** [comment]
can I be assigned this issue to work on?

**Comment by ankitjt** [comment]
We are not going with a dark theme for the project
