### ISSUE TITLE
Navbar hiding content.

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#771]
Navbar is hiding content. 

<img width="911" alt="Screenshot 2023-06-12 155245" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/e08f306b-9799-4d4c-821a-e95c8d9d64b2">

*Please assign this issue to me under GSSOC'23*.
@akshitagupta15june

**Comment by ankitjt** [comment]
It's meant to behave like this so the links and the content don't overlap. Position the scroll bar rightly to see the content.
