### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by Shreyans2004** [akshitagupta15june/Moksh#773]
## Description

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.
Your website is very beautiful .It will become more beautiful if while loading ,a preloader will be there. I can add the preloader to the website so that looks better.Can you assign this task to me?
**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by karthiknadar1204** [comment]
It is a pure html css project,a pre loader could be implemented in a react based project with routing.
Please explore other issues to contribute to.
Thank you.
