### ISSUE TITLE
Adding a button to take you to the top of the page. [FEATURE REQUEST] [gssoc23]

### ISSUE THREAD

**Issue by thevirengarg** [akshitagupta15june/Moksh#778]
## Description
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or limitation that the requested feature would address.

After scrolling down the website if we need to up we need to scroll back up again, we should have a button which if clicked will take me to the top of the page. 

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

On the bottom right corner it will show an up arrow button which if clicked will take you to the top of the webpage.

**Comment by ankitjt** [comment]
Someone has already raised an issue about it.
