### ISSUE TITLE
Improve the footer of rejuvenate section 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#78]
https://akshitagupta15june.github.io/Moksh/rejuvenate.html

add the same footer that is available in augmented reality meditation page https://akshitagupta15june.github.io/Moksh/meditation.html

**Comment by Lavesh12** [comment]
Can I work on this issue?

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23
