### ISSUE TITLE
[ENHANCEMENT] Improve link targeting, image spacing, and blog card responsiveness across multiple screen sizes

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/Moksh#783]
## Description

**Is your feature request related to a problem? Please describe.**
The current implementation of links, image spacing, and blog cards in the blog page of the website lacks the desired behavior and responsiveness on different screen sizes.

**Describe the solution you'd like**
For the link behavior enhancement, I suggest modifying the relevant HTML templates or components to include target="_blank" in the anchor tags associated with the buttons.

Regarding image spacing, the implementation could involve adding a padding on the right and left of the web page.

For blog card responsiveness, it will update the CSS styles and potentially modifying the HTML structure of the blog cards to ensure proper layout and readability on medium and smaller screens. Using CSS media queries and responsive design techniques will be used in achieving this goal.

**Describe alternatives you've considered**

## Additional Information
Under Gssoc23 assign this to me. 
<code>I will make sure that I commit or separate each change into individual commits: After completing work on a specific issue. I will also add a screenshot for the result</code>

**Context**

**Potential Implementation** (optional)

**Screenshots or Mockups** (optional)
No spacing on small screen
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/885da2bb-6a35-480e-bd55-128a341ebe38)
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/1988dc3f-7edb-4012-bfd4-f2c14b88de68)

We can improve the responsiveness of the blog cards further. This screenshot is for small screen (It should be stacked to each other vertically) 
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/10483a68-1cc2-488d-b444-7970a5b112ab)
On medium screen: 
![image](https://github.com/akshitagupta15june/Moksh/assets/129386460/abbc77d3-2786-4a90-8474-482bc4e9db00)

**Priority** (optional)

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by ankitjt** [comment]
Pl do a new fetch request , Blog page is updated.
