### ISSUE TITLE
Add google translate option and in blog

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#787]
https://akshitagupta15june.github.io/Moksh/Blogs/depression.html
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/60674f16-92c4-4652-a69c-6d9493a61ff1)

**Comment by akshitagupta15june** [comment]
assigning

**Comment by ShashankMaikhuri** [comment]
Ma'am, can your please assign this issue to me?
