### ISSUE TITLE
[BUG] In the footer section of the site, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [akshitagupta15june/Moksh#794]
<img width="956" alt="Screenshot 2023-06-15 143401" src="https://github.com/akshitagupta15june/Moksh/assets/85905403/2864b0a2-48e5-4557-950b-faa0e376120e">
<img width="960" alt="Screenshot 2023-06-15 143629" src="https://github.com/akshitagupta15june/Moksh/assets/85905403/93626da4-ffe6-45a3-9cb6-0ac814c81b30">
<img width="956" alt="Screenshot 2023-06-15 144132" src="https://github.com/akshitagupta15june/Moksh/assets/85905403/8fb8dc3c-d754-479e-8d04-398c05850139">

**Comment by gauravsingh1281** [comment]
Please @akshitagupta15june assign this issue to me I want to work on it.

**Comment by akshitagupta15june** [comment]
What will be the difference?

**Comment by gauravsingh1281** [comment]
Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.
