### ISSUE TITLE
add a card display to all features that are presented in website

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#8]
On clicking on those cards they will redirect to the functioning page

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by mud1tx** [comment]
@akshitagupta15june I can work on this issue can you descibe it little more.

**Comment by akshitagupta15june** [comment]
Hey checkout the recent issues, this issue is completed by a contributor
