### ISSUE TITLE
add footer in read a shlok page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#80]
https://akshitagupta15june.github.io/Moksh/motivation.html

apply the same footer that is available in augmented reality meditation page https://akshitagupta15june.github.io/Moksh/meditation.html

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I think I can do it Please assign this issue to me

**Comment by mnik7044** [comment]
Hey @akshitagupta15june is this issue resolved? If not I would like to work on it please assign this issue to me

**Comment by karthiknadar1204** [comment]
@akshitagupta15june i would like to work on this issue,please assign it to me

**Comment by MOHDNEHALKHAN** [comment]
Please assign this issue to me

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Lavesh12** [comment]
Can I work on this issue?
