### ISSUE TITLE
add a sound alert functionality in pomodoro spiritual break 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#81]
https://akshitagupta15june.github.io/Moksh/reward.html

after 25 min there should be a sound alert

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by ivanMehvish** [comment]
interested to work on this issue for GSSoC'23

**Comment by dishal35** [comment]
In addition to this, could we also add a clock ticking noise in the background, the user can also have the option to mute it if they want

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23
