### ISSUE TITLE
non responsive buttons

### ISSUE THREAD

**Issue by Sumit-pd** [akshitagupta15june/Moksh#810]
## Description

**Describe the bug:**
the share, download , print buttons are not functioning 

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'http://127.0.0.1:5500/Blogs/Words.html#'
2. Click on the buttons 
3. buttons are not functioning

## Screenshots

![Screenshot from 2023-06-16 19-24-01](https://github.com/akshitagupta15june/Moksh/assets/88550925/5c4edbff-c5db-41ee-bc9d-488eb9b906ad)

## Additional Information

**Device (please complete the following information):**
- OS:  Linux
- Browser :Chrome
- Version : 22.04.2 LTS

**Comment by Sumit-pd** [comment]
I would like to work on this issue

**Comment by akshitagupta15june** [comment]
Go for it
