### ISSUE TITLE
[BUG] Improve the logo sizing the moksh text is not visible 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#815]
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/aa5efb35-a6b7-48b6-8ea1-8f0532705b30)

**Comment by ritik48** [comment]
@akshitagupta15june please assign this issue to me under GSSoC'23.

**Comment by akshitagupta15june** [comment]
ok

**Comment by Developer-Swati** [comment]
Please assign it to me @akshitagupta15june  mam , I am just 6 min late.
