### ISSUE TITLE
Improve footer of divine activities page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#82]
https://akshitagupta15june.github.io/Moksh/story.html

add the footer of augmented reality meditation page to the divine activities page https://akshitagupta15june.github.io/Moksh/meditation.html

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Lavesh12** [comment]
Can I work on this issue ?

**Comment by kushwahajai74** [comment]
Hey @a

> https://akshitagupta15june.github.io/Moksh/story.html
> 
> add the footer of augmented reality meditation page to the divine activities page https://akshitagupta15june.github.io/Moksh/meditation.html

hey, i have gone through the project and understand the issue, can you assign this issue to me under GSSOC'23
