### ISSUE TITLE
Add our contributors section just above footer in the moksh index page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#83]
Take reference from the footer of this website https://akshitagupta15june.github.io/PetMe/
petme https://github.com/akshitagupta15june/PetMe

**Comment by vaibhavmishra4g** [comment]
could you elaborate the problem further? I'm interested in resolving the issue.

**Comment by akshitagupta15june** [comment]
Have you checked petme website footer contributors section
Just want same in moksh to show who all have contributed to moksh

**Comment by vaibhavmishra4g** [comment]
yes i've checked the website, so you just want to update the contributors section?

**Comment by akshitagupta15june** [comment]
yes

**Comment by vaibhavmishra4g** [comment]
great, i'm working on it now
