### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#834]
<img width="906" alt="Screenshot 2023-06-20 at 7 13 35 PM" src="https://github.com/akshitagupta15june/Moksh/assets/95973644/3766e21f-4bb4-4134-9d68-ca7798c8fa20">

Make it more elaborate for new contributors to understand how to go about with the github commands

**Comment by karthiknadar1204** [comment]
I would like to work on this issue undergssoc'23

**Comment by debdutta04** [comment]
i would like to work on this

**Comment by karthiknadar1204** [comment]
@debdutta04 The issue has already been wrapped up, please explore other issues to contribute to
