### ISSUE TITLE
[FEATURE REQUEST] Custom UI for 404 page

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [akshitagupta15june/Moksh#839]
## Description

**Is your feature request related to a problem? Please describe.**
The 404 page not found is the default github pages template. We can make our custom 404 page relating to our UI theme.

**Describe the solution you'd like**
A new component to design 404 page.

**Screenshots or Mockups** (optional)
![image](https://github.com/akshitagupta15june/Moksh/assets/83866602/0b410ada-ec30-4ead-960a-6aec83172b3a)

**Comment by karthiknadar1204** [comment]
@OMKAR-KALEPU A 404 page might require routes but since this is a pure HTML CSS project, we don't need one .
Please explore other issues to contribute to.
Please close this issue for now.
Thank you
