### ISSUE TITLE
add a switch for dark and light functionality in index page 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#84]
take reference from this website https://akshitagupta15june.github.io/PetMe/
petme https://github.com/akshitagupta15june/PetMe

**Comment by mud1tx** [comment]
@akshitagupta15june I can work on this please assign it to me.

**Comment by akshitagupta15june** [comment]
ok

**Comment by mud1tx** [comment]
@akshitagupta15june Do I have to create the full logic for dark and light mode? I can do that.

**Comment by akshitagupta15june** [comment]
Yes you have to, please check petme first for the dark and bright feature

**Comment by karthiknadar1204** [comment]
@mud1tx are you still working on this issue

**Comment by mud1tx** [comment]
@karthiknadar1204 yes I am working.

**Comment by mud1tx** [comment]
@akshitagupta15june I have send the PR related to this issue
