### ISSUE TITLE
Adding Contact Us[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by vaanyasharmaaa** [akshitagupta15june/Moksh#849]
## Adding Contact Us form 

**Is your feature request related to a problem? Please describe.**
At the end of the homepage, the contact us option doesn't respond, therefore I would like to add an extra page of Contact Us. 
**Describe the solution you'd like**
When we click on contact us, we will be redirected to a contact Us page, which will be a form, where people can add their name, email and message that they would like to send us.

## Additional Information

With the help of Contact Us form, people will be able to reach out to Moksh team with their concerns, appreciations, doubts etc.
**This will bring in inclusivity.** 
  
#### After the new feature is added:

![2023-06-21 (5)](https://github.com/akshitagupta15june/Moksh/assets/130481025/5e9c11d2-120d-4baa-a095-ee628d5bfce9)

#### Addition feature:
The form shows a message if we don't fill out all the required information 

![Screenshot 2023-06-21 154905](https://github.com/akshitagupta15june/Moksh/assets/130481025/3e180eff-5fe5-4635-a32d-f0fd68da544f)

**Priority** 
High Priority

**Comment by vaanyasharmaaa** [comment]
@akshitagupta15june Kindly assign me this issue under GSSOC'23

**Comment by akshitagupta15june** [comment]
hey contact us is not required currently
