### ISSUE TITLE
{GSSoc'23} Improve SEO of the website

### ISSUE THREAD

**Issue by Daksh-Goel12** [akshitagupta15june/Moksh#857]
![image](https://github.com/akshitagupta15june/Moksh/assets/123328399/4b425b39-7b33-4a3e-a8be-5426f6db191a)

The website does not have optimized image formats. There is also no meta description and links are not descriptive. I can help to improve the performance and SEO of the website. I am a GSSOC'23 contributor . Please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
its completed
