### ISSUE TITLE
[FEATURE REQUEST] Design Navbar for iskcon oage

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/Moksh#861]
## Description

**Is your feature request related to a problem? Please describe.**
In this issue, you have to Design the navbar on the iskcon page same as the navbar on the index page.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**
Make the navbar responsive as well, please be sure to share the screenshots of the changes implemented in your pull request.

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).
High

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Developer-Swati** [comment]
Please assign it to me @karthiknadar1204  sir

**Comment by akshitagupta15june** [comment]
ok

**Comment by akshitagupta15june** [comment]
make it similar to index.html

**Comment by Developer-Swati** [comment]
Ok mam

**Comment by Developer-Swati** [comment]
![iskonpage](https://github.com/akshitagupta15june/Moksh/assets/125959657/61372898-66c3-41e8-b8da-714bbbf36466)


So, I have to make this page to be look like this

![index](https://github.com/akshitagupta15june/Moksh/assets/125959657/6dbff194-d377-4b4f-a0c5-b8833d1e88e9)
Right @akshitagupta15june  mam?

**Comment by akshitagupta15june** [comment]
No just update the navbar

**Comment by Developer-Swati** [comment]
ok means navbar of iskcon page should be same as navbar of index page ?

**Comment by Developer-Swati** [comment]
Hello @akshitagupta15june  mam, the left side of Iskcon page has been updated and it looks like this :-

![leftside](https://github.com/akshitagupta15june/Moksh/assets/125959657/b92aa677-fdeb-4614-acf1-e9102ccb9a99)

But there is a problem on the right hand side of navbar of Iskcon page . I have to make it looks like index page so I tried to add the same CSS as in index page but it did not work . Screenshots are here:- 
Code

![navbar](https://github.com/akshitagupta15june/Moksh/assets/125959657/66fb5163-cbe4-4756-86db-d6231458bdc2)

Output

![home](https://github.com/akshitagupta15june/Moksh/assets/125959657/57aaa25a-9289-48ba-92c5-a7a24f0816cf)

It does not reflect CSS when I do hover on it .

Also, the dropdown icon does not fits well . On index page viewbox is 0,0,24,24 but when I do the same on Iskcon page the it looks very large then I tried to adjust it and end up with these negative values which is totally wrong in case of distance and height. 
code 

![dropdowncode](https://github.com/akshitagupta15june/Moksh/assets/125959657/1b98fd03-ba22-43ce-8ebc-78de29579396)

output

![dropdownoutput](https://github.com/akshitagupta15june/Moksh/assets/125959657/660371cd-de87-4730-8f86-533a06f5f0f5)

So, I am not getting what's wrong with this . 
Is there anything that has been applied or used in Index  page or may be I have to add some css file existing in the codebase or anything . 
Please help @akshitagupta15june  mam or @karthiknadar1204  sir .

**Comment by Developer-Swati** [comment]
Is it ok or not @akshitagupta15june  mam / @karthiknadar1204  sir ?


![Uploading okdropdown.PNG…]()

**Comment by Developer-Swati** [comment]
Hello @akshitagupta15june  I was working on it but now I have seen that the event page has been completely changed so I request you to please close this issue and assign me some other issue.
Thanks

**Comment by akshitagupta15june** [comment]
Sure I will keep in mind
Remind me in channel once too to assign u on priority

**Comment by Developer-Swati** [comment]
Ok @akshitagupta15june
