### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#872]
https://akshitagupta15june.github.io/Moksh/
Need a good background picture for index.html, it should be bright and keep theme on mind also share the pictures here before creating pr to get it approved

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue. Please assign me under GSSOC'23

**Comment by anand2025** [comment]
I would like to work on this issue. Ma'am please assign it to me under GSSOC'23

**Comment by akshitagupta15june** [comment]
assigning

**Comment by Vidip-Ghosh** [comment]
1. 
https://www.canva.com/design/DAFmvsQZJFQ/615T_JPgKhJ7SEnJwRcapQ/edit?utm_content=DAFmvsQZJFQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

2. 
https://www.canva.com/design/DAFmvs7ldMo/X2RiEZf2ZfxFHfP9aAHPxQ/edit?utm_content=DAFmvs7ldMo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

@akshitagupta15june I have found these. Can you please check which one is alright?

**Comment by akshitagupta15june** [comment]
Second design is not preferable as it is dark and first one is more like a travel websites background
Theme should be of meditation peace spirituality

**Comment by Vidip-Ghosh** [comment]
1.
https://www.canva.com/design/DAFmwYRmm6E/4TDBKX4n-g9bX3AZ2SHLRQ/edit?utm_content=DAFmwYRmm6E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

2.
https://www.canva.com/design/DAFmwZ8jSxU/PFIJmUhQEp88SSFJtZMMBg/edit?utm_content=DAFmwZ8jSxU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

3.
https://www.canva.com/design/DAFmweFnoNU/q6JWp0VhNI0kNGLb3Dn8Uw/edit?utm_content=DAFmweFnoNU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

What about these three?

**Comment by akshitagupta15june** [comment]
I liked the second picture also is it possible can we have a picture with "om" ॐ and also Buddha ji too but I think if ॐ will be there it will be perfect

**Comment by Vidip-Ghosh** [comment]
> I liked the second picture also is it possible can we have a picture with "om" ॐ and also Buddha ji too but I think if ॐ will be there it will be perfect

Can you please suggest some good color for "om" ॐ ?

**Comment by akshitagupta15june** [comment]
Yellow or a mix of colours
You can also share in discord channel so it will be easy for you
