### ISSUE TITLE
[FEATURE REQUEST] Add same footer as in index.html in ar meditation page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#880]
https://akshitagupta15june.github.io/Moksh/AR_Meditate/meditation.html

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by Developer-Swati** [comment]
Please assign it to me

**Comment by anand2025** [comment]
I would like to work on this issue please assign it to me under GSSOC'23

**Comment by dishamodi0910** [comment]
I would like to work on this issue. Please assign it to me. @akshitagupta15june

**Comment by gauravsingh1281** [comment]
@akshitagupta15june  please assign this issue to me because I want to work on it.

**Comment by akshitagupta15june** [comment]
assigning
