### ISSUE TITLE
[STYLE CHANGE] Updating the footer style

### ISSUE THREAD

**Issue by Shaba1406** [akshitagupta15june/Moksh#888]
**Description:**

I want to improve in the footer section

**Reason for Change:**

footer section should be more cleared and updated 

**Proposed Styling:**

want to add a seperate columns for features contacts and fixing the alignments

Please assign me under the Girlscript summer of code 2023

**Comment by ankitjt** [comment]
changes related to footer will be merged soon, pl do a new fetch in some time.
