### ISSUE TITLE
[STYLE CHANGE] Improve UI

### ISSUE THREAD

**Issue by MisterMickey** [akshitagupta15june/Moksh#890]
**Description:**

Improve UI

**Reason for Change:**

To make the website better in UI/UX

**Current Styling:**

1. Text in card is not center aligned
2. XPRESSION'23 in not a hyperlink

**Proposed Styling:**

1. Center align text in cards
2. make XPRESSION'23 hyperlink

**Screenshots or Design Mockups (optional):**

![Screenshot from 2023-06-24 17-01-31](https://github.com/akshitagupta15june/Moksh/assets/93720428/ca8143bb-4ba0-4123-8788-9f8d9248ec12)
![Screenshot from 2023-06-24 17-01-17](https://github.com/akshitagupta15june/Moksh/assets/93720428/893e440b-0f1a-4905-af5b-de83164c52e6)

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Comment by MisterMickey** [comment]
@akshitagupta15june Kindly assign me this issue.

**Comment by akshitagupta15june** [comment]
Hey right now website don't need any ui changes
If required I will create issues

**Comment by MisterMickey** [comment]
@akshitagupta15june But at least the XPRESSION'23 has to be hyperlink.
