### ISSUE TITLE
website not responsive for small devices

### ISSUE THREAD

**Issue by techmannih** [akshitagupta15june/Moksh#891]
## Before creating an issue, go through all open/closed issues to avoid getting your issue/suggestion marked as duplicate##

**Issue and Steps to Reproduce:**
hello @akshitagupta15june,
I found an issue in your website " Moksh" which is not responsive moblie and tablet devices please check it
And I want to work on this issue ...please assign me of this issue

**Screenshots:**
![2023-06-24-20_38_59-screenshot](https://github.com/akshitagupta15june/Moksh/assets/125847751/37fa7099-2792-4dea-bf44-467f85f59b91)

**Expected:**

**Actual:**

**Additional Details:**

**Comment by akshitagupta15june** [comment]
Assigning you
