### ISSUE TITLE
[BUG] remove the extra icon from navbar

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#899]
https://akshitagupta15june.github.io/Moksh/Blogs/depression.html
![image](https://github.com/akshitagupta15june/Moksh/assets/57909583/d818e2a4-3f42-414c-b3fd-366136073290)

**Comment by smritimangal26** [comment]
Please assign me this

**Comment by debdutta04** [comment]
I would like to work on this issue please assign me

**Comment by RitiChandak** [comment]
I would like to work on this issue please assign me this under GSSoC'23

**Comment by akshitagupta15june** [comment]
assigned

**Comment by smritimangal26** [comment]
you have created this issue twice
