### ISSUE TITLE
Improve the iskcon events page with more features

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#9]
you can suggest some changes that can be made in iskcon events page https://akshitagupta15june.github.io/Moksh/event.html

**Comment by BrightTNut** [comment]
hi I think on place of box of upcoming event we can use 'new' gif
it look attentive and impressive
below is 'new' gif 
![new](https://user-images.githubusercontent.com/118769123/232763384-04b8bf1b-6cd0-4918-b5c3-596c934a2b9e.gif)

**Comment by karthiknadar1204** [comment]
@akshitagupta15june please assign this issue to me,i would like to work on this issue.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by karthiknadar1204** [comment]
I am already working on this issue @Hritik1503
