### ISSUE TITLE
index footer about should redirect to the mental health problems section in same page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#901]
https://akshitagupta15june.github.io/Moksh/index.html#

**Comment by rayarka26** [comment]
Please assign me this issue

**Comment by debdutta04** [comment]
I would like to work on this issue please assign me

**Comment by gauravsingh1281** [comment]
@akshitagupta15june  Please assign this issue to me I want to work on it.

**Comment by debdutta04** [comment]
I would like to work on this issue please assign me @akshitagupta15june

**Comment by abhinav-m22** [comment]
Please assign me the issue @akshitagupta15june

**Comment by akshitagupta15june** [comment]
assigned
