### ISSUE TITLE
[FEATURE REQUEST] add a google language translate in navbar of index page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#906]
https://akshitagupta15june.github.io/Moksh/index.html

**Comment by debdutta04** [comment]
I would like to work on this issue

**Comment by MisterMickey** [comment]
Want to work on the issue, Kindly assign me.

**Comment by akshitagupta15june** [comment]
assigned

**Comment by RitiChandak** [comment]
I would like to work on this please assign me this issue

**Comment by ayushrathore111** [comment]
@akshitagupta15june I want to work on this please assign this to me 
thank you
