### ISSUE TITLE
Spelling mistake in README.md file

### ISSUE THREAD

**Issue by gauravsingh1281** [akshitagupta15june/Moksh#908]
<img width="956" alt="Screenshot 2023-06-25 140742" src="https://github.com/akshitagupta15june/Moksh/assets/85905403/5d2f5615-6fb8-441a-8892-cd136c4481c3">

**Comment by debdutta04** [comment]
please assign me this

**Comment by gauravsingh1281** [comment]
@akshitagupta15june please assign this issue to me because I have raised the issue first.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on this project @akshitagupta15june

**Comment by karthiknadar1204** [comment]
@gauravsingh1281 Will assign it soon
Thank you for patience

**Comment by akshitagupta15june** [comment]
- [ ] assigned
