### ISSUE TITLE
[BUG] the learn-more button is not designed correctly in motivation.html page

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#915]
## Description
the learn more button is mixed with the color of the background

**Expected behavior:**
it should be kept with some good styling

**Actual behavior:**
when we hovering and not hovering on it.
![Screenshot (360)](https://github.com/akshitagupta15june/Moksh/assets/124120102/b6cc8cd3-977b-4607-b66c-ef4efaf6ac14)

## Reproduction Steps
we can give it good styling by increasing the font of the text inside the button and giving it appropriate colors so that it looks good.

**Comment by khadar1020** [comment]
please assign me this issue

**Comment by karthiknadar1204** [comment]
@khadar1020 The Shlok page is currently being revamped, please explore other issues for the time being.
Thank you
