### ISSUE TITLE
[BUG] Favicon not present on some pages

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/Moksh#919]
## Description

**Describe the bug:**

Hey, @akshitagupta15june Favicon is not present on some of the pages link blogs and rejuvenate. Please assign me this issue. Thank you!

**Expected behavior:**
Favicons should be present ton all pages

**Actual behavior:**
Favicons is not present on these pages.

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
A clear and concise description of what you expected to happen at each step.

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/100675296/22c0db1f-5342-4f8d-89e0-1fb97832950c)
![image](https://github.com/akshitagupta15june/Moksh/assets/100675296/52b0ff3c-f1ec-41ed-a074-a4dec0b29ce1)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by akshitagupta15june** [comment]
its not required
