### ISSUE TITLE
Umprove the divine activity page all images have distorted

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#92]
https://akshitagupta15june.github.io/Moksh/story.html

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I want to work on this issue. please assign it to me.

**Comment by karthiknadar1204** [comment]
@akshitagupta15june i would like to work on this issue,please assign it to me

**Comment by karthiknadar1204** [comment]
Will get it done by tonight

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Lavesh12** [comment]
Can I work on this issue?
