### ISSUE TITLE
[STYLE CHANGE] 

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/Moksh#920]
**Description:**

Hey, @akshitagupta15june The navbar and footer should be consistent across all the pages for a better user experience. Please assign me this issue. Thank you!

**Reason for Change:**

Bad user experience

**Current Styling:**

Navbar and footer inconsistent across the pages.

**Proposed Styling:**

Navbar and footer same on all the pages.

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by karthiknadar1204** [comment]
@sumitkr2000 The pages are being revamped right now by the moderators, also in an attempt to make the navbar and footer consistent across all the pages, please close this issue for now and explore other issues to contribute to.

**Comment by sumitkr2000** [comment]
Okay @karthiknadar1204
