### ISSUE TITLE
[STYLE CHANGE] Make the information of the footer responsive on small screens

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/Moksh#921]
**Description:**

Hey @akshitagupta15june The information present in the footer is not responsive and is not looking good on small-screen devices. Please assign me this issue. Thank you!

**Reason for Change:**

Better UI 

**Current Styling:**

Displaying in row

**Proposed Styling:**

Display in column

**Screenshots or Design Mockups (optional):**

![image](https://github.com/akshitagupta15june/Moksh/assets/100675296/8d4a8aa9-e0bd-4785-8f1f-2bc34633d108)

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

By changing the flex-direction from row to column

**Comment by ankitjt** [comment]
changes related to footer will be merged soon, pl do a new fetch in some time.

**Comment by sumitkr2000** [comment]
okay sure!
