### ISSUE TITLE
[FEATURE REQUEST] making footer looking good.

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#923]
## Description
making the footer look more attractive like 
![Screenshot (365)](https://github.com/akshitagupta15june/Moksh/assets/124120102/feaa907f-09aa-4781-8fcb-c580f39d5b89)
![Screenshot (366)](https://github.com/akshitagupta15june/Moksh/assets/124120102/217fa860-bb12-4e27-8f8b-caa9a5c02f85)

**Describe the solution you'd like**
we can change the styling of the footer.

##before
![Screenshot (368)](https://github.com/akshitagupta15june/Moksh/assets/124120102/87c53a67-bef8-4ace-8c12-fc1720be86c0)

**Comment by khadar1020** [comment]
please assign me this issue

**Comment by khadar1020** [comment]
[ankitjt](https://github.com/ankitjt) please assign me this issue

**Comment by khadar1020** [comment]
[akshitagupta15june](https://github.com/akshitagupta15june) please assign me this issue

**Comment by akshitagupta15june** [comment]
we don't have such channel for moksh
