### ISSUE TITLE
[FEATURE REQUEST] footer of Great People 

### ISSUE THREAD

**Issue by khadar1020** [akshitagupta15june/Moksh#924]
## Description

we can add a quote at the footer or some design.

![Screenshot (371)](https://github.com/akshitagupta15june/Moksh/assets/124120102/e47095b1-b2bd-4d0b-90ae-9cd2826db00a)

**Comment by khadar1020** [comment]
please assign me this issue

**Comment by ankitjt** [comment]
there's a quote section for quotes.
