### ISSUE TITLE
[FEATURE REQUEST]  Create a Fixed Header on Scroll for Blogs page 

### ISSUE THREAD

**Issue by GauriBhandari** [akshitagupta15june/Moksh#929]
## Description

For the blogs page their is no fixed header used. This disturbs the reading of the blogs. 

**Describe the solution you'd like**
A fixed header is a smart navigation tool that causes the header of a website to remain at the top of the page as a user scrolls up and down. Using this method the header and site navigation are always on the top of the scrolled page.
This will make the page more readable.

**Comment by GauriBhandari** [comment]
@akshitagupta15june Would you please assign me this issue under GSSOC'23 
I would like to contribute to this issue

**Comment by GauriBhandari** [comment]
Hello ma'am, It's been a long time since I created this issue. Please assign me this issue. I would like to contribute to this project.

**Comment by ankitjt** [comment]
changes related to the blog section will be merged soon, pl do a new fetch in some time.
