### ISSUE TITLE
[STYLE CHANGE] add new logo in blog section

### ISSUE THREAD

**Issue by devWonderkind** [akshitagupta15june/Moksh#934]
**Description:**
I wanna change moksh new logo in POWER OF KNOWLEDGE BLOGS section navigation bar.

**Reason for Change:**
[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]
The Moksh logo is changed now that's an old one.

**Screenshots or Design Mockups (optional):**
[If available, include relevant screenshots or design mockups illustrating the requested style changes.]
![moksh](https://github.com/akshitagupta15june/Moksh/assets/110322061/6b3aaabf-623f-4983-b300-71ded70eede6)

**Additional Information (optional):**

@akshitagupta15june please assign this issue to me. I want to work on this issue under GSSoC'23.

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by ankitjt** [comment]
changes related to the blog section will be merged soon, pl do a new fetch in some time.
