### ISSUE TITLE
[FEATURE REQUEST] Migrating Website to Next.js, TypeScript, and Tailwind CSS

### ISSUE THREAD

**Issue by s2sharpit** [akshitagupta15june/Moksh#935]
## Description
I would like to propose migrating our website to Next.js, TypeScript, and Tailwind. I believe that this would improve the performance, maintainability, and overall quality of our website.

## Benefits of migrating to Next.js
- **Performance**: Next.js is a server-rendered framework, which means that our website will be pre-rendered on the server before it is sent to the client. This will improve the loading speed of our website, especially for users with slow internet connections.
- **Maintainability**: Next.js is built on top of React, so we will be able to use all of the same React components and libraries that we are already using. This will make it easier to maintain our website, as we will not have to learn a new framework.
- **Quality**: Next.js comes with a number of features that can help us to improve the quality of our website, such as automatic code splitting, static site generation, and server-side rendering. These features can help us to improve the performance, SEO, and security of our website.

## Benefits of using TypeScript
- **Type safety**: TypeScript is a typed language, which means that the compiler will check the types of our variables and expressions. This can help us to catch errors at compile time, rather than at runtime.
- **Code clarity**: TypeScript can help to make our code more clear and concise. This is because TypeScript allows us to use type annotations to document our code.
- **Refactoring**: TypeScript can make it easier to refactor our code. This is because the compiler will be able to check that our code is still valid after we have made changes.

## Benefits of using Tailwind CSS
- **Speed**: Tailwind CSS is a utility-first CSS framework, which means that we can only import the CSS that we need. This can help to improve the loading speed of our website.
- **Flexibility**: Tailwind CSS is very flexible, which means that we can customize the look and feel of our website without having to write a lot of CSS.
- **Simplicity**: Tailwind CSS is very simple to learn and use. This makes it a good choice for beginners and experienced developers alike.

## Proposal
I propose that we start migrating our website to Next.js, TypeScript, and Tailwind in the next sprint. I have already created a starter project that we can use as a starting point. I would be happy to help with the migration process.

## Questions
- Do you have any questions about my proposal?
- Are you interested in starting the migration process in the next sprint?

**Comment by s2sharpit** [comment]
Hey @akshitagupta15june 

I would like to work on this under GSSoC.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by karthiknadar1204** [comment]
@s2sharpit This project is intended to be beginner friendly for people just getting started out so we don't plan on migrating to a new tech stack any time sooner.
Please close this issue for now and explore the tissues to contribute to.
Thank you

**Comment by s2sharpit** [comment]
> @s2sharpit This project is intended to be beginner friendly for people just getting started out so we don't plan on migrating to a new tech stack any time sooner. Please close this issue for now and explore the tissues to contribute to. Thank you

Thank you for considering my proposal and providing your feedback. I completely understand the intention to keep the project beginner-friendly, and I appreciate your perspective.

While I agree that introducing a new tech stack can have its complexities, I'd like to emphasize the potential benefits it could bring, particularly in terms of performance, maintainability, and overall quality. However, I respect the decision to prioritize a beginner-friendly environment.

If there are any specific areas within the current tech stack where improvements could be made, I'd be more than happy to contribute and help enhance the project in any way possible.

Once again, thank you for your time and consideration. I'll be exploring other issues to contribute to and supporting the project in any way I can
