### ISSUE TITLE
[BUG] Page Blinking with Language Selection and Request for Voice Feature in Shlok Page

### ISSUE THREAD

**Issue by Nishitbaria** [akshitagupta15june/Moksh#945]
## Description
The current implementation of the language change feature on the Shlok page is causing the page to blink and continuously change languages every second, which is highly disruptive and annoying to users. Additionally, it would be beneficial to include a voice feature that allows users to listen to the Shloks instead of just reading them.

**Describe the bug:**
The page continuously blinks and changes languages when using the select language option on the Shlok page. This behavior is not expected and negatively affects the user experience.

**Expected behavior:**
When selecting a language from the language dropdown, the page should update to display the Shloks in the selected language without any blinking or continuous changes.
**Actual behavior:**
Upon selecting a language, the page starts blinking and rapidly changes languages, causing frustration and confusion for the user experience.
## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to the Shlok page.
2. Locate the language select dropdown.
3. Select a different language from the dropdown.
4. Observe the page behavior.

**Expected result:**
After selecting a language, the page should update once to display the Shloks in the selected language, without any continuous blinking or changes.

**Actual result:**
Upon selecting a language, the page starts blinking and rapidly changes languages, making it difficult to read and navigate the content.
## Screenshots
[Plzz checkout video](https://github.com/akshitagupta15june/Moksh/assets/85815172/cf0441dd-1a78-4881-ad78-ec390e5e05aa) 

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,please look into this issue and assign me

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,please review my pull request

**Comment by Nishitbaria** [comment]
@akshitagupta15june ,why you closed issue?
