### ISSUE TITLE
Navbar menus should be highlighted

### ISSUE THREAD

**Issue by 777Prabhjot** [akshitagupta15june/Moksh#95]
Navbar menu items should be highlighted according to the page right now only the home text is highlighted.

**Screen shot**
<img width="959" alt="Screenshot 2023-04-27 152143" src="https://user-images.githubusercontent.com/68184118/234827497-434a760e-b2c7-4f25-ad7e-569685285b9e.png">

### **I would love to work on this**

**Comment by Lavesh12** [comment]
Can I work on this issue?

**Comment by kasturimandlik** [comment]
I would like to work on this issue under GSSOC'23. please assign me this issue

**Comment by ankitjt** [comment]
Navbar is updated, you can check the blog and the meditation page for reference, it'll soon reflect on all pages.
@akshitagupta15june to close.
