### ISSUE TITLE
[STYLE CHANGE] : Shlok section

### ISSUE THREAD

**Issue by Yashika-Agrawal** [akshitagupta15june/Moksh#951]
**Description:**
![image](https://github.com/akshitagupta15june/Moksh/assets/97408966/51714fda-5485-4b93-bd3b-b31947a5ee22)
The content and the logo are not properly aligned and the content is going out of the box.

**Reason for Change:**
The logo should be in left and the content should be in right with properly aligned in center which enhances readability, user friendly and appealing. to view.

**Current Styling:**
Currently the logo is in left and the content is bottom of it and also going beyond the white box.

**Proposed Styling:**
The content should be in right to the logo and aligned in center with the white box .

**Priority Level (optional):**
- [ ] Low
- [X] Medium
- [ ] High

**Comment by Yashika-Agrawal** [comment]
Hey, @ankitjt @akshitagupta15june , please assign me this issue under GSsoc'23 contribution.

**Comment by akshitagupta15june** [comment]
hey the footer is changed now!
Thanks
