### ISSUE TITLE
[BUG] The menu button in the "Articles" blog under the "Power Of Knowledge Blogs" section  does not respond on clicking❗⚠️

### ISSUE THREAD

**Issue by Sch476** [akshitagupta15june/Moksh#962]
## Description
On clicking on the menu button in the articles of the "Power Of Knowledge Blogs" section of the website, the button does not send any response. It may be an issue because any action has not been assigned to this button.

**Expected behavior:**

**Actual behavior:**
A clear and concise description of what actually happened.

## Reproduction Steps
1) Open "https://akshitagupta15june.github.io/Moksh/index.html".
2) Click on "Power of Knowledge Blogs" in the navbar of the website.
3) Scroll Down to "Articles" section and click on "READ" on the first or the third article.
4) Click on the menu button.

**Expected result:**
On Clicking on the Menu button in the Articles, the button should respond and give us the options to navigate to different parts of the website.

**Actual result:**
On Clicking on the Menu button in the Articles, the button does not show any result, or the button does not show any response.

## Screenshots

https://github.com/akshitagupta15june/Moksh/assets/127319225/773b7bb0-1c6d-481f-881a-659a9458fcbd

## Additional Information

**Device (please complete the following information):**
- OS: Windows 11
- Browser :BRAVE
- Version : 2H22

**Additional context:**

I can fix this problem by adding a small drop-down menu which helps the user to navigate to a different part of the website.

THANK YOU,
Sayantan Choudhury
GSSOC'23 Contributor

**Comment by ankitjt** [comment]
Blogs UI is changed, pl wait as those changes will be merged soon.
