### ISSUE TITLE
[BUG] Change in button

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#963]
## Description

**Describe the bug:**
This button does not provide any significance of whether to scroll down or any other purpose.

**Expected behavior:**
There should be clear understanding of button.

We can add a scroll-down icon to make sure that users get a clear understanding.

## Screenshots
<img width="948" alt="Screenshot 2023-07-01 021610" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/1e9966f7-bd3e-4f34-8a52-2f77b7a02b2b">

<img width="243" alt="Screenshot 2023-07-01 021559" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/129dc28e-da8f-44ae-a999-c70b4b82d205">

*Please assign this to me under gssoc'23* @akshitagupta15june

**Comment by ankitjt** [comment]
it implies to scroll down .
