### ISSUE TITLE
[FEATURE REQUEST] Hovering effect on social media icons

### ISSUE THREAD

**Issue by DivyanshiNarang** [akshitagupta15june/Moksh#964]
Addition of hovering effect on social media icons to make website more attractive.

<img width="915" alt="Screenshot 2023-07-01 022034" src="https://github.com/akshitagupta15june/Moksh/assets/74779601/fc2c01ab-1216-4071-af4c-985b53de4e1c">

@akshitagupta15june Please assign this issue to me under gssoc'23.

**Comment by arihantJ24** [comment]
can u please assign this issue to me
