### ISSUE TITLE
[FEATURE REQUEST]  SLIDE DOWN FEATURE TO NAVBAR

### ISSUE THREAD

**Issue by rituk2002** [akshitagupta15june/Moksh#969]
## Description

**Is your feature request related to a problem? Please describe.**
I want to add a Slide Down to the navbar on scrolling.

**Describe the solution you'd like**
Create a nav-bar div that will contain all the elements of the navbar and then provide the required CSS and JavaScript code to it. This will give an enhanced look to the homepage.

**Describe alternatives you've considered**
I would come up with an alternate solution but I am sure the solution I provided will surely work.

## Additional Information

**Context**
I want to add a Slide Down to the navbar on Scrolling.

**Screenshots or Mockups** (optional)
![Screenshot (4)](https://github.com/akshitagupta15june/Moksh/assets/129873202/7f1334e1-3beb-4b55-b806-5f0c5518464d)

**Priority** (optional)
Medium.

**Comment by rituk2002** [comment]
Please assign me this issue @akshitagupta15june

**Comment by ankitjt** [comment]
I don't understand what slide down feature do you want to add? Navbar moves with page so it is accessible.

**Comment by rituk2002** [comment]
https://github.com/akshitagupta15june/Moksh/assets/129873202/e94d9071-4465-449b-a9bf-1603d8af1136

I was talking about this feature, as when the website will open it will give alike full-screen view of the first page(containing buddha photo) and when a person will scroll down the navbar will be visible.

**Comment by ankitjt** [comment]
it was like that initially but was changed so that the links are visible when user visits the website. 

Pl look for some other issues to contribute.
