### ISSUE TITLE
[BUG] Save functionality isn't working in the blog cards

### ISSUE THREAD

**Issue by Akanksha-202** [akshitagupta15june/Moksh#975]
## Description

**Describe the bug:**
![image](https://github.com/akshitagupta15june/Moksh/assets/100708686/ab3cffe2-0f9d-46a7-a9fe-ae40a64805b1)
Clicking on the save buttons does nothing.

**Expected behavior:**
The blog should get saved in the "Save Blogs" section.

**Actual behavior:**
Nothing is happening.

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Adding simple email authentication via Firebase for a user to log in,
2. Adding a section of "Saved Blogs" only when the user is logged in.
3. Saving the particular blogs in that section whenever the user reads the blog and wants to save it.

**Expected result:**
Customized section of the blogs, the user likes.

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]-> Windows
- Browser [e.g., Chrome, Safari, Firefox]-> Microsoft Edge

**Additional context:**

Assign this issue to me under GSSoC'23 label :)

**Comment by ankitjt** [comment]
there is no database feature in the project as of now, saving an article will not work atm.

**Comment by Akanksha-202** [comment]
I can add
