### ISSUE TITLE
[FEATURE REQUEST] A BLOG ON THE IMPORTANCE OF MINDFULNESS

### ISSUE THREAD

**Issue by GiriprasadKrishnamurthy** [akshitagupta15june/Moksh#986]
I have a very informative and interactive idea in mind to mention about the importance of mind over matter and how can we live in the present with the strength of this mind
Could you please give met he opportunity to contribute here @akshitagupta15june

**Comment by ankitjt** [comment]
you can create the blog, share the google doc in the moksh discord group, and if it gets accepted we will publish it with credit.
