### ISSUE TITLE
[BUG] iskcon page is not responsive 

### ISSUE THREAD

**Issue by RitiChandak** [akshitagupta15june/Moksh#994]
## Description

**Describe the bug:**
Iskcon page is not responsive to other devices 

**Expected behavior:**

**Actual behavior:**

## Reproduction Steps

**Steps to reproduce the behavior:**

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots

![image](https://github.com/akshitagupta15june/Moksh/assets/96969496/ac277a21-3206-40b8-8a41-eafe3cad7437)

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Additional context:**

**Comment by akshitagupta15june** [comment]
some are working on it
