### ISSUE TITLE
[FEATURE REQUEST] Adding a chatbot

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/Moksh#996]
## Description

**Is your feature request related to a problem? Please describe.**
A chatbot is a must of any of the websites

**Describe the solution you'd like**
A chatbot integrated with the website to enhance the user-experience!!

**Describe alternatives you've considered**

## Additional Information

**Context**
Please assign me this issue under GSSOC'23 @akshitagupta15june

**Comment by akshitagupta15june** [comment]
hey its not required currently 
Thanks
